### ISSUE TITLE
[BUG] Plugin not enabling at startup.

### ISSUE THREAD

**Issue by qzod** [booksaw/BetterTeams#15]
**Describe the bug**
Plugin will not enable at startup.

**To Reproduce**
1. Just try to use the plugin on the same PaperSpigot build I'm using.

**Expected behaviour**
For the plugin to enable. It says it is tested on 1.16.

**Details**
Using PaperSpigot-1.16.1 Build 82.
Using latest version of Better Teams (v3.0.10)

This is the error it's throwing.
`[Server thread/INFO]: [BetterTeams] Enabling BetterTeams v3.0.10
[Server thread/ERROR]: Error occurred while enabling BetterTeams v3.0.10 (Is it up to date?)
java.lang.NullPointerException: null
	at com.booksaw.betterTeams.Main.onEnable(Main.java:97) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.16.1.jar:git-Paper-82]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:380) ~[patched_1.16.1.jar:git-Paper-82]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483) ~[patched_1.16.1.jar:git-Paper-82]
	at org.bukkit.craftbukkit.v1_16_R1.CraftServer.enablePlugin(CraftServer.java:500) ~[patched_1.16.1.jar:git-Paper-82]
	at org.bukkit.craftbukkit.v1_16_R1.CraftServer.enablePlugins(CraftServer.java:414) ~[patched_1.16.1.jar:git-Paper-82]
	at net.minecraft.server.v1_16_R1.MinecraftServer.loadWorld(MinecraftServer.java:471) ~[patched_1.16.1.jar:git-Paper-82]
	at net.minecraft.server.v1_16_R1.DedicatedServer.init(DedicatedServer.java:241) ~[patched_1.16.1.jar:git-Paper-82]
	at net.minecraft.server.v1_16_R1.MinecraftServer.v(MinecraftServer.java:940) ~[patched_1.16.1.jar:git-Paper-82]
	at net.minecraft.server.v1_16_R1.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[patched_1.16.1.jar:git-Paper-82]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_242]
[Server thread/INFO]: [BetterTeams] Disabling BetterTeams v3.0.10`

**Comment by qzod** [comment]
I've just resolved the issue myself. By installing PlaceholderAPI it enabled the plugin. But you should probably put it as a dependency on the plugins Spigot page.

**Comment by booksaw** [comment]
Thanks for the report, this has been a known bug and is going to be patched in the next update. For now, I am going to update the plugin page to include a warning about the current state of the plugin.
