### ISSUE TITLE
[ERROR] WorldGuard initializing BetterTeams 1.12.2

### ISSUE THREAD

**Issue by dogi-dogi** [booksaw/BetterTeams#173]
just plugin loading error / not working

v 1.12.2
paper spigot
worldguard-bukkit-6.2.2

[03:19:53 INFO]: [BetterTeams] Loading BetterTeams v4.0.0
[03:19:53 ERROR]: [org.bukkit.craftbukkit.v1_12_R1.CraftServer] com/sk89q/worldguard/WorldGuard initializing BetterTeams v4.0.0 (Is it up to date?)
java.lang.NoClassDefFoundError: com/sk89q/worldguard/WorldGuard
        at com.booksaw.betterTeams.integrations.WorldGaurdManager.<init>(WorldGaurdManager.java:26) ~[?:?]
        at com.booksaw.betterTeams.Main.onLoad(Main.java:147) ~[?:?]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.loadPlugins(CraftServer.java:323) ~[Paper.jar:git-Paper-1618]
        at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:222) ~[Paper.jar:git-Paper-1618]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:616) ~[Paper.jar:git-Paper-1618]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_281]
Caused by: java.lang.ClassNotFoundException: com.sk89q.worldguard.WorldGuard
        at java.net.URLClassLoader.findClass(Unknown Source) ~[?:1.8.0_281]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:156) ~[Paper.jar:git-Paper-1618]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:104) ~[Paper.jar:git-Paper-1618]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_281]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_281]
        ... 6 more

**Comment by megargayu** [comment]
I just looked through the `WorldGuard 6.2.2` jar file, and it looks like it doesn't contain the `WorldGuard.class` file, meaning `BetterTeams` is trying to load something that doesn't exist. It looks like this is prevalent in `6.2.2` only and everything above that is fine (and everything below doesn't matter because it either has been superseded or is supporting 1.11 or below, which `BetterTeams` doesn't support). We might have to make a new integration file for this specific version, or just switch around the imports.

**Comment by megargayu** [comment]
WorldGuard 6.2.0 documentation can be seen here: https://worldguard.enginehub.org/en/6.2.0/ (there are no docs for 6.2.1/6.2.2)

**Comment by dogi-dogi** [comment]
so, 1.12.2 server 

I can't use the plugin anymore?
worldguard v 7.0.0  Plugin is not work in 1.12.2.. ㅠ ㅠ

anyather help??

**Comment by megargayu** [comment]
@dogi-dogi We might have to refactor the `WorldGuard` implementation just for WorldGuard 6.2.2 - currently I can't do it, so hopefully we can finish it by tomorrow (as long as it's just a small refactor and is not too big), and then for the next release to come out (hopefully soon). For now, you will just have to wait for us to fix the issue. Sorry!

**Comment by dogi-dogi** [comment]
@megargayu 
okay I'll wait for the next patch.
Thank you for help me.

**Comment by booksaw** [comment]
Though it is not perfect I have added a config option to disable the world guard integration (worldgaurd.enabled) so you can disable the integration so both plugins can run unaffected.
I do not have time to add support for older versions of world guard at the moment, but I am leaving this issue open to remind me to do so when I have time later down the line.

**Comment by booksaw** [comment]
Calling onLoad in /teama reload also causes problems if worldgaurd is working as expected
