### ISSUE TITLE
[BUG] One of my players is bugged, and i get console errors

### ISSUE THREAD

**Issue by TDMidkwhatisxd** [booksaw/BetterTeams#175]
[13:02:43 INFO]: LionHDPasler2132 tried to swim in lava
[13:02:44 ERROR]: Could not pass event InventoryCloseEvent to BetterTeams v4.0.0
java.lang.NullPointerException: Cannot invoke "String.length()" because "colorStr" is null
        at com.booksaw.betterTeams.Team.<init>(Team.java:287) ~[?:?]
        at com.booksaw.betterTeams.team.TeamManager.getTeam(TeamManager.java:72) ~[?:?]
[4:04 PM]
[13:04:34 ERROR]: Could not pass event AsyncPlayerChatEvent to BetterTeams v4.0.0
java.lang.NullPointerException: Cannot invoke "String.length()" because "colorStr" is null
        at com.booksaw.betterTeams.Team.<init>(Team.java:287) ~[?:?]
        at com.booksaw.betterTeams.team.TeamManager.getTeam(TeamManager.java:72) ~[?:?]

**Comment by booksaw** [comment]
This bug has been fixed and the patch will be included in the next update. Thank you for reporting.
