### ISSUE TITLE
[BUG] NullPointerException

### ISSUE THREAD

**Issue by Tijroon** [booksaw/BetterTeams#177]
I cant create teams or anything
Here is my error thingy,.
org.bukkit.command.CommandException: Unhandled exception executing 'TEAM DISBAND' in com.booksaw.betterTeams.BooksawCommand(team)
at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:169) ~[server.jar:git-Paper-779]
at org.bukkit.craftbukkit.v1_16_R3.CraftServer.dispatchCommand(CraftServer.java:826) ~[server.jar:git-Paper-779]
at net.minecraft.server.v1_16_R3.PlayerConnection.handleCommand(PlayerConnection.java:2185) ~[server.jar:git-Paper-779]
at net.minecraft.server.v1_16_R3.PlayerConnection.c(PlayerConnection.java:2000) ~[server.jar:git-Paper-779]
at net.minecraft.server.v1_16_R3.PlayerConnection.a(PlayerConnection.java:1953) ~[server.jar:git-Paper-779]
at net.minecraft.server.v1_16_R3.PacketPlayInChat.a(PacketPlayInChat.java:49) ~[server.jar:git-Paper-779]
at net.minecraft.server.v1_16_R3.PacketPlayInChat.a(PacketPlayInChat.java:7) ~[server.jar:git-Paper-779]
at net.minecraft.server.v1_16_R3.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:35) ~[server.jar:git-Paper-779]
at net.minecraft.server.v1_16_R3.TickTask.run(SourceFile:18) ~[server.jar:git-Paper-779]
at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[server.jar:git-Paper-779]
at net.minecraft.server.v1_16_R3.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[server.jar:git-Paper-779]
at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[server.jar:git-Paper-779]
at net.minecraft.server.v1_16_R3.MinecraftServer.bb(MinecraftServer.java:1266) ~[server.jar:git-Paper-779]
at net.minecraft.server.v1_16_R3.MinecraftServer.executeNext(MinecraftServer.java:1259) ~[server.jar:git-Paper-779]
at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[server.jar:git-Paper-779]
at net.minecraft.server.v1_16_R3.MinecraftServer.sleepForTick(MinecraftServer.java:1220) ~[server.jar:git-Paper-779]
at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1134) ~[server.jar:git-Paper-779]
at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:291) ~[server.jar:git-Paper-779]
at java.lang.Thread.run(Thread.java:834) [?:?]
Caused by: java.lang.NullPointerException
at com.booksaw.betterTeams.commands.presets.TeamSubCommand.checkRank(TeamSubCommand.java:77) ~[?:?]
at com.booksaw.betterTeams.commands.presets.TeamSubCommand.checkRank(TeamSubCommand.java:72) ~[?:?]
at com.booksaw.betterTeams.commands.presets.TeamSubCommand.onCommand(TeamSubCommand.java:33) ~[?:?]
at com.booksaw.betterTeams.commands.ParentCommand.onCommand(ParentCommand.java:135) ~[?:?]
at com.booksaw.betterTeams.BooksawCommand.execute(BooksawCommand.java:56) ~[?:?]
at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159) ~[server.jar:git-Paper-779]
... 18 more

**Comment by booksaw** [comment]
This bug has been fixed and the patch will be included in the next update. Thank you for reporting.
