### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by pentrait** [booksaw/BetterTeams#182]
**Describe the bug**
[01:41:44 WARN]: An avaliable team cannot be found, be prepared for a lot of errors. (this should never happen, and should always be reported to booksaw)
[01:41:44 WARN]: This catch is merely here to stop the server crashing
[01:41:44 ERROR]: Could not pass event PlayerJoinEvent to BetterTeams v4.0.1
java.lang.NullPointerException: Cannot invoke "org.bukkit.scoreboard.Team.addEntry(String)" because the return value of "com.booksaw.betterTeams.Team.getScoreboardTeam(org.bukkit.scoreboard.Scoreboard)" is null
	at com.booksaw.betterTeams.events.MCTeamManagement.displayBelowName(MCTeamManagement.java:62) ~[?:?]
	at com.booksaw.betterTeams.events.MCTeamManagement.playerJoinEvent(MCTeamManagement.java:109) ~[?:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor5.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[minecraft_server.jar:git-Paper-91]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[minecraft_server.jar:git-Paper-91]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[minecraft_server.jar:git-Paper-91]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:624) ~[minecraft_server.jar:git-Paper-91]
	at net.minecraft.server.players.PlayerList.postChunkLoadJoin(PlayerList.java:359) ~[minecraft_server.jar:git-Paper-91]
	at net.minecraft.server.players.PlayerList.lambda$placeNewPlayer$1(PlayerList.java:301) ~[minecraft_server.jar:git-Paper-91]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.tick(ServerGamePacketListenerImpl.java:307) ~[?:?]
	at net.minecraft.network.Connection.tick(Connection.java:399) ~[?:?]
	at net.minecraft.server.network.ServerConnectionListener.tick(ServerConnectionListener.java:196) ~[?:?]
	at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1578) ~[minecraft_server.jar:git-Paper-91]
	at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:479) ~[minecraft_server.jar:git-Paper-91]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1406) ~[minecraft_server.jar:git-Paper-91]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1188) ~[minecraft_server.jar:git-Paper-91]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316) ~[minecraft_server.jar:git-Paper-91]
	at java.lang.Thread.run(Thread.java:831) [?:?]

**To Reproduce**
Steps to reproduce the behaviour:
1. Creating a team
2. Disbanding the team
3. Logging out, logging in

**Expected behaviour**
No errors

**Details**
Please provide the following details about your server set-up:
- 1.17.1 Paper
- BetterTeams version 4.0.1

**Comment by booksaw** [comment]
could you screenshot the result of the command /minecraft:team list

**Comment by booksaw** [comment]
This bug has been fixed and the patch will be included in the next update. Thank you for reporting.
