### ISSUE TITLE
[BUG] Betterteam 4.0.1 unable to be enabled

### ISSUE THREAD

**Issue by jahua50** [booksaw/BetterTeams#184]
The plugin suddenly wasn't able to be enabled after today's automatic restart. The console error is in the following,
<html>
<body>

[14:42:21] [Server thread/INFO]: [BetterTeams] Enabling BetterTeams v4.0.1
--
[14:42:21] [Server thread/INFO]: [BetterTeams] Checking if the file messages.yml is up to date
[14:42:21] [Server thread/INFO]: [BetterTeams] File is up to date
[14:42:21] [Server thread/ERROR]: Error occurred while enabling BetterTeams v4.0.1 (Is it up to date?)
java.lang.ArrayIndexOutOfBoundsException: Index 1 out of bounds for length 1
at com.booksaw.betterTeams.team.storage.storageManager.SeparatedYamlStorageManager.<init>(SeparatedYamlStorageManager.java:60) ~[?:?]
at com.booksaw.betterTeams.team.storage.StorageType.getNewTeamManager(StorageType.java:29) ~[?:?]
at com.booksaw.betterTeams.Team.setupTeamManager(Team.java:58) ~[?:?]
at com.booksaw.betterTeams.Main.setupStorage(Main.java:432) ~[?:?]
at com.booksaw.betterTeams.Main.onEnable(Main.java:168) ~[?:?]
at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.16.5.jar:git-Paper-778]
at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[patched_1.16.5.jar:git-Paper-778]
at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500) ~[patched_1.16.5.jar:git-Paper-778]
at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugin(CraftServer.java:518) ~[patched_1.16.5.jar:git-Paper-778]
at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugins(CraftServer.java:432) ~[patched_1.16.5.jar:git-Paper-778]
at net.minecraft.server.v1_16_R3.MinecraftServer.loadWorld(MinecraftServer.java:594) ~[patched_1.16.5.jar:git-Paper-778]
at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:298) ~[patched_1.16.5.jar:git-Paper-778]
at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1069) ~[patched_1.16.5.jar:git-Paper-778]
at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:291) ~[patched_1.16.5.jar:git-Paper-778]
at java.lang.Thread.run(Thread.java:831) [?:?]
[14:42:21] [Server thread/INFO]: [BetterTeams] Disabling BetterTeams v4.0.1

</body>
</html>

**Comment by jahua50** [comment]
Im using paper 1.16.5 btw

**Comment by booksaw** [comment]
This bug has been fixed and the patch will be included in the next update. Thank you for reporting.
