### ISSUE TITLE
[BUG] The team manager has already been setup

### ISSUE THREAD

**Issue by Elbry20** [booksaw/BetterTeams#189]
**Describe the bug**
Can't load the plugin within minecraft when I try to run the command /teama reload

**ERROR**

[15:30:33] [Server thread/WARN]: Unexpected exception while parsing console command "teama reload"
org.bukkit.command.CommandException: Unhandled exception executing 'teama reload' in com.booksaw.betterTeams.BooksawCommand(teamadmin)
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:150) ~[SimpleCommandMap.class:git-CatServer-1.12.2-83bb041]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:710) ~[CraftServer.class:git-CatServer-1.12.2-83bb041]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchServerCommand(CraftServer.java:695) [CraftServer.class:git-CatServer-1.12.2-83bb041]
        at net.minecraft.server.dedicated.DedicatedServer.func_71333_ah(DedicatedServer.java:517) [nz.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:475) [nz.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:770) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:630) [MinecraftServer.class:?]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_291]
Caused by: java.lang.IllegalArgumentException: The team manager has already been setup
        at com.booksaw.betterTeams.Team.setupTeamManager(Team.java:55) ~[?:?]
        at com.booksaw.betterTeams.Main.setupStorage(Main.java:432) ~[?:?]
        at com.booksaw.betterTeams.Main.onEnable(Main.java:168) ~[?:?]
        at com.booksaw.betterTeams.Main.reload(Main.java:287) ~[?:?]
        at com.booksaw.betterTeams.commands.teama.ReloadTeama.onCommand(ReloadTeama.java:17) ~[?:?]
        at com.booksaw.betterTeams.commands.ParentCommand.onCommand(ParentCommand.java:135) ~[?:?]
        at com.booksaw.betterTeams.BooksawCommand.execute(BooksawCommand.java:56) ~[?:?]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:146) ~[SimpleCommandMap.class:git-CatServer-1.12.2-83bb041]
        ... 7 more

I hope I have a solution because the plugin is very good and I would like to use it on my server, I mean my server is a server (catserver) with mods and plugins 1.12.2.

**Comment by booksaw** [comment]
This bug has been fixed and the patch will be included in the next update. Thank you for reporting.
