### ISSUE TITLE
[16:18:18 ERROR]: Could not pass event PlayerJoinEvent to BetterTeams v4.0.1

### ISSUE THREAD

**Issue by Tijroon** [booksaw/BetterTeams#190]
[16:18:18 ERROR]: Could not pass event PlayerJoinEvent to BetterTeams v4.0.1
java.lang.NullPointerException: Cannot invoke "org.bukkit.scoreboard.Team.addEntry(String)" because the return value of "com.booksaw.betterTeams.Team.getScoreboardTeam(org.bukkit.scoreboard.Scoreboard)" is null
at com.booksaw.betterTeams.events.MCTeamManagement.displayBelowName(MCTeamManagement.java:62) ~[?:?]
at com.booksaw.betterTeams.events.MCTeamManagement.playerJoinEvent(MCTeamManagement.java:109) ~[?:?]
at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor348.execute(Unknown Source) ~[?:?]
at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[server.jar:git-Paper-779]
at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[server.jar:git-Paper-779]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[server.jar:git-Paper-779]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:624) ~[server.jar:git-Paper-779]
at net.minecraft.server.v1_16_R3.PlayerList.postChunkLoadJoin(PlayerList.java:356) ~[server.jar:git-Paper-779]
at net.minecraft.server.v1_16_R3.PlayerList.lambda$a$1(PlayerList.java:303) ~[server.jar:git-Paper-779]
at net.minecraft.server.v1_16_R3.PlayerConnection.tick(PlayerConnection.java:316) ~[server.jar:git-Paper-779]
at net.minecraft.server.v1_16_R3.NetworkManager.a(NetworkManager.java:408) ~[server.jar:git-Paper-779]
at net.minecraft.server.v1_16_R3.ServerConnection.c(ServerConnection.java:168) ~[server.jar:git-Paper-779]
at net.minecraft.server.v1_16_R3.MinecraftServer.b(MinecraftServer.java:1515) ~[server.jar:git-Paper-779]
at net.minecraft.server.v1_16_R3.DedicatedServer.b(DedicatedServer.java:436) ~[server.jar:git-Paper-779]
at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1342) ~[server.jar:git-Paper-779]
at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1130) ~[server.jar:git-Paper-779]
at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:291) ~[server.jar:git-Paper-779]
at java.lang.Thread.run(Thread.java:831) [?:?]
[16:18:18 INFO]: tim_hoogervorst joined the game
[16:18:19 INFO]: tim_hoogervorst[/217.104.54.240:41287] logged in with entity id 254 at ([spawn]-235.47549392715905, 98.24947197770308, 208.4298077848761)
[16:18:19 WARN]: [Essentials] Permissions lag notice with (LuckPermsHandler). Response took 67.854714ms. Summary: Getting group for MoneyMan3009
[16:18:19 INFO]: Frankrijk xLilStinky joined the game
[16:18:19 INFO]: xLilStinky[/86.86.83.220:33805] logged in with entity id 253 at ([Albion]-936.6999999880791, 53.0, 539.5146852438636)
[16:18:19 INFO]: UUID of player Joey_YT is bb7a8b30-8c4f-4870-a2df-3cadd170a808
[16:18:20 WARN]: Can't keep up! Is the server overloaded? Running 5165ms or 103 ticks behind
[16:18:20 INFO]: [UltimateClaims] Data handler connected using SQLite.
[16:18:20 ERROR]: [UltimateClaims] An error occurred executing an SQLite query: Cannot invoke "com.songoda.ultimateclaims.member.ClaimMember.getUniqueId()" because the return value of "com.songoda.ultimateclaims.claim.Claim.getOwner()" is null
[16:18:20 WARN]: java.lang.NullPointerException: Cannot invoke "com.songoda.ultimateclaims.member.ClaimMember.getUniqueId()" because the return value of "com.songoda.ultimateclaims.claim.Claim.getOwner()" is null
[16:18:20 WARN]: at com.songoda.ultimateclaims.database.DataManager.lambda$null$40(DataManager.java:730)
[16:18:20 WARN]: at com.songoda.ultimateclaims.core.database.SQLiteConnector.connect(SQLiteConnector.java:54)
[16:18:20 WARN]: at com.songoda.ultimateclaims.database.DataManager.lambda$getClaims$41(DataManager.java:534)
[16:18:20 WARN]: at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:100)
[16:18:20 WARN]: at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54)
[16:18:20 WARN]: at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[16:18:20 WARN]: at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
[16:18:20 WARN]: at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
[16:18:20 WARN]: at java.base/java.lang.Thread.run(Thread.java:831)
[16:18:21 INFO]: UUID of player xLilPeer is 2357f730-0824-408c-bcec-e88c52984dcc
[16:18:22 INFO]: xLilPeer joined the game
[16:18:22 INFO]: xLilPeer[/217.123.232.168:56591] logged in with entity id 282 at ([spawn]-250.30000001192093, 98.0, 208.17016831796406)
[16:18:25 INFO]: xLilPain issued server command: /team create noorwegen
[16:18:28 INFO]: UUID of player spicy_ghostclap is dfcec5c2-d0f9-4ad3-a217-86acf113c4f6
[16:18:28 INFO]: spicy_ghostclap joined the game
[16:18:28 INFO]: spicy_ghostclap[/147.12.11.201:55083] logged in with entity id 389 at ([spawn]-235.60951795704915, 105.5, 199.09903810945465)
[16:18:29 INFO]: [Noorwegen] [Eigenaar] xLilPeer >> t
[16:18:30 INFO]: Rusland h0erezoon joined the game
[16:18:30 INFO]: h0erezoon[/77.162.135.239:47909] logged in with entity id 252 at ([Albion]-294.2444349536454, 60.56904711312371, -502.849629683923)
[16:18:30 INFO]: xLilPeer issued server command: /team
[16:18:31 INFO]: Frankrijk Joey_YT joined the game
[16:18:31 INFO]: Joey_YT[/178.51.247.74:54367] logged in with entity id 281 at ([Albion]-326.85584286175026, 46.04320004463196, 708.6999999880791)
[16:18:33 INFO]: xLilPeer issued server command: /team disband
[16:18:35 INFO]: xLilPeer issued server command: /team disband
[16:18:35 INFO]: [Rusland] [Speler] h0erezoon >> mn iron is loesoe
[16:18:38 INFO]: xLilPain issued server command: /team create België
[16:18:41 INFO]: xLilPeer issued server command: /team create Noorwegen
[16:18:42 INFO]: xLilPeer issued server command: /gmc
[16:18:43 INFO]: xLilPain issued server command: /team leave
[16:18:43 ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing 'team leave' in com.booksaw.betterTeams.BooksawCommand(team)
at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:169) ~[server.jar:git-Paper-779]
at org.bukkit.craftbukkit.v1_16_R3.CraftServer.dispatchCommand(CraftServer.java:826) ~[server.jar:git-Paper-779]
at net.minecraft.server.v1_16_R3.PlayerConnection.handleCommand(PlayerConnection.java:2185) ~[server.jar:git-Paper-779]
at net.minecraft.server.v1_16_R3.PlayerConnection.c(PlayerConnection.java:2000) ~[server.jar:git-Paper-779]
at net.minecraft.server.v1_16_R3.PlayerConnection.a(PlayerConnection.java:1953) ~[server.jar:git-Paper-779]
at net.minecraft.server.v1_16_R3.PacketPlayInChat.a(PacketPlayInChat.java:49) ~[server.jar:git-Paper-779]
at net.minecraft.server.v1_16_R3.PacketPlayInChat.a(PacketPlayInChat.java:7) ~[server.jar:git-Paper-779]
at net.minecraft.server.v1_16_R3.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:35) ~[server.jar:git-Paper-779]
at net.minecraft.server.v1_16_R3.TickTask.run(SourceFile:18) ~[server.jar:git-Paper-779]
at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[server.jar:git-Paper-779]
at net.minecraft.server.v1_16_R3.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[server.jar:git-Paper-779]
at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[server.jar:git-Paper-779]
at net.minecraft.server.v1_16_R3.MinecraftServer.bb(MinecraftServer.java:1266) ~[server.jar:git-Paper-779]
at net.minecraft.server.v1_16_R3.MinecraftServer.executeNext(MinecraftServer.java:1259) ~[server.jar:git-Paper-779]
at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[server.jar:git-Paper-779]
at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1333) ~[server.jar:git-Paper-779]
at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1130) ~[server.jar:git-Paper-779]
at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:291) ~[server.jar:git-Paper-779]
at java.lang.Thread.run(Thread.java:831) [?:?]
Caused by: java.lang.NullPointerException: Cannot invoke "com.booksaw.betterTeams.TeamPlayer.getRank()" because "player" is null
at com.booksaw.betterTeams.commands.presets.TeamSubCommand.checkRank(TeamSubCommand.java:77) ~[?:?]
at com.booksaw.betterTeams.commands.presets.TeamSubCommand.checkRank(TeamSubCommand.java:72) ~[?:?]
at com.booksaw.betterTeams.commands.presets.TeamSubCommand.onCommand(TeamSubCommand.java:33) ~[?:?]
at com.booksaw.betterTeams.commands.ParentCommand.onCommand(ParentCommand.java:135) ~[?:?]
at com.booksaw.betterTeams.BooksawCommand.execute(BooksawCommand.java:56) ~[?:?]
at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159) ~[server.jar:git-Paper-779]
... 18 more

**Comment by booksaw** [comment]
This bug has been fixed and the patch will be included in the next update. Thank you for reporting.
