### ISSUE TITLE
[BUG] /team top  dont work

### ISSUE THREAD

**Issue by TDMidkwhatisxd** [booksaw/BetterTeams#195]
NoobKing994 issued server command: /teama holo create score
[10:35:03 ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing 'teama holo create score' in com.booksaw.betterTeams.BooksawCommand(teamadmin)
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:169) ~[patched_1.17.1.jar:git-Paper-112]
        at org.bukkit.craftbukkit.v1_17_R1.CraftServer.dispatchCommand(CraftServer.java:821) ~[patched_1.17.1.jar:git-Paper-112]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleCommand(ServerGamePacketListenerImpl.java:2170) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleChat(ServerGamePacketListenerImpl.java:1981) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleChat(ServerGamePacketListenerImpl.java:1962) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundChatPacket.handle(ServerboundChatPacket.java:46) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundChatPacket.handle(ServerboundChatPacket.java:6) ~[?:?]
[1:39 PM]
its weird, when i do /team top  only 1 team is showing

**Comment by booksaw** [comment]
This bug should be fixed and the patch will be included in the next update, if it does not please make a new bug report referencing this one. Thank you for reporting.
