### ISSUE TITLE
[BUG] Unhandled Exception

### ISSUE THREAD

**Issue by ToggleMountain** [booksaw/BetterTeams#20]
**Describe the bug**
When issuing command /team rank <team_name> unhandled exception occurs:
```
[11:39:00 ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'team' in plugin BetterTeams v3.1.1
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[patched_1.16.1.jar:git-Paper-101]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159) ~[patched_1.16.1.jar:git-Paper-101]
        at org.bukkit.craftbukkit.v1_16_R1.CraftServer.dispatchCommand(CraftServer.java:794) ~[patched_1.16.1.jar:git-Paper-101]
        at net.minecraft.server.v1_16_R1.PlayerConnection.handleCommand(PlayerConnection.java:1912) ~[patched_1.16.1.jar:git-Paper-101]
        at net.minecraft.server.v1_16_R1.PlayerConnection.a(PlayerConnection.java:1723) ~[patched_1.16.1.jar:git-Paper-101]
        at net.minecraft.server.v1_16_R1.PacketPlayInChat.a(PacketPlayInChat.java:47) ~[patched_1.16.1.jar:git-Paper-101]
        at net.minecraft.server.v1_16_R1.PacketPlayInChat.a(PacketPlayInChat.java:5) ~[patched_1.16.1.jar:git-Paper-101]
        at net.minecraft.server.v1_16_R1.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:23) ~[patched_1.16.1.jar:git-Paper-101]
        at net.minecraft.server.v1_16_R1.TickTask.run(SourceFile:18) ~[patched_1.16.1.jar:git-Paper-101]
        at net.minecraft.server.v1_16_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.16.1.jar:git-Paper-101]
        at net.minecraft.server.v1_16_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.16.1.jar:git-Paper-101]
        at net.minecraft.server.v1_16_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.16.1.jar:git-Paper-101]
        at net.minecraft.server.v1_16_R1.MinecraftServer.aZ(MinecraftServer.java:1136) ~[patched_1.16.1.jar:git-Paper-101]
        at net.minecraft.server.v1_16_R1.MinecraftServer.executeNext(MinecraftServer.java:1129) ~[patched_1.16.1.jar:git-Paper-101]
        at net.minecraft.server.v1_16_R1.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.16.1.jar:git-Paper-101]
        at net.minecraft.server.v1_16_R1.MinecraftServer.sleepForTick(MinecraftServer.java:1090) ~[patched_1.16.1.jar:git-Paper-101]
        at net.minecraft.server.v1_16_R1.MinecraftServer.v(MinecraftServer.java:1004) ~[patched_1.16.1.jar:git-Paper-101]
        at net.minecraft.server.v1_16_R1.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[patched_1.16.1.jar:git-Paper-101]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_242]
Caused by: java.util.MissingFormatArgumentException: Format specifier '%s'
        at java.util.Formatter.format(Formatter.java:2519) ~[?:1.8.0_242]
        at java.util.Formatter.format(Formatter.java:2455) ~[?:1.8.0_242]
        at java.lang.String.format(String.java:2940) ~[?:1.8.0_242]
        at com.booksaw.betterTeams.message.MessageManager.sendMessageF(MessageManager.java:105) ~[?:?]
        at com.booksaw.betterTeams.message.ReferencedFormatMessage.sendMessage(ReferencedFormatMessage.java:28) ~[?:?]
        at com.booksaw.betterTeams.message.CompositeMessage.sendMessage(CompositeMessage.java:23) ~[?:?]
        at com.booksaw.betterTeams.CommandResponse.sendResponseMessage(CommandResponse.java:89) ~[?:?]
        at com.booksaw.betterTeams.BooksawCommand.onCommand(BooksawCommand.java:36) ~[?:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[patched_1.16.1.jar:git-Paper-101]
        ... 18 more
```

**To Reproduce**
Steps to reproduce the behaviour:
1. Run command /team rank <team_name>

**Expected behaviour**
I expected to see team's rank

**Details**
I'm using PaperSpigot version Paper-101, Minecraft version 1.16.1, BetterTeams version 3.1.1

**Comment by booksaw** [comment]
The error has been fixed for the next version
