### ISSUE TITLE
TEAM HOLO CREATE ERROR

### ISSUE THREAD

**Issue by giantfurkii** [booksaw/BetterTeams#228]
https://mclo.gs/ohiIOzm

**Comment by booksaw** [comment]
Pasting here so it does not expire: 


[09:24:24] [Server thread/INFO]: GiantFurkii issued server command: /teama holo create score
--
2 | [09:24:24] [Server thread/ERROR]: null
3 | org.bukkit.command.CommandException: Unhandled exception executing 'teama holo create score' in com.booksaw.betterTeams.BooksawCommand(teamadmin)
4 | at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:169) ~[patched_1.17.1.jar:git-Airplane-76]
5 | at org.bukkit.craftbukkit.v1_17_R1.CraftServer.dispatchCommand(CraftServer.java:838) ~[patched_1.17.1.jar:git-Airplane-76]
6 | at net.minecraft.server.network.PlayerConnection.handleCommand(PlayerConnection.java:2248) ~[patched_1.17.1.jar:git-Airplane-76]
7 | at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:2059) ~[patched_1.17.1.jar:git-Airplane-76]
8 | at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:2040) ~[patched_1.17.1.jar:git-Airplane-76]
9 | at net.minecraft.network.protocol.game.PacketPlayInChat.a(PacketPlayInChat.java:46) ~[patched_1.17.1.jar:git-Airplane-76]
10 | at net.minecraft.network.protocol.game.PacketPlayInChat.a(PacketPlayInChat.java:6) ~[patched_1.17.1.jar:git-Airplane-76]
11 | at net.minecraft.network.protocol.PlayerConnectionUtils.lambda$ensureRunningOnSameThread$1(PlayerConnectionUtils.java:56) ~[patched_1.17.1.jar:git-Airplane-76]
12 | at net.minecraft.server.TickTask.run(TickTask.java:18) ~[patched_1.17.1.jar:git-Airplane-76]
13 | at net.minecraft.util.thread.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:149) ~[patched_1.17.1.jar:git-Airplane-76]
14 | at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.executeTask(IAsyncTaskHandlerReentrant.java:23) ~[patched_1.17.1.jar:git-Airplane-76]
15 | at net.minecraft.server.MinecraftServer.executeTask(MinecraftServer.java:1418) ~[patched_1.17.1.jar:git-Airplane-76]
16 | at net.minecraft.server.MinecraftServer.executeTask(MinecraftServer.java:192) ~[patched_1.17.1.jar:git-Airplane-76]
17 | at net.minecraft.util.thread.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:122) ~[patched_1.17.1.jar:git-Airplane-76]
18 | at net.minecraft.server.MinecraftServer.bf(MinecraftServer.java:1396) ~[patched_1.17.1.jar:git-Airplane-76]
19 | at net.minecraft.server.MinecraftServer.executeNext(MinecraftServer.java:1389) ~[patched_1.17.1.jar:git-Airplane-76]
20 | at net.minecraft.util.thread.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:132) ~[patched_1.17.1.jar:git-Airplane-76]
21 | at net.minecraft.server.MinecraftServer.sleepForTick(MinecraftServer.java:1367) ~[patched_1.17.1.jar:git-Airplane-76]
22 | at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1278) ~[patched_1.17.1.jar:git-Airplane-76]
23 | at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[patched_1.17.1.jar:git-Airplane-76]
24 | at java.lang.Thread.run(Thread.java:831) [?:?]
25 | Caused by: java.util.MissingFormatArgumentException: Format specifier '%s'
26 | at java.util.Formatter.format(Formatter.java:2688) ~[?:?]
27 | at java.util.Formatter.format(Formatter.java:2625) ~[?:?]
28 | at java.lang.String.format(String.java:3290) ~[?:?]
29 | at com.booksaw.betterTeams.integrations.HologramManager.reloadHolo(HologramManager.java:70) ~[BetterTeams.jar:?]
30 | at com.booksaw.betterTeams.integrations.HologramManager.createHolo(HologramManager.java:57) ~[BetterTeams.jar:?]
31 | at com.booksaw.betterTeams.commands.teama.CreateHoloTeama.onCommand(CreateHoloTeama.java:18) ~[BetterTeams.jar:?]
32 | at com.booksaw.betterTeams.commands.ParentCommand.onCommand(ParentCommand.java:135) ~[BetterTeams.jar:?]
33 | at com.booksaw.betterTeams.commands.ParentCommand.onCommand(ParentCommand.java:82) ~[BetterTeams.jar:?]
34 | at com.booksaw.betterTeams.commands.ParentCommand.onCommand(ParentCommand.java:135) ~[BetterTeams.jar:?]
35 | at com.booksaw.betterTeams.BooksawCommand.execute(BooksawCommand.java:56) ~[BetterTeams.jar:?]
36 | at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159) ~[patched_1.17.1.jar:git-Airplane-76]
37 | ... 20 more

**Comment by giantfurkii** [comment]
holo:
  leaderboard: '&8&l&m----|&r &a&lEN İYİLER &8&l&m|----'
  syntax: '&e%s &8▸ &c%s &8(&4%s &7Katletme!&8)'
  msyntax: '&e%s &8▸ &c%s &8(&4%s &7Katletme!&8)'

**Comment by booksaw** [comment]
As discussed in the discord server your formatting is wrong.
Let me know if you are still having difficulties
