### ISSUE TITLE
[BUG] /team promote doesnt work

### ISSUE THREAD

**Issue by heybangsie** [booksaw/BetterTeams#230]
[07:54:42 INFO]: Apricot248 issued server command: /team promote ItzOmz
[07:54:42 ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing 'team promote ItzOmz' in com.booksaw.betterTeams.BooksawCommand(team)
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:182) ~[patched_1.17.1.jar:git-Purpur-1384]
        at org.bukkit.craftbukkit.v1_17_R1.CraftServer.dispatchCommand(CraftServer.java:838) ~[patched_1.17.1.jar:git-Purpur-1384]
        at net.minecraft.server.network.PlayerConnection.handleCommand(PlayerConnection.java:2316) ~[patched_1.17.1.jar:git-Purpur-1384]
        at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:2127) ~[patched_1.17.1.jar:git-Purpur-1384]
        at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:2108) ~[patched_1.17.1.jar:git-Purpur-1384]
        at net.minecraft.network.protocol.game.PacketPlayInChat.a(PacketPlayInChat.java:46) ~[patched_1.17.1.jar:git-Purpur-1384]
        at net.minecraft.network.protocol.game.PacketPlayInChat.a(PacketPlayInChat.java:6) ~[patched_1.17.1.jar:git-Purpur-1384]
        at net.minecraft.network.protocol.PlayerConnectionUtils.lambda$ensureRunningOnSameThread$1(PlayerConnectionUtils.java:56) ~[patched_1.17.1.jar:git-Purpur-1384]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[patched_1.17.1.jar:git-Purpur-1384]
        at net.minecraft.util.thread.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:149) ~[patched_1.17.1.jar:git-Purpur-1384]
        at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.executeTask(IAsyncTaskHandlerReentrant.java:23) ~[patched_1.17.1.jar:git-Purpur-1384]
        at net.minecraft.server.MinecraftServer.executeTask(MinecraftServer.java:1433) ~[patched_1.17.1.jar:git-Purpur-1384]
        at net.minecraft.server.MinecraftServer.executeTask(MinecraftServer.java:192) ~[patched_1.17.1.jar:git-Purpur-1384]
        at net.minecraft.util.thread.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:122) ~[patched_1.17.1.jar:git-Purpur-1384]
        at net.minecraft.server.MinecraftServer.bf(MinecraftServer.java:1411) ~[patched_1.17.1.jar:git-Purpur-1384]
        at net.minecraft.server.MinecraftServer.executeNext(MinecraftServer.java:1404) ~[patched_1.17.1.jar:git-Purpur-1384]
        at net.minecraft.util.thread.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:132) ~[patched_1.17.1.jar:git-Purpur-1384]
        at net.minecraft.server.MinecraftServer.sleepForTick(MinecraftServer.java:1382) ~[patched_1.17.1.jar:git-Purpur-1384]
        at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1293) ~[patched_1.17.1.jar:git-Purpur-1384]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:321) ~[patched_1.17.1.jar:git-Purpur-1384]
        at java.lang.Thread.run(Thread.java:831) [?:?]
Caused by: java.lang.NullPointerException: Cannot invoke "String.equals(Object)" because the return value of "org.bukkit.OfflinePlayer.getName()" is null
        at com.booksaw.betterTeams.Utils.getOfflinePlayer(Utils.java:22) ~[BetterTeams.jar:?]
        at com.booksaw.betterTeams.commands.team.PromoteCommand.onCommand(PromoteCommand.java:34) ~[BetterTeams.jar:?]
        at com.booksaw.betterTeams.commands.presets.TeamSubCommand.onCommand(TeamSubCommand.java:39) ~[BetterTeams.jar:?]
        at com.booksaw.betterTeams.commands.ParentCommand.onCommand(ParentCommand.java:135) ~[BetterTeams.jar:?]
        at com.booksaw.betterTeams.BooksawCommand.execute(BooksawCommand.java:56) ~[BetterTeams.jar:?]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:172) ~[patched_1.17.1.jar:git-Purpur-1384]
        ... 20 more

**Comment by booksaw** [comment]
This bug has been fixed and the patch will be included in the next update. Thank you for reporting.
