### ISSUE TITLE
[BUG] autoPurge does not work

### ISSUE THREAD

**Issue by HunkyMunky** [booksaw/BetterTeams#285]
**Describe the bug**
autoPurge does not appear in the default config, even though it's on github. Adding it to the default config gives you console errors on start up and doesn't allow the plugin to reload. 

**To Reproduce**
Add the following to config:
```
autoPurge:
- 1:6
```
After the server loads, it becomes:
```
autoPurge
- 66
```

**Details**
Please provide the following details about your server set-up:
- Spigot version (found by running /version): Mohist 1.12.2
- BetterTeams version (found by running /version BetterTeams): 4.2.1

**Additional context**
Reload error
```
org.bukkit.command.CommandException: Unhandled exception executing 'teama reload' in com.booksaw.betterTeams.BooksawCommand(teamadmin)
    at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:158) ~[SimpleCommandMap.class:?]
    at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:752) ~[CraftServer.class:?]
    at net.minecraft.network.NetHandlerPlayServer.func_147361_d(NetHandlerPlayServer.java:1589) ~[pa.class:?]
    at net.minecraft.network.NetHandlerPlayServer.func_147354_a(NetHandlerPlayServer.java:1428) ~[pa.class:?]
    at net.minecraft.network.play.client.CPacketChatMessage.func_148833_a(CPacketChatMessage.java:46) ~[la.class:?]
    at net.minecraft.network.play.client.CPacketChatMessage.func_148833_a(CPacketChatMessage.java:9) ~[la.class:?]
    at net.minecraft.network.PacketThreadUtil.lambda$checkThreadAndEnqueue$0(PacketThreadUtil.java:16) ~[hv.class:?]
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_251]
    at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_251]
    at net.minecraft.util.Util.func_181617_a(SourceFile:46) [h.class:?]
    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:840) [MinecraftServer.class:?]
    at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:461) [nz.class:?]
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:778) [MinecraftServer.class:?]
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:624) [MinecraftServer.class:?]
    at java.lang.Thread.run(Thread.java:748) [?:1.8.0_251]
Caused by: java.lang.ArrayIndexOutOfBoundsException: 1
    at com.booksaw.betterTeams.score.ScoreManagement.lambda$0(ScoreManagement.java:31) ~[?:?]
    at java.util.ArrayList.forEach(ArrayList.java:1257) ~[?:1.8.0_251]
    at com.booksaw.betterTeams.score.ScoreManagement.<init>(ScoreManagement.java:29) ~[?:?]
    at com.booksaw.betterTeams.Main.setupListeners(Main.java:408) ~[?:?]
    at com.booksaw.betterTeams.Main.onEnable(Main.java:209) ~[?:?]
    at com.booksaw.betterTeams.Main.reload(Main.java:315) ~[?:?]
    at com.booksaw.betterTeams.commands.teama.ReloadTeama.onCommand(ReloadTeama.java:17) ~[?:?]
    at com.booksaw.betterTeams.commands.ParentCommand.onCommand(ParentCommand.java:135) ~[?:?]
    at com.booksaw.betterTeams.BooksawCommand.execute(BooksawCommand.java:56) ~[?:?]
    at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:154) ~[SimpleCommandMap.class:?]
    ... 14 more
```

**Comment by booksaw** [comment]
This bug has been fixed and the patch will be included in the next update. Thank you for reporting.

This is a documentation issue, replace 
`- 1:6`
with 
`- '1:6'` (include single quotes)
