### ISSUE TITLE
[BUG] Using tags in team chat gives console error

### ISSUE THREAD

**Issue by HunkyMunky** [booksaw/BetterTeams#287]
**Describe the bug**
I tried using the plugins CMI and TagSomeone with their tagging system, and it gave me this error in console. I did not get this error when using another plugin with a chat feature.

Should note that this error only happens when I do `/team chat` with a message. If I enter into team chat mode then type my message with a tag, there is no issue.

**To Reproduce**
Steps to reproduce the behaviour:
1. Run command `/team chat <my message>`

**Expected behaviour**
BetterTeams should just ignore the tag and treat it like normal text.

**Details**
Please provide the following details about your server set-up:
- Spigot version (found by running /version): Mohist 1.12.2
- BetterTeams version (found by running /version BetterTeams): 4.2.1

**Additional context**
Console error
```
 org.bukkit.command.CommandException: Unhandled exception executing 'team chat @FrostDream' in com.booksaw.betterTeams.BooksawCommand(team)
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:158) ~[SimpleCommandMap.class:?]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:752) ~[CraftServer.class:?]
	at org.bukkit.Bukkit.dispatchCommand(Bukkit.java:593) ~[Bukkit.class:?]
	at org.bukkit.command.FormattedCommandAlias.execute(FormattedCommandAlias.java:41) ~[FormattedCommandAlias.class:?]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:154) ~[SimpleCommandMap.class:?]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:752) ~[CraftServer.class:?]
	at net.minecraft.network.NetHandlerPlayServer.func_147361_d(NetHandlerPlayServer.java:1589) ~[pa.class:?]
	at net.minecraft.network.NetHandlerPlayServer.func_147354_a(NetHandlerPlayServer.java:1428) ~[pa.class:?]
	at net.minecraft.network.play.client.CPacketChatMessage.func_148833_a(CPacketChatMessage.java:46) ~[la.class:?]
	at net.minecraft.network.play.client.CPacketChatMessage.func_148833_a(CPacketChatMessage.java:9) ~[la.class:?]
	at net.minecraft.network.PacketThreadUtil.lambda$checkThreadAndEnqueue$0(PacketThreadUtil.java:16) ~[hv.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_251]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_251]
	at net.minecraft.util.Util.func_181617_a(SourceFile:46) [h.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:840) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:461) [nz.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:778) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:624) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_251]
Caused by: java.lang.NoSuchMethodError: org.bukkit.Bukkit.selectEntities(Lorg/bukkit/command/CommandSender;Ljava/lang/String;)Ljava/util/List;
	at com.booksaw.betterTeams.BooksawCommand.checkPointers(BooksawCommand.java:88) ~[?:?]
	at com.booksaw.betterTeams.BooksawCommand.execute(BooksawCommand.java:49) ~[?:?]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:154) ~[SimpleCommandMap.class:?]
	... 18 more
```

**Comment by booksaw** [comment]
This bug has been fixed and the patch will be included in the next update. Thank you for reporting.
