### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by ChrisCreeper** [booksaw/BetterTeams#293]
```
An avaliable team cannot be found, be prepared for a lot of errors. (this should never happen, and should always be reported to booksaw)
[20.12 18:42:16] [Server] [Server thread/WARN]: This catch is merely here to stop the server crashing
[20.12 18:42:16] [Server] [Server thread/ERROR]: null
[20.12 18:42:16] [Server] org.bukkit.command.CommandExceptionUnhandled exception executing 'teama reload' in com.booksaw.betterTeams.BooksawCommand(teamadmin)
[20.12 18:42:16] [Server] 	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:156) ~[spigot-1.17.1.jar:3284a-Spigot-3892929-0ab8487]
[20.12 18:42:16] [Server] 	at org.bukkit.craftbukkit.v1_17_R1.CraftServer.dispatchCommand(CraftServer.java:790) ~[spigot-1.17.1.jar:3284a-Spigot-3892929-0ab8487]
[20.12 18:42:16] [Server] 	at net.minecraft.server.network.PlayerConnection.handleCommand(PlayerConnection.java:1931) ~[spigot-1.17.1.jar:3284a-Spigot-3892929-0ab8487]
[20.12 18:42:16] [Server] 	at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:1770) ~[spigot-1.17.1.jar:3284a-Spigot-3892929-0ab8487]
[20.12 18:42:16] [Server] 	at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:1751) ~[spigot-1.17.1.jar:3284a-Spigot-3892929-0ab8487]
[20.12 18:42:16] [Server] 	at net.minecraft.network.protocol.game.PacketPlayInChat.a(PacketPlayInChat.java:46) ~[spigot-1.17.1.jar:3284a-Spigot-3892929-0ab8487]
[20.12 18:42:16] [Server] 	at net.minecraft.network.protocol.game.PacketPlayInChat.a(PacketPlayInChat.java:1) ~[spigot-1.17.1.jar:3284a-Spigot-3892929-0ab8487]
[20.12 18:42:16] [Server] 	at net.minecraft.network.protocol.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:30) ~[spigot-1.17.1.jar:3284a-Spigot-3892929-0ab8487]
[20.12 18:42:16] [Server] 	at net.minecraft.server.TickTask.run(SourceFile:18) ~[spigot-1.17.1.jar:3284a-Spigot-3892929-0ab8487]
[20.12 18:42:16] [Server] 	at net.minecraft.util.thread.IAsyncTaskHandler.executeTask(SourceFile:151) ~[spigot-1.17.1.jar:3284a-Spigot-3892929-0ab8487]
[20.12 18:42:16] [Server] 	at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[spigot-1.17.1.jar:3284a-Spigot-3892929-0ab8487]
[20.12 18:42:16] [Server] 	at net.minecraft.util.thread.IAsyncTaskHandler.executeNext(SourceFile:125) ~[spigot-1.17.1.jar:3284a-Spigot-3892929-0ab8487]
[20.12 18:42:16] [Server] 	at net.minecraft.server.MinecraftServer.bf(MinecraftServer.java:1148) ~[spigot-1.17.1.jar:3284a-Spigot-3892929-0ab8487]
[20.12 18:42:16] [Server] 	at net.minecraft.server.MinecraftServer.executeNext(MinecraftServer.java:1141) ~[spigot-1.17.1.jar:3284a-Spigot-3892929-0ab8487]
[20.12 18:42:16] [Server] 	at net.minecraft.util.thread.IAsyncTaskHandler.executeAll(SourceFile:110) ~[spigot-1.17.1.jar:3284a-Spigot-3892929-0ab8487]
[20.12 18:42:16] [Server] 	at net.minecraft.server.MinecraftServer.sleepForTick(MinecraftServer.java:1124) ~[spigot-1.17.1.jar:3284a-Spigot-3892929-0ab8487]
[20.12 18:42:16] [Server] 	at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1054) ~[spigot-1.17.1.jar:3284a-Spigot-3892929-0ab8487]
[20.12 18:42:16] [Server] 	at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:305) ~[spigot-1.17.1.jar:3284a-Spigot-3892929-0ab8487]
[20.12 18:42:16] [Server] 	at java.lang.Thread.run(Thread.java:831) [?:?]
[20.12 18:42:16] [Server] Caused byjava.lang.NullPointerException: Cannot invoke "org.bukkit.scoreboard.Team.removeEntry(String)" because the return value of "com.booksaw.betterTeams.Team.getScoreboardTeam(org.bukkit.scoreboard.Scoreboard)" is null
[20.12 18:42:16] [Server] 	at com.booksaw.betterTeams.events.MCTeamManagement.remove(MCTeamManagement.java:100) ~[?:?]
[20.12 18:42:16] [Server] 	at com.booksaw.betterTeams.events.MCTeamManagement.removeAll(MCTeamManagement.java:71) ~[?:?]
[20.12 18:42:16] [Server] 	at com.booksaw.betterTeams.Main.onDisable(Main.java:200) ~[?:?]
[20.12 18:42:16] [Server] 	at com.booksaw.betterTeams.Main.reload(Main.java:284) ~[?:?]
[20.12 18:42:16] [Server] 	at com.booksaw.betterTeams.commands.teama.ReloadTeama.onCommand(ReloadTeama.java:17) ~[?:?]
[20.12 18:42:16] [Server] 	at com.booksaw.betterTeams.commands.ParentCommand.onCommand(ParentCommand.java:135) ~[?:?]
[20.12 18:42:16] [Server] 	at com.booksaw.betterTeams.BooksawCommand.execute(BooksawCommand.java:56) ~[?:?]
[20.12 18:42:16] [Server] 	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:149) ~[spigot-1.17.1.jar:3284a-Spigot-3892929-0ab8487]
[20.12 18:42:16] [Server] 	... more```

**Comment by booksaw** [comment]
duplicate of #289
