### ISSUE TITLE
[BUG] Give Me an Error every time someone type message after adding PlaceHolderAPI plugin

### ISSUE THREAD

**Issue by darktet** [booksaw/BetterTeams#295]
**Describe the bug**
When someone type any message in chat it's give error in console instead showing there team name in chat it's only happen when I add PaceHolderAPI along side Better Team Chat

**To Reproduce**
Steps to reproduce the behaviour:
1. Add Tab (v3.0.1), LuckPerm (v5.3.64), ProtocolLib (v4.7.0) and Vault (1.7.3-b131) plugin 
2. Add Basic Configuration for tab and LuckPerm
3. Now add Placeholderapi (2.11.0)
4. Type anything in message and see console

**Expected behaviour**
It should Display Team Name In Chat

**Screenshots**
![Demo Screenshot](https://i.imgur.com/UQ9f8tJ.png)

**Details**
Please provide the following details about your server set-up:
- Spigon Version (found by running /version): CraftBukkit version 3284a-Spigot-3892929-0ab8487 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT)
- Paper version (found by running /version): Paper version git-Paper-249 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: 6fa1983)
- BetterTeams version (found by running /version BetterTeams): 4.2.1

**Additional context**
<details>
<summary>Paper Error</summary>
[19:40:01 ERROR]: Could not pass event AsyncPlayerChatEvent to BetterTeams v4.2.1
java.util.UnknownFormatConversionException: Conversion = ' '
    at java.util.Formatter.parse(Formatter.java:2750) ~[?:?]
    at java.util.Formatter.format(Formatter.java:2671) ~[?:?]
    at java.util.Formatter.format(Formatter.java:2625) ~[?:?]
    at java.lang.String.format(String.java:4140) ~[?:?]
    at com.booksaw.betterTeams.events.ChatManagement$PrefixType.getUpdatedFormat(ChatManagement.java:105) ~[BetterTeams.jar:?]
    at com.booksaw.betterTeams.events.ChatManagement.onChat(ChatManagement.java:74)
~[BetterTeams.jar:?]
    at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor78.execute(Unknown Source) ~[?:?]
    at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.17.1.jar:git-Paper-249]
    at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76) ~[patched_1.17.1.jar:git-Paper-249]
    at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.17.1.jar:git-Paper-249]
    at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:624) [patched_1.17.1.jar:git-Paper-249]
    at io.papermc.paper.adventure.ChatProcessor.post(ChatProcessor.java:234) [patched_1.17.1.jar:git-Paper-249]
    at io.papermc.paper.adventure.ChatProcessor.processingLegacyFirst(ChatProcessor.java:116) [patched_1.17.1.jar:git-Paper-249]
    at io.papermc.paper.adventure.ChatProcessor.process(ChatProcessor.java:65) [patched_1.17.1.jar:git-Paper-249]
    at net.minecraft.server.network.PlayerConnection.chat(PlayerConnection.java:2165) [patched_1.17.1.jar:git-Paper-249]
    at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:2076) [patched_1.17.1.jar:git-Paper-249]
    at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:2042) [patched_1.17.1.jar:git-Paper-249]
    at net.minecraft.network.protocol.game.PacketPlayInChat$1.run(PacketPlayInChat.java:40) [patched_1.17.1.jar:git-Paper-249]
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539) [?:?]
    at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) [?:?]
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) [?:?]
    at java.lang.Thread.run(Thread.java:833) [?:?]
</details>
<details>
<summary>Spigot Error</summary>
[19:53:07] [Async Chat Thread - #0/ERROR]: Could not pass event AsyncPlayerChatEvent to BetterTeams v4.2.1
org.bukkit.event.EventException: null
    at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[spigot-1.17.1.jar:3284a-Spigot-3892929-0ab8487]
    at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[spigot-1.17.1.jar:3284a-Spigot-3892929-0ab8487]
    at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:589) [spigot-1.17.1.jar:3284a-Spigot-3892929-0ab8487]
    at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:576) [spigot-1.17.1.jar:3284a-Spigot-3892929-0ab8487]
    at net.minecraft.server.network.PlayerConnection.chat(PlayerConnection.java:1853) [spigot-1.17.1.jar:3284a-Spigot-3892929-0ab8487]
    at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:1787) [spigot-1.17.1.jar:3284a-Spigot-3892929-0ab8487]
    at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:1753) [spigot-1.17.1.jar:3284a-Spigot-3892929-0ab8487]
    at net.minecraft.network.protocol.game.PacketPlayInChat$1.run(PacketPlayInChat.java:40) [spigot-1.17.1.jar:3284a-Spigot-3892929-0ab8487]
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539) [?:?]
    at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) [?:?]
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) [?:?]
    at java.lang.Thread.run(Thread.java:833) [?:?]
Caused by: java.util.UnknownFormatConversionException: Conversion = ' '
    at java.util.Formatter.parse(Formatter.java:2750) ~[?:?]
    at java.util.Formatter.format(Formatter.java:2671) ~[?:?]
    at java.util.Formatter.format(Formatter.java:2625) ~[?:?]
    at java.lang.String.format(String.java:4140) ~[?:?]
    at com.booksaw.betterTeams.events.ChatManagement$PrefixType.getUpdatedFormat(ChatManagement.java:105) ~[?:?]
    at com.booksaw.betterTeams.events.ChatManagement.onChat(ChatManagement.java:74) ~[?:?]
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
    at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
    at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
    at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-1.17.1.jar:3284a-Spigot-3892929-0ab8487]
    ... 12 more
[19:53:07] [Async Chat Thread - #0/INFO]:
</details>

**Comment by booksaw** [comment]
Please could you share the entire error message

**Comment by Mato1111** [comment]
The issue happened on my server too after updating Placeholder

**Comment by darktet** [comment]
> Please could you share the entire error message

[**Latest Error Logs PaperMC**](https://pastebin.ubuntu.com/p/TBkCQvFRjn/)
[**Letest Error Logs SpigotMC**](https://pastebin.ubuntu.com/p/4zmK45jfRg/)

**Comment by srnyx** [comment]
Getting it too on Purpur 1.17.1: https://paste.srnyx.xyz/ozafefepix.md
It's because of the latest PlaceholderAPI update: https://www.spigotmc.org/resources/placeholderapi.6245/update?update=436451

**Comment by booksaw** [comment]
Thank you srnyx, I have been trying to track down the cause of this issue for a whole now

**Comment by booksaw** [comment]
Ive made a bug report on the PlaceholderAPI github, there is nothing more I can do
