### ISSUE TITLE
[BUG] Error when player quit in console.

### ISSUE THREAD

**Issue by PJGamerr** [booksaw/BetterTeams#303]
### What is the bug?

When a player quit froms server, console send this error:

[20:23:46 ERROR]: Could not pass event PlayerQuitEvent to BetterTeams v4.3.1
java.lang.NullPointerException: Cannot invoke "com.booksaw.betterTeams.Team.getOnlineMemebers()" because "team" is null
        at com.booksaw.betterTeams.team.storage.storageManager.SeparatedYamlStorageManager.onLeave(SeparatedYamlStorageManager.java:387) ~[BetterTeams.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor504.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.17.1.jar:git-Purpur-1428]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.17.1.jar:git-Purpur-1428]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.17.1.jar:git-Purpur-1428]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:628) ~[patched_1.17.1.jar:git-Purpur-1428]
        at net.minecraft.server.players.PlayerList.disconnect(PlayerList.java:610) ~[patched_1.17.1.jar:git-Purpur-1428]
        at net.minecraft.server.players.PlayerList.disconnect(PlayerList.java:593) ~[patched_1.17.1.jar:git-Purpur-1428]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.onDisconnect(ServerGamePacketListenerImpl.java:2049) ~[app:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.onDisconnect(ServerGamePacketListenerImpl.java:2029) ~[app:?]
        at net.minecraft.network.Connection.handleDisconnection(Connection.java:743) ~[app:?]
        at net.minecraft.server.network.ServerConnectionListener.tick(ServerConnectionListener.java:221) ~[app:?]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1681) ~[patched_1.17.1.jar:git-Purpur-1428]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:528) ~[patched_1.17.1.jar:git-Purpur-1428]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1507) ~[patched_1.17.1.jar:git-Purpur-1428]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1300) ~[patched_1.17.1.jar:git-Purpur-1428]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:322) ~[patched_1.17.1.jar:git-Purpur-1428]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]

### Expected Behaviour

it shouldn't appear haha

### How to Reproduce

When a player quit froms server, console send this error:

### Output of /teama version

![2022-01-11_20 57 57](https://user-images.githubusercontent.com/85345525/149012332-f162f21d-5b6e-4943-bb7c-4685a6b1ee9d.png)

**Comment by booksaw** [comment]
This bug has been fixed and the patch will be included in the next update. Thank you for reporting.
