### ISSUE TITLE
[BUG] An avaliable team cannot be found

### ISSUE THREAD

**Issue by Wakestb** [booksaw/BetterTeams#307]
### What is the bug?

[Server thread/WARN]: An avaliable team cannot be found, be prepared for a lot of errors. (this should never happen, and should always be reported to booksaw) [19:52:10] [Server thread/WARN]: This catch is merely here to stop the server crashing
[19:52:10] [Server thread/ERROR]: Could not pass event PlayerJoinEvent to BetterTeams v4.2.1 

this comes up when people try to leave or join a team.

### Expected Behaviour

Maybe help 0.0

### How to Reproduce

1. try to join or leave a team.

### Error message

[Server thread/WARN]: An avaliable team cannot be found, be prepared for a lot of errors. (this should never happen, and should always be reported to booksaw) [19:55:57] [Server thread/WARN]: This catch is merely here to stop the server crashing
[19:55:57] [Server thread/ERROR]: Could not pass event PlayerJoinEvent to BetterTeams v4.2.1 org.bukkit.event.EventException: null at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[spigot-api-1.18-R0.1-SNAPSHOT.jar:?] at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[spigot-api-1.18-R0.1-SNAPSHOT.jar:?]
at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:589) ~[spigot-api-1.18-R0.1-SNAPSHOT.jar:?] at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:576) ~[spigot-api-1.18-R0.1-SNAPSHOT.jar:?] at net.minecraft.server.players.PlayerList.a(PlayerList.java:277) ~[spigot-1.18-R0.1-SNAPSHOT.jar:3358-Spigot-dbf4938-8b98c8e] at net.minecraft.server.network.LoginListener.a(LoginListener.java:193) ~[spigot-1.18-R0.1-SNAPSHOT.jar:3358-Spigot-dbf4938-8b98c8e] at net.minecraft.server.network.LoginListener.c(LoginListener.java:179) ~[spigot-1.18-R0.1-SNAPSHOT.jar:3358-Spigot-dbf4938-8b98c8e] at net.minecraft.server.network.LoginListener.b(LoginListener.java:74) ~[spigot-1.18-R0.1-SNAPSHOT.jar:3358-Spigot-dbf4938-8b98c8e] at net.minecraft.network.NetworkManager.a(NetworkManager.java:246) ~[spigot-1.18-R0.1-SNAPSHOT.jar:3358-Spigot-dbf4938-8b98c8e] at net.minecraft.server.network.ServerConnection.c(ServerConnection.java:172) ~[spigot-1.18-R0.1-SNAPSHOT.jar:3358-Spigot-dbf4938-8b98c8e] at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1322) ~[spigot-1.18-R0.1-SNAPSHOT.jar:3358-Spigot-dbf4938-8b98c8e]
at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:428) ~[spigot-1.18-R0.1-SNAPSHOT.jar:3358-Spigot-dbf4938-8b98c8e] at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1206) ~[spigot-1.18-R0.1-SNAPSHOT.jar:3358-Spigot-dbf4938-8b98c8e] at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1034) ~[spigot-1.18-R0.1-SNAPSHOT.jar:3358-Spigot-dbf4938-8b98c8e] at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:304) ~[spigot-1.18-R0.1-SNAPSHOT.jar:3358-Spigot-dbf4938-8b98c8e] at java.lang.Thread.run(Thread.java:833) [?:?] Caused by: java.lang.NullPointerException: Cannot invoke "org.bukkit.scoreboard.Team.addEntry(String)" because the return value of "com.booksaw.betterTeams.Team.getScoreboardTeam(org.bukkit.scoreboard.Scoreboard)" is null at com.booksaw.betterTeams.events.MCTeamManagement.displayBelowName(MCTeamManagement.java:62) ~[?:?]
at com.booksaw.betterTeams.events.MCTeamManagement.playerJoinEvent(MCTeamManagement.java:109) ~[?:?] at jdk.internal.reflect.GeneratedMethodAccessor128.invoke(Unknown Source) ~[?:?] at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-api-1.18-R0.1-SNAPSHOT.jar:?] ... 15 more

### Output of /teama version

idk what this is to be honest.

**Comment by booksaw** [comment]
Run /teama version and provide the output else this bug will not be reviewed

**Comment by Wakestb** [comment]
it says that the version is 4.2.1.

**Comment by booksaw** [comment]
Update to the latest version and tell me if the bug still occurs

**Comment by booksaw** [comment]
This issue is being closed for inactivity. If you are still having problems feel free to open a new issue linking this one, make sure you answer any questions asked in the new issue.
