### ISSUE TITLE
[BUG] /team list error on with no teams created

### ISSUE THREAD

**Issue by tooop4u** [booksaw/BetterTeams#318]
### What is the bug?

Running `/team list` while there are no teams created results in an error.

### Expected Behaviour

Perhaps have a message saying that there are no teams available to be shown?

### How to Reproduce

Run command /team list.

### Error message

```
Could not sort teams for results, report the following error:
java.sql.SQLException: Illegal operation on empty result set.
       at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:129)
       at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:97)
       at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:89)
       at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:63)
       at com.mysql.cj.jdbc.result.ResultSetImpl.checkRowPos(ResultSetImpl.java:517)
       at com.mysql.cj.jdbc.result.UpdatableResultSet.checkRowPos(UpdatableResultSet.java:204)
       at com.mysql.cj.jdbc.result.ResultSetImpl.getString(ResultSetImpl.java:870)
       at com.mysql.cj.jdbc.result.ResultSetImpl.getString(ResultSetImpl.java:888)
       at BetterTeams.jar//com.booksaw.betterTeams.team.storage.storageManager.SQLStorageManager.getTeamsFromResultSet(SQLStorageManager.java:212)
       at BetterTeams.jar//com.booksaw.betterTeams.team.storage.storageManager.SQLStorageManager.sortTeamsByMembers(SQLStorageManager.java:196)
       at BetterTeams.jar//com.booksaw.betterTeams.commands.team.ListCommand$1.run(ListCommand.java:36)
       at org.bukkit.craftbukkit.v1_18_R1.scheduler.CraftTask.run(CraftTask.java:101)
       at org.bukkit.craftbukkit.v1_18_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57)
       at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
       at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
       at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
       at java.base/java.lang.Thread.run(Thread.java:833)
```

### Output of /teama version

```
Storage Method: com.booksaw.betterTeams.team.storage.storageManager.SQLStorageManager
Minecraft Version: git-Purpur-1555 (MC: 1.18.1)
Current plugin version: 4.3.3
```

**Comment by booksaw** [comment]
This bug has been fixed and the patch will be included in the next update. Thank you for reporting.
