### ISSUE TITLE
[BUG] Team reader bug

### ISSUE THREAD

**Issue by D1p4k** [booksaw/BetterTeams#339]
### What is the bug?

Some Commands dont work on Players like /team info, but on Nations they do, 

### Expected Behaviour

That the Commands can be used.

### How to Reproduce

1. Run Command
2. There should be an internal Error 

### Error message

Caused by: java.lang.NullPointerException: Cannot invoke "String.toLowerCase()" because the return value of "com.booksaw.betterTeams.Team.getName()" is null
        at com.booksaw.betterTeams.team.storage.storageManager.SeparatedYamlStorageManager.deleteTeamStorage(SeparatedYamlStorageManager.java:166) ~[BetterTeams.jar:?]
        at com.booksaw.betterTeams.team.TeamManager.disbandTeam(TeamManager.java:390) ~[BetterTeams.jar:?]
        at com.booksaw.betterTeams.Team.<init>(Team.java:299) ~[BetterTeams.jar:?]
        at com.booksaw.betterTeams.team.TeamManager.getTeam(TeamManager.java:73) ~[BetterTeams.jar:?]
        at com.booksaw.betterTeams.team.TeamManager.getTeam(TeamManager.java:121) ~[BetterTeams.jar:?]
        at com.booksaw.betterTeams.Team.getTeam(Team.java:92) ~[BetterTeams.jar:?]
        at com.booksaw.betterTeams.events.MCTeamManagement.remove(MCTeamManagement.java:96) ~[BetterTeams.jar:?]
        at com.booksaw.betterTeams.events.MCTeamManagement.removeAll(MCTeamManagement.java:71) ~[BetterTeams.jar:?]
        at com.booksaw.betterTeams.Main.onDisable(Main.java:228) ~[BetterTeams.jar:?]
        at com.booksaw.betterTeams.Main.reload(Main.java:314) ~[BetterTeams.jar:?]
        at com.booksaw.betterTeams.commands.teama.ReloadTeama.onCommand(ReloadTeama.java:18) ~[BetterTeams.jar:?]
        at com.booksaw.betterTeams.commands.ParentCommand.onCommand(ParentCommand.java:135) ~[BetterTeams.jar:?]
        at com.booksaw.betterTeams.BooksawCommand.execute(BooksawCommand.java:56) ~[BetterTeams.jar:?]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159) ~[pufferfish-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        ... 20 more

[10:06:10 ERROR]: Could not pass event InventoryCloseEvent to BetterTeams v4.3.7
java.lang.NullPointerException: Cannot invoke "String.toLowerCase()" because the return value of "com.booksaw.betterTeams.Team.getName()" is null
        at com.booksaw.betterTeams.team.storage.storageManager.SeparatedYamlStorageManager.deleteTeamStorage(SeparatedYamlStorageManager.java:166) ~[BetterTeams.jar:?]
        at com.booksaw.betterTeams.team.TeamManager.disbandTeam(TeamManager.java:390) ~[BetterTeams.jar:?]
        at com.booksaw.betterTeams.Team.<init>(Team.java:299) ~[BetterTeams.jar:?]
        at com.booksaw.betterTeams.team.TeamManager.getTeam(TeamManager.java:73) ~[BetterTeams.jar:?]
        at com.booksaw.betterTeams.team.TeamManager.getTeam(TeamManager.java:121) ~[BetterTeams.jar:?]
        at com.booksaw.betterTeams.Team.getTeam(Team.java:92) ~[BetterTeams.jar:?]
        at com.booksaw.betterTeams.events.InventoryManagement.onClose(InventoryManagement.java:23) ~[BetterTeams.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor339.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:75) ~[pufferfish-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76) ~[pufferfish-api-1.18.2-R0.1-SNAPSHOT.jar:git-Pufferfish-61]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[pufferfish-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:631) ~[pufferfish-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_18_R2.event.CraftEventFactory.handleInventoryCloseEvent(CraftEventFactory.java:1532) ~[pufferfish-1.18.2.jar:git-Pufferfish-61]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleContainerClose(ServerGamePacketListenerImpl.java:2627) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleContainerClose(ServerGamePacketListenerImpl.java:2620) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundContainerClosePacket.handle(ServerboundContainerClosePacket.java:15) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundContainerClosePacket.handle(ServerboundContainerClosePacket.java:6) ~[?:?]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$1(PacketUtils.java:51) ~[?:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[pufferfish-1.18.2.jar:git-Pufferfish-61]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:23) ~[?:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1401) ~[pufferfish-1.18.2.jar:git-Pufferfish-61]
        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:188) ~[pufferfish-1.18.2.jar:git-Pufferfish-61]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1378) ~[pufferfish-1.18.2.jar:git-Pufferfish-61]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1371) ~[pufferfish-1.18.2.jar:git-Pufferfish-61]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1349) ~[pufferfish-1.18.2.jar:git-Pufferfish-61]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1231) ~[pufferfish-1.18.2.jar:git-Pufferfish-61]
        at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:317) ~[pufferfish-1.18.2.jar:git-Pufferfish-61]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]

[10:07:44 INFO]: Louis_DS issued server command: /team info AtrixKRN
[10:07:44 ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing 'team info AtrixKRN' in com.booksaw.betterTeams.BooksawCommand(team)
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:169) ~[pufferfish-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_18_R2.CraftServer.dispatchCommand(CraftServer.java:906) ~[pufferfish-1.18.2.jar:git-Pufferfish-61]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleCommand(ServerGamePacketListenerImpl.java:2307) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleChat(ServerGamePacketListenerImpl.java:2118) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleChat(ServerGamePacketListenerImpl.java:2099) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundChatPacket.handle(ServerboundChatPacket.java:46) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundChatPacket.a(ServerboundChatPacket.java:6) ~[?:?]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$1(PacketUtils.java:51) ~[?:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[pufferfish-1.18.2.jar:git-Pufferfish-61]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:23) ~[?:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1401) ~[pufferfish-1.18.2.jar:git-Pufferfish-61]
        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:188) ~[pufferfish-1.18.2.jar:git-Pufferfish-61]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1378) ~[pufferfish-1.18.2.jar:git-Pufferfish-61]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1371) ~[pufferfish-1.18.2.jar:git-Pufferfish-61]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1349) ~[pufferfish-1.18.2.jar:git-Pufferfish-61]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1231) ~[pufferfish-1.18.2.jar:git-Pufferfish-61]
        at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:317) ~[pufferfish-1.18.2.jar:git-Pufferfish-61]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.NullPointerException: Cannot invoke "String.toLowerCase()" because the return value of "com.booksaw.betterTeams.Team.getName()" is null
        at com.booksaw.betterTeams.team.storage.storageManager.SeparatedYamlStorageManager.deleteTeamStorage(SeparatedYamlStorageManager.java:166) ~[BetterTeams.jar:?]
        at com.booksaw.betterTeams.team.TeamManager.disbandTeam(TeamManager.java:390) ~[BetterTeams.jar:?]
        at com.booksaw.betterTeams.Team.<init>(Team.java:299) ~[BetterTeams.jar:?]
        at com.booksaw.betterTeams.team.TeamManager.getTeam(TeamManager.java:73) ~[BetterTeams.jar:?]
        at com.booksaw.betterTeams.team.TeamManager.getTeam(TeamManager.java:121) ~[BetterTeams.jar:?]
        at com.booksaw.betterTeams.team.TeamManager.getTeam(TeamManager.java:97) ~[BetterTeams.jar:?]
        at com.booksaw.betterTeams.Team.getTeam(Team.java:88) ~[BetterTeams.jar:?]
        at com.booksaw.betterTeams.commands.team.InfoCommand.onCommand(InfoCommand.java:122) ~[BetterTeams.jar:?]
        at com.booksaw.betterTeams.commands.ParentCommand.onCommand(ParentCommand.java:135) ~[BetterTeams.jar:?]
        at com.booksaw.betterTeams.BooksawCommand.execute(BooksawCommand.java:56) ~[BetterTeams.jar:?]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159) ~[pufferfish-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        ... 20 more

### Output of /teama version

[CHAT] [BetterTeams] Storage Method: com.booksaw.betterTeams.team.storage.storageManager.SeparatedYamlStorageManager

[CHAT] [BetterTeams] Minecraft Version: git-Pufferfish-61 (MC: 1.18.2)

[CHAT] [BetterTeams] Current plugin version: 4.3.7

### Additional Information

Team Names for Chat and Tab can still be loaded and 

/team info TEAM does still work

But invites from Normal users seem not too.

**Comment by booksaw** [comment]
Hi, I have tried to reproduce this bug to no success, could you give information on how reproduce this bug from a clean install.

**Comment by D1p4k** [comment]
> Hi, I have tried to reproduce this bug to no success, could you give information on how reproduce this bug from a clean install.

Should I send my data, configs or something like that?

**Comment by booksaw** [comment]
try setting `rebuildLookups` to true in config.yml and restarting your server. 
if that does not fix the issue, then yeah sharing zip your betterteams folder and share it with me.

**Comment by D1p4k** [comment]
Ok

**Comment by D1p4k** [comment]
>....
[10:13:03 ERROR]: Error occurred while enabling BetterTeams v4.4.0 (Is it up to date?)
java.lang.NullPointerException: Cannot invoke "String.toLowerCase()" because the return value of "org.bukkit.configuration.file.YamlConfiguration.getString(String)" is null
	at com.booksaw.betterTeams.team.storage.storageManager.SeparatedYamlStorageManager.rebuildLookups(SeparatedYamlStorageManager.java:458) ~[BetterTeams.jar:?]
	at com.booksaw.betterTeams.Team.setupTeamManager(Team.java:63) ~[BetterTeams.jar:?]
	at com.booksaw.betterTeams.Main.setupStorage(Main.java:469) ~[BetterTeams.jar:?]
	at com.booksaw.betterTeams.Main.onEnable(Main.java:179) ~[BetterTeams.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[pufferfish-api-1.18.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[pufferfish-api-1.18.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:501) ~[pufferfish-api-1.18.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_18_R2.CraftServer.enablePlugin(CraftServer.java:560) ~[pufferfish-1.18.2.jar:git-Pufferfish-61]
	at org.bukkit.craftbukkit.v1_18_R2.CraftServer.enablePlugins(CraftServer.java:474) ~[pufferfish-1.18.2.jar:git-Pufferfish-61]
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:666) ~[pufferfish-1.18.2.jar:git-Pufferfish-61]
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:433) ~[pufferfish-1.18.2.jar:git-Pufferfish-61]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:318) ~[pufferfish-1.18.2.jar:git-Pufferfish-61]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1165) ~[pufferfish-1.18.2.jar:git-Pufferfish-61]
	at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:317) ~[pufferfish-1.18.2.jar:git-Pufferfish-61]

**Comment by D1p4k** [comment]
new error

**Comment by D1p4k** [comment]
https://pastebin.com/BLH0UMTR

**Comment by booksaw** [comment]
could you share the contents of the file `1192b0a4-c676-48ce-968e-75e608a7578c.yml` found in betterteams/teaminfo as that is the file with the error.

**Comment by D1p4k** [comment]
My entire Server crashed I will get back to you when its back on.

**Comment by D1p4k** [comment]
```# Do not edit this file, all changes can be made in game, check the wiki page on commands for more details: https://github.com/booksaw/BetterTeams/wiki/Commands```
@booksaw

**Comment by D1p4k** [comment]
Thats everything

**Comment by booksaw** [comment]
sorry for the long delay, delete the file and set `rebuildLookups` to true and it should all work
