### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by Gonaaal** [booksaw/BetterTeams#340]
### What is the bug?

Hello, I have an error with better teams, before it worked for me, I use purpur with via version and it gives this error in console: https://pastebin.com/Q7uKk86L  and error in minecraft: https://prnt.sc/1m2AbXtfON30

### Expected Behaviour

Let him try to fix what does not work is the plugin in all its commands or variables

### How to Reproduce

/team create (name team)

### Error message

[08:28:58 INFO]: Gonaaal issued server command: /team create a
[08:28:58 ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing 'team create a' in com.booksaw.betterTeams.BooksawCommand(team)
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:182) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_18_R2.CraftServer.dispatchCommand(CraftServer.java:905) ~[purpur-1.18.2.jar:git-Purpur-1609]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleCommand(ServerGamePacketListenerImpl.java:2389) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleChat(ServerGamePacketListenerImpl.java:2200) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleChat(ServerGamePacketListenerImpl.java:2181) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundChatPacket.handle(ServerboundChatPacket.java:46) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundChatPacket.a(ServerboundChatPacket.java:6) ~[?:?]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$1(PacketUtils.java:51) ~[?:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[purpur-1.18.2.jar:git-Purpur-1609]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:23) ~[?:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1426) ~[purpur-1.18.2.jar:git-Purpur-1609]
        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:188) ~[purpur-1.18.2.jar:git-Purpur-1609]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1403) ~[purpur-1.18.2.jar:git-Purpur-1609]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1396) ~[purpur-1.18.2.jar:git-Purpur-1609]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1374) ~[purpur-1.18.2.jar:git-Purpur-1609]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1256) ~[purpur-1.18.2.jar:git-Purpur-1609]
        at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:320) ~[purpur-1.18.2.jar:git-Purpur-1609]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.NullPointerException: Cannot invoke "String.toLowerCase()" because the return value of "com.booksaw.betterTeams.Team.getName()" is null
        at com.booksaw.betterTeams.team.storage.storageManager.SeparatedYamlStorageManager.deleteTeamStorage(SeparatedYamlStorageManager.java:166) ~[BetterTeams.jar:?]
        at com.booksaw.betterTeams.team.TeamManager.disbandTeam(TeamManager.java:390) ~[BetterTeams.jar:?]
        at com.booksaw.betterTeams.Team.<init>(Team.java:299) ~[BetterTeams.jar:?]
        at com.booksaw.betterTeams.team.TeamManager.getTeam(TeamManager.java:73) ~[BetterTeams.jar:?]
        at com.booksaw.betterTeams.team.TeamManager.getTeam(TeamManager.java:121) ~[BetterTeams.jar:?]
        at com.booksaw.betterTeams.Team.getTeam(Team.java:92) ~[BetterTeams.jar:?]
        at com.booksaw.betterTeams.commands.presets.NoTeamSubCommand.onCommand(NoTeamSubCommand.java:20) ~[BetterTeams.jar:?]
        at com.booksaw.betterTeams.commands.ParentCommand.onCommand(ParentCommand.java:135) ~[BetterTeams.jar:?]
        at com.booksaw.betterTeams.BooksawCommand.execute(BooksawCommand.java:56) ~[BetterTeams.jar:?]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:172) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        ... 20 more

### Output of /teama version

https://user-images.githubusercontent.com/87767165/163962550-c5f49169-e401-4aa5-b0df-b2586b9dd64f.png

### Additional Information

Nothing

**Comment by booksaw** [comment]
I have tried to recreate this bug but the steps to reproduce are not working for me, could you provide the steps to reproduce this bug from a clean installation.

**Comment by D1p4k** [comment]
> I have tried to recreate this bug but the steps to reproduce are not working for me, could you provide the steps to reproduce this bug from a clean installation.

```java
Caused by: java.lang.NullPointerException: Cannot invoke "String.toLowerCase()" because the return value of "com.booksaw.betterTeams.Team.getName()" is null
        at com.booksaw.betterTeams.team.storage.storageManager.SeparatedYamlStorageManager.deleteTeamStorage(SeparatedYamlStorageManager.java:166) ~[BetterTeams.jar:?]
```
Seems to be the same Issue with a empty team file #339 , checking if its empty an if skipping the file should fix it right @booksaw ?

**Comment by D1p4k** [comment]
Oh it is already in the newest Version :)
