### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by SaidInDex** [booksaw/BetterTeams#383]
### What is the bug?

So basically I downloaded plugin bank https://www.curseforge.com/minecraft/bukkit-plugins/bank-lite and when I open bank i get this err

### Expected Behaviour

No err

### How to Reproduce

1. I open the bank
2. Select items and I get err

### Error message

[17:24:31] [Server thread/ERROR]: Could not pass event InventoryCloseEvent to BetterTeams v4.5.0
org.bukkit.event.EventException: null
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[spigot-api-1.19.1-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[spigot-api-1.19.1-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:589) ~[spigot-api-1.19.1-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:576) ~[spigot-api-1.19.1-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_19_R1.event.CraftEventFactory.handleInventoryCloseEvent(CraftEventFactory.java:1379) ~[spigot-1.19.1-R0.1-SNAPSHOT.jar:3563-Spigot-2183145-1e3bf58]
	at net.minecraft.server.level.EntityPlayer.q(EntityPlayer.java:1464) ~[spigot-1.19.1-R0.1-SNAPSHOT.jar:3563-Spigot-2183145-1e3bf58]
	at org.bukkit.craftbukkit.v1_19_R1.entity.CraftHumanEntity.closeInventory(CraftHumanEntity.java:441) ~[spigot-1.19.1-R0.1-SNAPSHOT.jar:3563-Spigot-2183145-1e3bf58]
	at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftTask.run(CraftTask.java:82) ~[spigot-1.19.1-R0.1-SNAPSHOT.jar:3563-Spigot-2183145-1e3bf58]
	at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:415) ~[spigot-1.19.1-R0.1-SNAPSHOT.jar:3563-Spigot-2183145-1e3bf58]
	at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1245) ~[spigot-1.19.1-R0.1-SNAPSHOT.jar:3563-Spigot-2183145-1e3bf58]
	at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:394) ~[spigot-1.19.1-R0.1-SNAPSHOT.jar:3563-Spigot-2183145-1e3bf58]
	at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1197) ~[spigot-1.19.1-R0.1-SNAPSHOT.jar:3563-Spigot-2183145-1e3bf58]
	at net.minecraft.server.MinecraftServer.v(MinecraftServer.java:1013) ~[spigot-1.19.1-R0.1-SNAPSHOT.jar:3563-Spigot-2183145-1e3bf58]
	at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:293) ~[spigot-1.19.1-R0.1-SNAPSHOT.jar:3563-Spigot-2183145-1e3bf58]
	at java.lang.Thread.run(Thread.java:833) [?:?]
Caused by: java.lang.IllegalStateException: Title not set
	at com.google.common.base.Preconditions.checkState(Preconditions.java:502) ~[guava-31.0.1-jre.jar:?]
	at net.minecraft.world.inventory.Container.getTitle(Container.java:91) ~[spigot-1.19.1-R0.1-SNAPSHOT.jar:3563-Spigot-2183145-1e3bf58]
	at org.bukkit.craftbukkit.v1_19_R1.inventory.CraftInventoryView.getTitle(CraftInventoryView.java:69) ~[spigot-1.19.1-R0.1-SNAPSHOT.jar:3563-Spigot-2183145-1e3bf58]
	at com.booksaw.betterTeams.events.InventoryManagement.onClose(InventoryManagement.java:21) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-api-1.19.1-R0.1-SNAPSHOT.jar:?]
	... 14 mores

### Output of /teama version

Latest version

### Additional Information

Nothing

**Comment by booksaw** [comment]
I was not able to reproduce the issue without more detailed steps, but that bug sounds like it is due to a bug with the bank plugin or something along those lines, I have not looked through the code but essentially it would appear that the title of a GUI is being set to be `null` even though spigot states that the title of a GUI is `@NotNull` - should never return null.

I have added an additional check to ensure that the inventory type is correct. But I think it is down to the bank plugin author to fix the problem on their end unless more detailed info on how to reproduce the bug is given.

Please open another bug report or reopen this one if you can provide more information.
