### ISSUE TITLE
[BUG] BETTERTEAMS ON COMMAND /TEAM KICK AND ERROR IN THE CONSOLE

### ISSUE THREAD

**Issue by tomimza** [booksaw/BetterTeams#390]
### What is the bug?

Bug in the console and use command /team kick

### Expected Behaviour

Being able to fix it as soon as possible.

### How to Reproduce

1. /team kick

### Error message

[07:55:50 ERROR]: Could not pass event AsyncPlayerChatEvent to BetterTeams v4.5.0
java.lang.NullPointerException: null
        at java.util.Objects.requireNonNull(Objects.java:208) ~[?:?]
        at com.booksaw.betterTeams.events.ChatManagement.onChat(ChatManagement.java:50) ~[BetterTeams.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor740.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:75) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:git-light-"aaf5e39"]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:670) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.adventure.ChatProcessor.post(ChatProcessor.java:381) ~[paper-1.19.2.jar:git-light-"aaf5e39"]
        at io.papermc.paper.adventure.ChatProcessor.process(ChatProcessor.java:96) ~[paper-1.19.2.jar:git-light-"aaf5e39"]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.chat(ServerGamePacketListenerImpl.java:2406) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.broadcastChatMessage(ServerGamePacketListenerImpl.java:2591) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.lambda$handleChat$17(ServerGamePacketListenerImpl.java:2232) ~[?:?]
        at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:718) ~[?:?]
        at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
        
        
        AND..
        
        
        [07:55:50 ERROR]: Could not pass event AsyncPlayerChatEvent to BetterTeams v4.5.0
java.lang.NullPointerException: null
        at java.util.Objects.requireNonNull(Objects.java:208) ~[?:?]
        at com.booksaw.betterTeams.events.ChatManagement.onChat(ChatManagement.java:50) ~[BetterTeams.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor740.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:75) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:git-light-"aaf5e39"]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:670) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.adventure.ChatProcessor.post(ChatProcessor.java:381) ~[paper-1.19.2.jar:git-light-"aaf5e39"]
        at io.papermc.paper.adventure.ChatProcessor.process(ChatProcessor.java:96) ~[paper-1.19.2.jar:git-light-"aaf5e39"]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.chat(ServerGamePacketListenerImpl.java:2406) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.broadcastChatMessage(ServerGamePacketListenerImpl.java:2591) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.lambda$handleChat$17(ServerGamePacketListenerImpl.java:2232) ~[?:?]
        at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:718) ~[?:?]
        at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]

### Output of /teama version

![image](https://user-images.githubusercontent.com/119277081/206864020-c130f460-5b2e-4adc-963f-862ad947b38b.png)

**Comment by booksaw** [comment]
I have been unable to recreate this error, please could you provide more detailed information 
![image](https://user-images.githubusercontent.com/13976636/208157555-362992dc-273b-480e-812f-4eea9095e5d4.png)

in the next update I have also added an additional error message, so it will be easier to track down what is causing the bug. So please screenshot this error again when the next update comes out

**Comment by booksaw** [comment]
This issue is being closed for inactivity. If you are still having problems feel free to open a new issue linking this one, make sure you answer any questions asked in the new issue.
