### ISSUE TITLE
[BUG] Special characters are not allowed error.

### ISSUE THREAD

**Issue by RealTriassic** [booksaw/BetterTeams#394]
### What is the bug?

Somehow, a player has created a clan with an illegal symbol in it, the symbol being 0x1F, supposedly also known as the Windows Control Character.

### Expected Behaviour

BetterTeams should have prevented the creation of a clan under this name.

As you can see in the below image, the illegal clan name is replaced by `...`, so the command does still function mostly normally.
![image](https://user-images.githubusercontent.com/40073455/211420149-f6217b4c-2942-4b94-9093-adec5fa80832.png)

### How to Reproduce

1. Create a clan with the 0x1F symbol.
2. Try to run any command that tries to display your clan name, such as `/clan top`.
3. Observe error in console.

### Error message

```
[22:14:05 ERROR]: Cannot load plugins/BetterTeams/teamInfo/archive-2022-12-20T002131Z.tar.gz
org.bukkit.configuration.InvalidConfigurationException: unacceptable code point '' (0x1F) special characters are not allowed
in "'reader'", position 0
        at org.bukkit.configuration.file.YamlConfiguration.loadFromString(YamlConfiguration.java:106) ~[purpur-api-1.19.3-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.configuration.file.FileConfiguration.load(FileConfiguration.java:160) ~[purpur-api-1.19.3-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.configuration.file.FileConfiguration.load(FileConfiguration.java:128) ~[purpur-api-1.19.3-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.configuration.file.YamlConfiguration.loadConfiguration(YamlConfiguration.java:306) ~[purpur-api-1.19.3-R0.1-SNAPSHOT.jar:?]
        at com.booksaw.betterTeams.team.storage.storageManager.SeparatedYamlStorageManager.sortTeamsByScore(SeparatedYamlStorageManager.java:220) ~[BetterTeams-4.5.0.jar:?]
        at com.booksaw.betterTeams.commands.team.TopCommand$1.run(TopCommand.java:34) ~[BetterTeams-4.5.0.jar:?]
        at org.bukkit.craftbukkit.v1_19_R2.scheduler.CraftTask.run(CraftTask.java:101) ~[purpur-1.19.3.jar:git-Purpur-1888]
        at org.bukkit.craftbukkit.v1_19_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[purpur-1.19.3.jar:git-Purpur-1888]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[purpur-1.19.3.jar:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: org.yaml.snakeyaml.reader.ReaderException: special characters are not allowed
        at org.yaml.snakeyaml.reader.StreamReader.update(StreamReader.java:204) ~[snakeyaml-1.33.jar:?]
        at org.yaml.snakeyaml.reader.StreamReader.ensureEnoughData(StreamReader.java:169) ~[snakeyaml-1.33.jar:?]
        at org.yaml.snakeyaml.reader.StreamReader.ensureEnoughData(StreamReader.java:164) ~[snakeyaml-1.33.jar:?]
        at org.yaml.snakeyaml.reader.StreamReader.peek(StreamReader.java:119) ~[snakeyaml-1.33.jar:?]
        at org.yaml.snakeyaml.scanner.ScannerImpl.scanToNextToken(ScannerImpl.java:1229) ~[snakeyaml-1.33.jar:?]
        at org.yaml.snakeyaml.scanner.ScannerImpl.fetchMoreTokens(ScannerImpl.java:345) ~[snakeyaml-1.33.jar:?]
        at org.yaml.snakeyaml.scanner.ScannerImpl.checkToken(ScannerImpl.java:263) ~[snakeyaml-1.33.jar:?]
        at org.yaml.snakeyaml.parser.ParserImpl$ParseImplicitDocumentStart.produce(ParserImpl.java:235) ~[snakeyaml-1.33.jar:?]
        at org.yaml.snakeyaml.parser.ParserImpl.peekEvent(ParserImpl.java:185) ~[snakeyaml-1.33.jar:?]
        at org.yaml.snakeyaml.parser.ParserImpl.checkEvent(ParserImpl.java:175) ~[snakeyaml-1.33.jar:?]
        at org.yaml.snakeyaml.composer.Composer.getSingleNode(Composer.java:159) ~[snakeyaml-1.33.jar:?]
        at org.yaml.snakeyaml.Yaml.compose(Yaml.java:559) ~[snakeyaml-1.33.jar:?]
        at org.bukkit.configuration.file.YamlConfiguration.loadFromString(YamlConfiguration.java:104) ~[purpur-api-1.19.3-R0.1-SNAPSHOT.jar:?]
        ... 11 more
```

### Output of /teama version

[22:20:06 INFO]: » Data Storage Method: com.booksaw.betterTeams.team.storage.storageManager.SeparatedYamlStorageManager.
[22:20:06 INFO]: » Server's Minecraft version: git-Purpur-1888 (MC: 1.19.3).
[22:20:06 INFO]: » Current BetterTeams version that is installed is v4.5.0.

### Additional Information

I understand that this issue doesn't have much to work with in terms of information regarding reproduction of this issue, but I will try update this issue once I get knowledge of other ways to reproduce this.

**Comment by RealTriassic** [comment]
Relevant configuration options:
```
bannedChars: ',.!"�$%^&*()[]{};:#~\|`�'
allowedChars: ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789
```

**Comment by booksaw** [comment]
I am thus far unable to reproduce this bug. I have attempted to add a error message which is more informative so if you could share that error message after you update to the next version, it will help to narrow down the error
