### ISSUE TITLE
[BUG] Files in teaminfo folder which are not .yamls break stuff 

### ISSUE THREAD

**Issue by booksaw** [booksaw/BetterTeams#400]
### What is the bug?

.

### Expected Behaviour

.

### How to Reproduce

.

### Error message

something causes this as well
[12:56:18 INFO]: Triassic issued server command: /clan top
[12:56:18 WARN]: [BetterTeams] Plugin BetterTeams v4.6.1 generated an exception while executing task 2739550
java.lang.NullPointerException: Cannot invoke "String.equals(Object)" because "teams[i]" is null
        at com.booksaw.betterTeams.commands.team.TopCommand$1.run(TopCommand.java:50) ~[BetterTeams-4.6.1.jar:?]
        at org.bukkit.craftbukkit.v1_19_R2.scheduler.CraftTask.run(CraftTask.java:101) ~[purpur-1.19.3.jar:git-Purpur-1906]
        at org.bukkit.craftbukkit.v1_19_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[purpur-1.19.3.jar:git-Purpur-1906]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[purpur-1.19.3.jar:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]

### Output of /teama version

.

**Comment by booksaw** [comment]
This bug has been fixed and the patch will be included in the next update. Thank you for reporting.
