### ISSUE TITLE
[BUG] is registered to be in a team, yet has no playerdata associated with that team

### ISSUE THREAD

**Issue by homerek111** [booksaw/BetterTeams#403]
### What is the bug?

some players are losing their team tags before nickname and when and have errors on joining...

### Expected Behaviour

teams working properly

### How to Reproduce

start the server and it just happens on some players

### Error message

[bugreport.txt](https://github.com/booksaw/BetterTeams/files/10674267/bugreport.txt)

### Output of /teama version

[11:57:49 INFO]: [Drużyna] Storage Method: com.booksaw.betterTeams.team.storage.storageManager.SeparatedYamlStorageManager
[11:57:49 INFO]: [Drużyna] Minecraft Version: git-Paper-307 (MC: 1.19.2)
[11:57:49 INFO]: [Drużyna] Wersja pluginu: 4.6.1

### Additional Information

Something went wrong while executing the command, please report this https://github.com/booksaw/BetterTeams/issues/new/choose

**Comment by booksaw** [comment]
Stack trace of another version of error: 

[17:31:10] [Craft Scheduler Thread - 1/ERROR]: Something went wrong while executing the command, please report this https://github.com/booksaw/BetterTeams/issues/new/choose
[17:31:10] [Craft Scheduler Thread - 1/WARN]: java.lang.NullPointerException
[17:31:10] [Craft Scheduler Thread - 1/WARN]:   at java.base/java.util.Objects.requireNonNull(Objects.java:208)
[17:31:10] [Craft Scheduler Thread - 1/WARN]:   at com.booksaw.betterTeams.commands.team.KickCommand.onCommand(KickCommand.java:43)
[17:31:10] [Craft Scheduler Thread - 1/WARN]:   at com.booksaw.betterTeams.commands.presets.TeamSubCommand.onCommand(TeamSubCommand.java:39)
[17:31:10] [Craft Scheduler Thread - 1/WARN]:   at com.booksaw.betterTeams.commands.ParentCommand.onCommand(ParentCommand.java:135)
[17:31:10] [Craft Scheduler Thread - 1/WARN]:   at com.booksaw.betterTeams.BooksawCommand.runExecution(BooksawCommand.java:72)
[17:31:10] [Craft Scheduler Thread - 1/WARN]:   at com.booksaw.betterTeams.BooksawCommand.lambda$execute$0(BooksawCommand.java:59)
[17:31:10] [Craft Scheduler Thread - 1/WARN]:   at org.bukkit.craftbukkit.v1_19_R2.scheduler.CraftTask.run(CraftTask.java:82)
[17:31:10] [Craft Scheduler Thread - 1/WARN]:   at org.bukkit.craftbukkit.v1_19_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54)
[17:31:10] [Craft Scheduler Thread - 1/WARN]:   at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[17:31:10] [Craft Scheduler Thread - 1/WARN]:   at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[17:31:10] [Craft Scheduler Thread - 1/WARN]:   at java.base/java.lang.Thread.run(Thread.java:833)

**Comment by booksaw** [comment]
To both, update to the latest version, set `rebuildLookups` to true in `config.yml` and restart your server, this should fix the problem. Please open another issue if this does not fix your problems referencing this one.
