### ISSUE TITLE
[BUG] error msg with 4.6.2

### ISSUE THREAD

**Issue by adalmo** [booksaw/BetterTeams#411]
### What is the bug?

[09:05:48 WARN]: [BetterTeams] Plugin BetterTeams v4.6.2 generated an exception while executing task 641099
java.lang.NullPointerException: Cannot invoke "String.equals(Object)" because "teams[i]" is null
        at com.booksaw.betterTeams.commands.team.BaltopCommand$1.run(BaltopCommand.java:50) ~[BetterTeams.jar:?]
        at org.bukkit.craftbukkit.v1_19_R2.scheduler.CraftTask.run(CraftTask.java:101) ~[purpur-1.19.3.jar:git-Purpur-1916]
        at org.bukkit.craftbukkit.v1_19_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[purpur-1.19.3.jar:git-Purpur-1916]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[purpur-1.19.3.jar:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]

### Expected Behaviour

[09:05:10 INFO]: CalledMusic5714 issued server command: /team neutral 한국
[09:05:41 INFO]: CalledMusic5714 issued server command: /team baltop
[09:05:48 WARN]: [BetterTeams] Plugin BetterTeams v4.6.2 generated an exception while executing task 641099
java.lang.NullPointerException: Cannot invoke "String.equals(Object)" because "teams[i]" is null
        at com.booksaw.betterTeams.commands.team.BaltopCommand$1.run(BaltopCommand.java:50) ~[BetterTeams.jar:?]
        at org.bukkit.craftbukkit.v1_19_R2.scheduler.CraftTask.run(CraftTask.java:101) ~[purpur-1.19.3.jar:git-Purpur-1916]
        at org.bukkit.craftbukkit.v1_19_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[purpur-1.19.3.jar:git-Purpur-1916]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[purpur-1.19.3.jar:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]

### How to Reproduce

[09:05:10 INFO]: CalledMusic5714 issued server command: /team neutral 한국
[09:05:41 INFO]: CalledMusic5714 issued server command: /team baltop

### Error message

[09:05:48 WARN]: [BetterTeams] Plugin BetterTeams v4.6.2 generated an exception while executing task 641099
java.lang.NullPointerException: Cannot invoke "String.equals(Object)" because "teams[i]" is null
        at com.booksaw.betterTeams.commands.team.BaltopCommand$1.run(BaltopCommand.java:50) ~[BetterTeams.jar:?]
        at org.bukkit.craftbukkit.v1_19_R2.scheduler.CraftTask.run(CraftTask.java:101) ~[purpur-1.19.3.jar:git-Purpur-1916]
        at org.bukkit.craftbukkit.v1_19_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[purpur-1.19.3.jar:git-Purpur-1916]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[purpur-1.19.3.jar:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]

### Output of /teama version

4.6.2

**Comment by booksaw** [comment]
This issue is being closed for inactivity. If you are still having problems feel free to open a new issue linking this one, make sure you answer any questions asked in the new issue.
