### ISSUE TITLE
[BUG] java.lang.ClassCastException

### ISSUE THREAD

**Issue by adalmo** [booksaw/BetterTeams#412]
### What is the bug?

[12:53:26 ERROR]: Something went wrong while executing the command, please report this https://github.com/booksaw/BetterTeams/issues/new/choose
[12:53:26 WARN]: java.lang.ClassCastException: class org.bukkit.craftbukkit.v1_19_R2.block.CraftBlockState cannot be cast to class org.bukkit.block.Chest (org.bukkit.craftbukkit.v1_19_R2.block.CraftBlockState and org.bukkit.block.Chest are in unnamed module of loader java.net.URLClassLoader @ba8a1dc)
[12:53:26 WARN]:        at BetterTeams.jar//com.booksaw.betterTeams.team.TeamManager.getClaimingLocation(TeamManager.java:272)
[12:53:26 WARN]:        at BetterTeams.jar//com.booksaw.betterTeams.Team.getClaimingLocation(Team.java:112)
[12:53:26 WARN]:        at BetterTeams.jar//com.booksaw.betterTeams.commands.team.chest.ChestRemoveCommand.onCommand(ChestRemoveCommand.java:24)
[12:53:26 WARN]:        at BetterTeams.jar//com.booksaw.betterTeams.commands.presets.TeamSubCommand.onCommand(TeamSubCommand.java:39)
[12:53:26 WARN]:        at BetterTeams.jar//com.booksaw.betterTeams.commands.ParentCommand.onCommand(ParentCommand.java:135)
[12:53:26 WARN]:        at BetterTeams.jar//com.booksaw.betterTeams.commands.ParentCommand.onCommand(ParentCommand.java:82)
[12:53:26 WARN]:        at BetterTeams.jar//com.booksaw.betterTeams.commands.ParentCommand.onCommand(ParentCommand.java:135)
[12:53:26 WARN]:        at BetterTeams.jar//com.booksaw.betterTeams.BooksawCommand.runExecution(BooksawCommand.java:72)
[12:53:26 WARN]:        at BetterTeams.jar//com.booksaw.betterTeams.BooksawCommand.execute(BooksawCommand.java:62)
[12:53:26 WARN]:        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:168)
[12:53:26 WARN]:        at org.bukkit.craftbukkit.v1_19_R2.CraftServer.dispatchCommand(CraftServer.java:926)
[12:53:26 WARN]:        at org.bukkit.craftbukkit.v1_19_R2.command.BukkitCommandWrapper.run(BukkitCommandWrapper.java:64)
[12:53:26 WARN]:        at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:264)
[12:53:26 WARN]:        at net.minecraft.commands.CommandDispatcher.performCommand(CommandDispatcher.java:324)
[12:53:26 WARN]:        at net.minecraft.commands.CommandDispatcher.a(CommandDispatcher.java:308)
[12:53:26 WARN]:        at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:2379)
[12:53:26 WARN]:        at net.minecraft.server.network.PlayerConnection.lambda$handleChatCommand$21(PlayerConnection.java:2339)
[12:53:26 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.b(IAsyncTaskHandler.java:59)
[12:53:26 WARN]:        at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)[12:53:26 WARN]:        at net.minecraft.server.TickTask.run(TickTask.java:18)
[12:53:26 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.d(IAsyncTaskHandler.java:153)
[12:53:26 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.d(IAsyncTaskHandlerReentrant.java:24)
[12:53:26 WARN]:        at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1368)
[12:53:26 WARN]:        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:197)
[12:53:26 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.x(IAsyncTaskHandler.java:126)
[12:53:26 WARN]:        at net.minecraft.server.MinecraftServer.bh(MinecraftServer.java:1345)
[12:53:26 WARN]:        at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1338)
[12:53:26 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.c(IAsyncTaskHandler.java:136)
[12:53:26 WARN]:        at net.minecraft.server.MinecraftServer.i_(MinecraftServer.java:1316)
[12:53:26 WARN]:        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1204)
[12:53:26 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:321)
[12:53:26 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)

### Expected Behaviour

it makes error

### How to Reproduce

idk what happend

### Error message

[12:53:26 ERROR]: Something went wrong while executing the command, please report this https://github.com/booksaw/BetterTeams/issues/new/choose
[12:53:26 WARN]: java.lang.ClassCastException: class org.bukkit.craftbukkit.v1_19_R2.block.CraftBlockState cannot be cast to class org.bukkit.block.Chest (org.bukkit.craftbukkit.v1_19_R2.block.CraftBlockState and org.bukkit.block.Chest are in unnamed module of loader java.net.URLClassLoader @ba8a1dc)
[12:53:26 WARN]:        at BetterTeams.jar//com.booksaw.betterTeams.team.TeamManager.getClaimingLocation(TeamManager.java:272)
[12:53:26 WARN]:        at BetterTeams.jar//com.booksaw.betterTeams.Team.getClaimingLocation(Team.java:112)
[12:53:26 WARN]:        at BetterTeams.jar//com.booksaw.betterTeams.commands.team.chest.ChestRemoveCommand.onCommand(ChestRemoveCommand.java:24)
[12:53:26 WARN]:        at BetterTeams.jar//com.booksaw.betterTeams.commands.presets.TeamSubCommand.onCommand(TeamSubCommand.java:39)
[12:53:26 WARN]:        at BetterTeams.jar//com.booksaw.betterTeams.commands.ParentCommand.onCommand(ParentCommand.java:135)
[12:53:26 WARN]:        at BetterTeams.jar//com.booksaw.betterTeams.commands.ParentCommand.onCommand(ParentCommand.java:82)
[12:53:26 WARN]:        at BetterTeams.jar//com.booksaw.betterTeams.commands.ParentCommand.onCommand(ParentCommand.java:135)
[12:53:26 WARN]:        at BetterTeams.jar//com.booksaw.betterTeams.BooksawCommand.runExecution(BooksawCommand.java:72)
[12:53:26 WARN]:        at BetterTeams.jar//com.booksaw.betterTeams.BooksawCommand.execute(BooksawCommand.java:62)
[12:53:26 WARN]:        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:168)
[12:53:26 WARN]:        at org.bukkit.craftbukkit.v1_19_R2.CraftServer.dispatchCommand(CraftServer.java:926)
[12:53:26 WARN]:        at org.bukkit.craftbukkit.v1_19_R2.command.BukkitCommandWrapper.run(BukkitCommandWrapper.java:64)
[12:53:26 WARN]:        at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:264)
[12:53:26 WARN]:        at net.minecraft.commands.CommandDispatcher.performCommand(CommandDispatcher.java:324)
[12:53:26 WARN]:        at net.minecraft.commands.CommandDispatcher.a(CommandDispatcher.java:308)
[12:53:26 WARN]:        at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:2379)
[12:53:26 WARN]:        at net.minecraft.server.network.PlayerConnection.lambda$handleChatCommand$21(PlayerConnection.java:2339)
[12:53:26 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.b(IAsyncTaskHandler.java:59)
[12:53:26 WARN]:        at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)[12:53:26 WARN]:        at net.minecraft.server.TickTask.run(TickTask.java:18)
[12:53:26 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.d(IAsyncTaskHandler.java:153)
[12:53:26 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.d(IAsyncTaskHandlerReentrant.java:24)
[12:53:26 WARN]:        at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1368)
[12:53:26 WARN]:        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:197)
[12:53:26 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.x(IAsyncTaskHandler.java:126)
[12:53:26 WARN]:        at net.minecraft.server.MinecraftServer.bh(MinecraftServer.java:1345)
[12:53:26 WARN]:        at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1338)
[12:53:26 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.c(IAsyncTaskHandler.java:136)
[12:53:26 WARN]:        at net.minecraft.server.MinecraftServer.i_(MinecraftServer.java:1316)
[12:53:26 WARN]:        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1204)
[12:53:26 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:321)
[12:53:26 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)

### Output of /teama version

[12:55:12 INFO]: [Teams] Storage Method: com.booksaw.betterTeams.team.storage.storageManager.SeparatedYamlStorageManager
[12:55:12 INFO]: [Teams] Minecraft Version: git-Purpur-1923 (MC: 1.19.3)
[12:55:12 INFO]: [Teams] Language Selected: messages
[12:55:12 INFO]: [Teams] Current plugin version: 4.6.2

**Comment by booksaw** [comment]
This bug has been fixed and the patch will be included in the next update. Thank you for reporting.
