### ISSUE TITLE
[BUG] java.lang.NullPointerException: null

### ISSUE THREAD

**Issue by HowToPlayVN** [booksaw/BetterTeams#415]
### What is the bug?

I got a warning message when using team home command.

### Expected Behaviour

Do you think this is a bug or not?

### How to Reproduce

1. Run /team home

### Error message

[BetterTeams] Task #115001 for BetterTeams v4.6.2 generated an exception
java.lang.NullPointerException: null
	at com.booksaw.betterTeams.PlayerTeleport.runTp(PlayerTeleport.java:66) ~[BetterTeams.jar:?]
	at org.bukkit.craftbukkit.v1_19_R2.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.19.3.jar:git-Paper-445]
	at org.bukkit.craftbukkit.v1_19_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483) ~[paper-1.19.3.jar:git-Paper-445]
	at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1473) ~[paper-1.19.3.jar:git-Paper-445]
	at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:447) ~[paper-1.19.3.jar:git-Paper-445]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1397) ~[paper-1.19.3.jar:git-Paper-445]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1173) ~[paper-1.19.3.jar:git-Paper-445]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316) ~[paper-1.19.3.jar:git-Paper-445]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]

### Output of /teama version

[16:47:20] [Craft Scheduler Thread - 84 - BetterTeams/INFO]: [BetterTeams] Storage Method: com.booksaw.betterTeams.team.storage.storageManager.SeparatedYamlStorageManager
[16:47:20] [Craft Scheduler Thread - 84 - BetterTeams/INFO]: [BetterTeams] Minecraft Version: git-Paper-445 (MC: 1.19.3)
[16:47:20] [Craft Scheduler Thread - 84 - BetterTeams/INFO]: [BetterTeams] Language Selected: messages
[16:47:20] [Craft Scheduler Thread - 84 - BetterTeams/INFO]: [BetterTeams] Current plugin version: 4.6.2

### Additional Information

I'm running Paper 1.19.3 (445)

**Comment by booksaw** [comment]
This bug has been fixed and the patch will be included in the next update. Thank you for reporting.
