### ISSUE TITLE
[BUG] Task #445813 for BetterTeams v4.6.3 generated an exception

### ISSUE THREAD

**Issue by adalmo** [booksaw/BetterTeams#419]
### What is the bug?

[00:06:57 WARN]: [BetterTeams] Task #445813 for BetterTeams v4.6.3 generated an exception
java.lang.IllegalArgumentException: Cannot measure distance between world and world_nether
        at org.bukkit.Location.distanceSquared(Location.java:510) ~[purpur-api-1.19.3-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.Location.distance(Location.java:493) ~[purpur-api-1.19.3-R0.1-SNAPSHOT.jar:?]
        at com.booksaw.betterTeams.PlayerTeleport.canTp(PlayerTeleport.java:91) ~[BetterTeams.jar:?]
        at com.booksaw.betterTeams.PlayerTeleport.lambda$new$0(PlayerTeleport.java:57) ~[BetterTeams.jar:?]
        at org.bukkit.craftbukkit.v1_19_R2.scheduler.CraftTask.run(CraftTask.java:101) ~[purpur-1.19.3.jar:git-Purpur-1933]
        at org.bukkit.craftbukkit.v1_19_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483) ~[purpur-1.19.3.jar:git-Purpur-1933]
        at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1500) ~[purpur-1.19.3.jar:git-Purpur-1933]
        at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:488) ~[purpur-1.19.3.jar:git-Purpur-1933]
        at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1424) ~[purpur-1.19.3.jar:git-Purpur-1933]
        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1194) ~[purpur-1.19.3.jar:git-Purpur-1933]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:321) ~[purpur-1.19.3.jar:git-Purpur-1933]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]

### Expected Behaviour

[00:06:57 WARN]: [BetterTeams] Task #445813 for BetterTeams v4.6.3 generated an exception
java.lang.IllegalArgumentException: Cannot measure distance between world and world_nether
        at org.bukkit.Location.distanceSquared(Location.java:510) ~[purpur-api-1.19.3-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.Location.distance(Location.java:493) ~[purpur-api-1.19.3-R0.1-SNAPSHOT.jar:?]
        at com.booksaw.betterTeams.PlayerTeleport.canTp(PlayerTeleport.java:91) ~[BetterTeams.jar:?]
        at com.booksaw.betterTeams.PlayerTeleport.lambda$new$0(PlayerTeleport.java:57) ~[BetterTeams.jar:?]
        at org.bukkit.craftbukkit.v1_19_R2.scheduler.CraftTask.run(CraftTask.java:101) ~[purpur-1.19.3.jar:git-Purpur-1933]
        at org.bukkit.craftbukkit.v1_19_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483) ~[purpur-1.19.3.jar:git-Purpur-1933]
        at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1500) ~[purpur-1.19.3.jar:git-Purpur-1933]
        at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:488) ~[purpur-1.19.3.jar:git-Purpur-1933]
        at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1424) ~[purpur-1.19.3.jar:git-Purpur-1933]
        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1194) ~[purpur-1.19.3.jar:git-Purpur-1933]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:321) ~[purpur-1.19.3.jar:git-Purpur-1933]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]

### How to Reproduce

[00:06:57 WARN]: [BetterTeams] Task #445813 for BetterTeams v4.6.3 generated an exception
java.lang.IllegalArgumentException: Cannot measure distance between world and world_nether
        at org.bukkit.Location.distanceSquared(Location.java:510) ~[purpur-api-1.19.3-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.Location.distance(Location.java:493) ~[purpur-api-1.19.3-R0.1-SNAPSHOT.jar:?]
        at com.booksaw.betterTeams.PlayerTeleport.canTp(PlayerTeleport.java:91) ~[BetterTeams.jar:?]
        at com.booksaw.betterTeams.PlayerTeleport.lambda$new$0(PlayerTeleport.java:57) ~[BetterTeams.jar:?]
        at org.bukkit.craftbukkit.v1_19_R2.scheduler.CraftTask.run(CraftTask.java:101) ~[purpur-1.19.3.jar:git-Purpur-1933]
        at org.bukkit.craftbukkit.v1_19_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483) ~[purpur-1.19.3.jar:git-Purpur-1933]
        at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1500) ~[purpur-1.19.3.jar:git-Purpur-1933]
        at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:488) ~[purpur-1.19.3.jar:git-Purpur-1933]
        at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1424) ~[purpur-1.19.3.jar:git-Purpur-1933]
        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1194) ~[purpur-1.19.3.jar:git-Purpur-1933]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:321) ~[purpur-1.19.3.jar:git-Purpur-1933]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]

### Error message

[00:06:57 WARN]: [BetterTeams] Task #445813 for BetterTeams v4.6.3 generated an exception
java.lang.IllegalArgumentException: Cannot measure distance between world and world_nether
        at org.bukkit.Location.distanceSquared(Location.java:510) ~[purpur-api-1.19.3-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.Location.distance(Location.java:493) ~[purpur-api-1.19.3-R0.1-SNAPSHOT.jar:?]
        at com.booksaw.betterTeams.PlayerTeleport.canTp(PlayerTeleport.java:91) ~[BetterTeams.jar:?]
        at com.booksaw.betterTeams.PlayerTeleport.lambda$new$0(PlayerTeleport.java:57) ~[BetterTeams.jar:?]
        at org.bukkit.craftbukkit.v1_19_R2.scheduler.CraftTask.run(CraftTask.java:101) ~[purpur-1.19.3.jar:git-Purpur-1933]
        at org.bukkit.craftbukkit.v1_19_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483) ~[purpur-1.19.3.jar:git-Purpur-1933]
        at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1500) ~[purpur-1.19.3.jar:git-Purpur-1933]
        at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:488) ~[purpur-1.19.3.jar:git-Purpur-1933]
        at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1424) ~[purpur-1.19.3.jar:git-Purpur-1933]
        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1194) ~[purpur-1.19.3.jar:git-Purpur-1933]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:321) ~[purpur-1.19.3.jar:git-Purpur-1933]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]

### Output of /teama version

[01:04:16 INFO]: [Teams] Storage Method: com.booksaw.betterTeams.team.storage.storageManager.SeparatedYamlStorageManager
[01:04:16 INFO]: [Teams] Minecraft Version: git-Purpur-1933 (MC: 1.19.3)
[01:04:16 INFO]: [Teams] Language Selected: messages
[01:04:16 INFO]: [Teams] Current plugin version: 4.6.3

**Comment by booksaw** [comment]
This bug has been fixed and the patch will be included in the next update. Thank you for reporting.
