### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by DAKUsir** [booksaw/BetterTeams#424]
### What is the bug?

players are unable to leave team.
they are saying no perms for team command and the message is saying to tellt he owner.

### Expected Behaviour

i think it if players can use the commands it will be normal.

### How to Reproduce

auusume a player joined the team
if he or she runs /team leave the error appears

### Error message

[16:22:13 INFO]: gamertamer127 issued server command: /team leave
[16:22:13 ERROR]: Something went wrong while executing the command, please report this https://github.com/booksaw/BetterTeams/issues/new/choose
[16:22:13 WARN]: java.lang.IllegalStateException: Unregistered scoreboard component
[16:22:13 WARN]: 	at org.bukkit.craftbukkit.v1_19_R2.scoreboard.CraftTeam.checkState(CraftTeam.java:403)
[16:22:13 WARN]: 	at org.bukkit.craftbukkit.v1_19_R2.scoreboard.CraftTeam.removeEntry(CraftTeam.java:261)
[16:22:13 WARN]: 	at BetterTeams.jar//com.booksaw.betterTeams.events.MCTeamManagement.remove(MCTeamManagement.java:110)
[16:22:13 WARN]: 	at BetterTeams.jar//com.booksaw.betterTeams.events.MCTeamManagement.remove(MCTeamManagement.java:91)
[16:22:13 WARN]: 	at BetterTeams.jar//com.booksaw.betterTeams.team.MemberListComponent.remove(MemberListComponent.java:63)
[16:22:13 WARN]: 	at BetterTeams.jar//com.booksaw.betterTeams.Team.removePlayer(Team.java:662)
[16:22:13 WARN]: 	at BetterTeams.jar//com.booksaw.betterTeams.Team.removePlayer(Team.java:648)
[16:22:13 WARN]: 	at BetterTeams.jar//com.booksaw.betterTeams.commands.team.LeaveCommand.onCommand(LeaveCommand.java:26)
[16:22:13 WARN]: 	at BetterTeams.jar//com.booksaw.betterTeams.commands.presets.TeamSubCommand.onCommand(TeamSubCommand.java:39)
[16:22:13 WARN]: 	at BetterTeams.jar//com.booksaw.betterTeams.commands.ParentCommand.onCommand(ParentCommand.java:135)
[16:22:13 WARN]: 	at BetterTeams.jar//com.booksaw.betterTeams.BooksawCommand.runExecution(BooksawCommand.java:72)
[16:22:13 WARN]: 	at BetterTeams.jar//com.booksaw.betterTeams.BooksawCommand.lambda$execute$0(BooksawCommand.java:59)
[16:22:13 WARN]: 	at org.bukkit.craftbukkit.v1_19_R2.scheduler.CraftTask.run(CraftTask.java:101)
[16:22:13 WARN]: 	at org.bukkit.craftbukkit.v1_19_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57)
[16:22:13 WARN]: 	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[16:22:13 WARN]: 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
[16:22:13 WARN]: 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
[16:22:13 WARN]: 	at java.base/java.lang.Thread.run(Unknown Source)

### Output of /teama version

[16:23:34 INFO]: /teama echest <team> - View your teams ender chest
[16:23:34 INFO]: /teama color <team> <color code> - Change your teams color
[16:23:34 INFO]: /teama teleport <team> [x|player] [y] [z] [yaw] [pitch] - Teleports the specified team to the specified location (or executor's location)
[16:23:34 INFO]: /teama description <team> <description> - View and change your team's description
[16:23:34 INFO]: /teama setwarp <team> <name> [password] - Set a warp for the rest of your team
[16:23:34 INFO]: /teama purge  - Reset the score for all teams
[16:23:34 INFO]: /teama title <player> <title> - Change that players title within the team
[16:23:34 INFO]: /teama setrank <team> <rank> - Set the level of the team specified
[16:23:34 INFO]: /teama promote <player> - Promote the specified player within your team
[16:23:34 INFO]: /teama score  - 
[16:23:34 INFO]: /teama reload  - Reload the BetterTeams configs
[16:23:34 INFO]: /teama leave <player> - Leave your current team
[16:23:34 INFO]: /teama create <team> - Create a team with the specified name
[16:23:34 INFO]: /teama join <team> <player> - Join the specified team
[16:23:34 INFO]: /teama tag <team> <tag> - Set your teams tag
[16:23:34 INFO]: /teama disband <team> - Disband your current team
[16:23:34 INFO]: /teama delwarp <team> <name> - Delete that warp from your team
[16:23:34 INFO]: /teama chest  - 
[16:23:34 INFO]: /teama chatspy  - Spy on messages sent to team chats
[16:23:34 INFO]: /teama version  - Check the plugin version
[16:23:34 INFO]: /teama home <team> - Teleports you to your team's home
[16:23:34 INFO]: /teama help  - View this help page
[16:23:34 INFO]: /teama demote <player> - Demote the specified player within your team
[16:23:34 INFO]: /teama money  - 
[16:23:34 INFO]: /teama name <team> <name> - View and change your team's name
[16:23:34 INFO]: /teama invite <team> <player> - Invite the specified player to your team
[16:23:34 INFO]: /teama open <team> - Toggle if the team is invite only
[16:23:34 INFO]: /teama warp <team> <warp> - Warp to a location set by your team

### Additional Information

https://dump.geysermc.org/FoHSHmbL4EeZDYOJ731eQBuBLlEttGhC

**Comment by booksaw** [comment]
@DAKUsir 
I need the output of the command `/teama version` not the output of the command `/teama`
