### ISSUE TITLE
[BUG]  Unregistered scoreboard component

### ISSUE THREAD

**Issue by KasaiSora** [booksaw/BetterTeams#434]
### What is the bug?

I don't know what the error is, but it told me to paste it here

### Expected Behaviour

N\A

### How to Reproduce

N\A

### Error message

[21:43:43 WARN]: java.lang.IllegalStateException: Unregistered scoreboard component
[21:43:43 WARN]:        at org.bukkit.craftbukkit.v1_19_R2.scoreboard.CraftTeam.checkState(CraftTeam.java:403)
[21:43:43 WARN]:        at org.bukkit.craftbukkit.v1_19_R2.scoreboard.CraftTeam.removeEntry(CraftTeam.java:261)
[21:43:43 WARN]:        at BetterTeams.jar//com.booksaw.betterTeams.events.MCTeamManagement.remove(MCTeamManagement.java:110)
[21:43:43 WARN]:        at BetterTeams.jar//com.booksaw.betterTeams.events.MCTeamManagement.removeAll(MCTeamManagement.java:71)
[21:43:43 WARN]:        at BetterTeams.jar//com.booksaw.betterTeams.Main.onDisable(Main.java:231)
[21:43:43 WARN]:        at BetterTeams.jar//com.booksaw.betterTeams.Main.reload(Main.java:317)
[21:43:43 WARN]:        at BetterTeams.jar//com.booksaw.betterTeams.commands.teama.ReloadTeama.onCommand(ReloadTeama.java:18)
[21:43:43 WARN]:        at BetterTeams.jar//com.booksaw.betterTeams.commands.ParentCommand.onCommand(ParentCommand.java:135)
[21:43:43 WARN]:        at BetterTeams.jar//com.booksaw.betterTeams.BooksawCommand.runExecution(BooksawCommand.java:72)
[21:43:43 WARN]:        at BetterTeams.jar//com.booksaw.betterTeams.BooksawCommand.execute(BooksawCommand.java:62)
[21:43:43 WARN]:        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:155)
[21:43:43 WARN]:        at org.bukkit.craftbukkit.v1_19_R2.CraftServer.dispatchCommand(CraftServer.java:911)
[21:43:43 WARN]:        at org.bukkit.craftbukkit.v1_19_R2.command.BukkitCommandWrapper.run(BukkitCommandWrapper.java:64)
[21:43:43 WARN]:        at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:264)
[21:43:43 WARN]:        at net.minecraft.commands.CommandDispatcher.performCommand(CommandDispatcher.java:316)
[21:43:43 WARN]:        at net.minecraft.commands.CommandDispatcher.a(CommandDispatcher.java:300)
[21:43:43 WARN]:        at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:2288)
[21:43:43 WARN]:        at net.minecraft.server.network.PlayerConnection.lambda$handleChatCommand$20(PlayerConnection.java:2248)
[21:43:43 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.b(IAsyncTaskHandler.java:59)
[21:43:43 WARN]:        at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
[21:43:43 WARN]:        at net.minecraft.server.TickTask.run(TickTask.java:18)
[21:43:43 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.d(IAsyncTaskHandler.java:153)
[21:43:43 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.d(IAsyncTaskHandlerReentrant.java:24)
[21:43:43 WARN]:        at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1341)
[21:43:43 WARN]:        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:197)
[21:43:43 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.x(IAsyncTaskHandler.java:126)
[21:43:43 WARN]:        at net.minecraft.server.MinecraftServer.bh(MinecraftServer.java:1318)
[21:43:43 WARN]:        at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1311)
[21:43:43 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.c(IAsyncTaskHandler.java:136)
[21:43:43 WARN]:        at net.minecraft.server.MinecraftServer.i_(MinecraftServer.java:1289)
[21:43:43 WARN]:        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1177)
[21:43:43 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316)
[21:43:43 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)

### Output of /teama version

N\A

### Additional Information

N\A

**Comment by booksaw** [comment]
Please provide a screenshot of the output of /teama version as this bug may have been fixed in older versions

**Comment by booksaw** [comment]
Refer to final comment of #437 for fix
