### ISSUE TITLE
[BUG] Could not pass event AsyncPlayerChatEvent

### ISSUE THREAD

**Issue by ghost** [booksaw/BetterTeams#436]
### What is the bug?

I'm getting a error from BetterTeams randomly on the console.

### Expected Behaviour

BetterTeams works fine, but it gives an error for some reason.

### How to Reproduce

Not sure how really. We use Bungeecord I guess and the error is randomly sent sometimes. I can't figure out what it means.

### Error message

`Could not pass event AsyncPlayerChatEvent to BetterTeams v4.6.4
java.lang.IllegalStateException: Player *RUST1974 is registered to be in a team, yet has no playerdata associated with that team
        at com.booksaw.betterTeams.events.ChatManagement.onChat(ChatManagement.java:51) ~[BetterTeams.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor416.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:75) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:git-Paper-260]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:670) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.adventure.ChatProcessor.post(ChatProcessor.java:381) ~[paper-1.19.2.jar:git-Paper-260]
        at io.papermc.paper.adventure.ChatProcessor.process(ChatProcessor.java:96) ~[paper-1.19.2.jar:git-Paper-260]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.chat(ServerGamePacketListenerImpl.java:2403) ~[?:?]
        at jdk.internal.reflect.GeneratedMethodAccessor154.invoke(Unknown Source) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
        at com.loohp.interactivechat.utils.PlayerUtils.chatAsPlayer(PlayerUtils.java:130) ~[InteractiveChat-4.2.6.0.jar:?]
        at com.loohp.interactivechat.listeners.RedispatchSignedPacket$1.lambda$onPacketReceiving$4(RedispatchSignedPacket.java:92) ~[InteractiveChat-4.2.6.0.jar:?]
        at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.19.2.jar:git-Paper-260]
        at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[paper-1.19.2.jar:git-Paper-260]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[paper-1.19.2.jar:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]`

### Output of /teama version

[14:12:05 INFO]: [Teams] Storage Method: com.booksaw.betterTeams.team.storage.storageManager.SeparatedYamlStorageManager
[14:12:05 INFO]: [Teams] Minecraft Version: git-Paper-260 (MC: 1.19.2)
[14:12:05 INFO]: [Teams] Language Selected: messages
[14:12:05 INFO]: [Teams] Current plugin version: 4.6.4

**Comment by booksaw** [comment]
Set `rebuildLookups` to true in config.yml and restart your server, let me know if the issue persists once you have done that.

**Comment by booksaw** [comment]
This issue is being closed for inactivity. If you are still having problems feel free to open a new issue linking this one, make sure you answer any questions asked in the new issue.
