### ISSUE TITLE
[BUG] SQL Teams echest console error

### ISSUE THREAD

**Issue by Taneax** [booksaw/BetterTeams#441]
### What is the bug?

title

### Expected Behaviour

e

### How to Reproduce

e

### Error message

https://paste.gg/p/anonymous/ed8ccb2db2f74da88df6762329f9b76a

### Output of /teama version

4.6.4 / latest

### Additional Information

1.19.4 paper server latest

**Comment by booksaw** [comment]
Pasting error here to avoid the paste.gg link expring
```
[Wed 18:36:01 INFO  Server/PlayerConnection] IroniclyIconic issued server command: /team echest
--
  | [Wed 18:36:11 INFO  Server/PlayerConnection] Kloputzer666 issued server command: /belohnung
  |  
  | [Wed 18:36:18 INFO  Server/PlayerConnection] ItzRealFinley issued server command: /sell
  | - [Wed 18:36:19 ERROR Minecraft] Something went wrong while executing SQL
  | - [Wed 18:36:19 ERROR Minecraft] SQL: UPDATE BetterTeams_Team SET echest = "items:
  | '0':
  | ==: org.bukkit.inventory.ItemStack
  | v: 3337
  | type: OAK_PLANKS
  | amount: 45
  | '1':
  | ==: org.bukkit.inventory.ItemStack
  | v: 3337
  | type: VILLAGER_SPAWN_EGG
  | amount: 3
  | '2':
  | ==: org.bukkit.inventory.ItemStack
  | v: 3337
  | type: CRAFTING_TABLE
  | amount: 2
  | '3':
  | ==: org.bukkit.inventory.ItemStack
  | v: 3337
  | type: GOLDEN_CARROT
  | amount: 53
  | '4':
  | ==: org.bukkit.inventory.ItemStack
  | v: 3337
  | type: DIAMOND_PICKAXE
  | meta:
  | ==: ItemMeta
  | meta-type: UNSPECIFIC
  | Damage: 60
  | '5':
  | ==: org.bukkit.inventory.ItemStack
  | v: 3337
  | type: DIAMOND_BOOTS
  | meta:
  | ==: ItemMeta
  | meta-type: ARMOR
  | display-name: '{"extra":[{"bold":true,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"#FFF613","text":"RARE
  | SCHUHE"}],"text":""}'
  | enchants:
  | PROTECTION_FALL: 2
  | PROTECTION_ENVIRONMENTAL: 3
  | DURABILITY: 2
  | Damage: 77
  | '6':
  | ==: org.bukkit.inventory.ItemStack
  | v: 3337
  | type: GOLD_NUGGET
  | amount: 57
  | '7':
  | ==: org.bukkit.inventory.ItemStack
  | v: 3337
  | type: WATER_BUCKET
  | '8':
  | ==: org.bukkit.inventory.ItemStack
  | v: 3337
  | type: FLINT_AND_STEEL
  | meta:
  | ==: ItemMeta
  | meta-type: UNSPECIFIC
  | Damage: 6
  | '9':
  | ==: org.bukkit.inventory.ItemStack
  | v: 3337
  | type: PLAYER_HEAD
  | meta:
  | ==: ItemMeta
  | meta-type: SKULL
  | display-name: '{"extra":[{"bold":false,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"yellow","text":"Abgetrennter
  | Kopf von: "},{"italic":false,"color":"red","text":"IroniclyIconic"}],"text":""}'
  | Damage: 3
  | skull-owner:
  | ==: PlayerProfile
  | uniqueId: 2cbdc282-a10e-491e-8b82-3ac353a80d66
  | name: IroniclyIconic
  | properties:
  | - name: textures
  | value: e
  | - [Wed 18:36:19 ERROR Minecraft] wogICJ0aW1lc3RhbXAiIDogMTY4MzEzMDAzMjE1NCwKICAicHJvZmlsZUlkIiA6ICIyY2JkYzI4MmExMGU0OTFlOGI4MjNhYzM1M2E4MGQ2NiIsCiAgInByb2ZpbGVOYW1lIiA6ICJJcm9uaWNseUljb25pYyIsCiAgInNpZ25hdHVyZVJlcXVpcmVkIiA6IHRydWUsCiAgInRleHR1cmVzIiA6IHsKICAgICJTS0lOIiA6IHsKICAgICAgInVybCIgOiAiaHR0cDovL3RleHR1cmVzLm1pbmVjcmFmdC5uZXQvdGV4dHVyZS80MzhkZWE0ZGE0NGE4ZTg5MzQyMTU3ZmYzZjkxYWUzZTc0NmJhMDU1YzMwYzNkNzFlOWUyZTAyN2I4ZTNlMjdjIiwKICAgICAgIm1ldGFkYXRhIiA6IHsKICAgICAgICAibW9kZWwiIDogInNsaW0iCiAgICAgIH0KICAgIH0KICB9Cn0=
  | signature: OYzsFkiJwOhk7QutFXZbcQQxl3nLK/OrQFXGUwIPstjlgV3sqcfQC3zbqh6zSRhahvCRtxn2gVNaSIvyYHR/HQ03X+wtg/32a10tvyedYWH5WTNRVbVGLiwRC+nefpsr0zpgxQ5rmwHCjTq53v/BIcCAKI+Da9Q14zuwrTO0XsVxYcuJd+kEv34qIzIdX6Se7yMJb686kio9H0362JI7CHUk9W2aVoB8+stqHiZFsjUgKb5w3RkS8OvumGWvig0033KQENjHu3vw9T4vQoZsVuOCw7oWd7AYYPXeQ086V7zTdwM+Rc1ePrX+hGLBjXdwELB5DidYQUOAkjy26CQjtWorxVhrUUNMF1csl6lACZ+zl2ChOz1lSgugQkJMyYEgyLF8/zEaDgVTYK5HYzjuyv0PyeQjf9Z3TQhB720DRWuq+IxKZGEKlQ+ePciwl8RDJrlJXj/B/TAiyb2jWBj0hz5EXGMWWmTIMgWHnRWzkqaTwvb8KEUvsO7YzaxauKPpjYYZnV+4T9bDgwC/BW6p+fJeCoiTfh4JnkDaXk3nygZhcYdmvV+oOZ/mmWjFpGdeQiQ0EROxllEQehjstSBsgv1i9+6kM966uAD9FPqJGL0pBD+tXHHWT+xCOJOG6em0WljEZdNDZtMZzHql9ieuqtWk38Yzq2/T+CsXGUhcR/4=
  | " WHERE teamID LIKE '1d66cf7e-cec3-4aa9-953f-5da39de9dd54';
  | ! [Wed 18:36:19 WARN ] java.sql.SQLSyntaxErrorException: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'extra":[{"bold":true,"italic":false,"underlined":false,"strikethrough":false,...' at line 1
  | ! [Wed 18:36:19 WARN ]     at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:120)
  | ! [Wed 18:36:19 WARN ]     at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122)
  | ! [Wed 18:36:19 WARN ]     at com.mysql.cj.jdbc.ClientPreparedStatement.executeInternal(ClientPreparedStatement.java:916)
  | ! [Wed 18:36:19 WARN ]     at com.mysql.cj.jdbc.ClientPreparedStatement.executeUpdateInternal(ClientPreparedStatement.java:1061)
  | ! [Wed 18:36:19 WARN ]     at com.mysql.cj.jdbc.ClientPreparedStatement.executeUpdateInternal(ClientPreparedStatement.java:1009)
  | ! [Wed 18:36:19 WARN ]     at com.mysql.cj.jdbc.ClientPreparedStatement.executeLargeUpdate(ClientPreparedStatement.java:1320)
  | ! [Wed 18:36:19 WARN ]     at com.mysql.cj.jdbc.ClientPreparedStatement.executeUpdate(ClientPreparedStatement.java:994)
  | ! [Wed 18:36:19 WARN ]     at BetterTeams.jar//com.booksaw.betterTeams.database.api.Database.executeStatement(Database.java:141)
  | ! [Wed 18:36:19 WARN ]     at BetterTeams.jar//com.booksaw.betterTeams.database.BetterTeamsDatabase.updateRecordWhere(BetterTeamsDatabase.java:159)
  | ! [Wed 18:36:19 WARN ]     at BetterTeams.jar//com.booksaw.betterTeams.team.storage.team.SQLTeamStorage.setEchestContents(SQLTeamStorage.java:181)
  | ! [Wed 18:36:19 WARN ]     at BetterTeams.jar//com.booksaw.betterTeams.team.EChestComponent.save(EChestComponent.java:34)
  | ! [Wed 18:36:19 WARN ]     at BetterTeams.jar//com.booksaw.betterTeams.Team.saveEchest(Team.java:1364)
  | ! [Wed 18:36:19 WARN ]     at BetterTeams.jar//com.booksaw.betterTeams.events.InventoryManagement.onClose(InventoryManagement.java:36)
  | ! [Wed 18:36:19 WARN ]     at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor705.execute(Unknown Source)
  | ! [Wed 18:36:19 WARN ]     at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77)
  | ! [Wed 18:36:19 WARN ]     at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:77)
  | ! [Wed 18:36:19 WARN ]     at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
  | ! [Wed 18:36:19 WARN ]     at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54)
  | ! [Wed 18:36:19 WARN ]     at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126)
  | ! [Wed 18:36:19 WARN ]     at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:615)
  | ! [Wed 18:36:19 WARN ]     at org.bukkit.craftbukkit.v1_19_R3.event.CraftEventFactory.handleInventoryCloseEvent(CraftEventFactory.java:1566)
  | ! [Wed 18:36:19 WARN ]     at net.minecraft.server.network.PlayerConnection.handleContainerClose(PlayerConnection.java:2953)
  | ! [Wed 18:36:19 WARN ]     at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:2946)
  | ! [Wed 18:36:19 WARN ]     at net.minecraft.network.protocol.game.PacketPlayInCloseWindow.a(PacketPlayInCloseWindow.java:15)
  | ! [Wed 18:36:19 WARN ]     at net.minecraft.network.protocol.game.PacketPlayInCloseWindow.a(PacketPlayInCloseWindow.java:10)
  | ! [Wed 18:36:19 WARN ]     at net.minecraft.network.protocol.PlayerConnectionUtils.lambda$ensureRunningOnSameThread$0(PlayerConnectionUtils.java:51)
  | ! [Wed 18:36:19 WARN ]     at net.minecraft.server.TickTask.run(TickTask.java:18)
  | ! [Wed 18:36:19 WARN ]     at net.minecraft.util.thread.IAsyncTaskHandler.d(IAsyncTaskHandler.java:153)
  | ! [Wed 18:36:19 WARN ]     at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.d(IAsyncTaskHandlerReentrant.java:24)
  | ! [Wed 18:36:19 WARN ]     at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1342)
  | ! [Wed 18:36:19 WARN ]     at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:197)
  | ! [Wed 18:36:19 WARN ]     at net.minecraft.util.thread.IAsyncTaskHandler.x(IAsyncTaskHandler.java:126)
  | ! [Wed 18:36:19 WARN ]     at net.minecraft.server.MinecraftServer.bi(MinecraftServer.java:1319)
  | ! [Wed 18:36:19 WARN ]     at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1312)
  | ! [Wed 18:36:19 WARN ]     at net.minecraft.util.thread.IAsyncTaskHandler.c(IAsyncTaskHandler.java:136)
  | ! [Wed 18:36:19 WARN ]     at net.minecraft.server.MinecraftServer.i_(MinecraftServer.java:1290)
  | ! [Wed 18:36:19 WARN ]     at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1178)
  | ! [Wed 18:36:19 WARN ]     at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:320)
  | ! [Wed 18:36:19 WARN ]     at java.base/java.lang.Thread.run(Thread.java:833)
```

**Comment by booksaw** [comment]
This bug has been fixed and the patch will be included in the next update. Thank you for reporting.
