### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by weirdtrash2** [booksaw/BetterTeams#443]
### What is the bug?

I type /teama reload and it gives me an error it says please contact ur server owner

### Expected Behaviour

I don't know what causes this bug

### How to Reproduce

/teamadmin reload

### Error message

13:21:32 INFO]: WeirdTrash issued server command: /teamadmin reload
[13:21:32 ERROR]: Something went wrong while executing the command, please report this https://github.com/booksaw/BetterTeams/issues/new/choose
[13:21:32 WARN]: java.lang.IllegalStateException: Unregistered scoreboard component
[13:21:32 WARN]:        at org.bukkit.craftbukkit.v1_19_R3.scoreboard.CraftTeam.checkState(CraftTeam.java:403)
[13:21:32 WARN]:        at org.bukkit.craftbukkit.v1_19_R3.scoreboard.CraftTeam.removeEntry(CraftTeam.java:261)
[13:21:32 WARN]:        at BetterTeams.jar//com.booksaw.betterTeams.events.MCTeamManagement.remove(MCTeamManagement.java:110)
[13:21:32 WARN]:        at BetterTeams.jar//com.booksaw.betterTeams.events.MCTeamManagement.removeAll(MCTeamManagement.java:71)
[13:21:32 WARN]:        at BetterTeams.jar//com.booksaw.betterTeams.Main.onDisable(Main.java:231)
[13:21:32 WARN]:        at BetterTeams.jar//com.booksaw.betterTeams.Main.reload(Main.java:317)
[13:21:32 WARN]:        at BetterTeams.jar//com.booksaw.betterTeams.commands.teama.ReloadTeama.onCommand(ReloadTeama.java:18)
[13:21:32 WARN]:        at BetterTeams.jar//com.booksaw.betterTeams.commands.ParentCommand.onCommand(ParentCommand.java:135)
[13:21:32 WARN]:        at BetterTeams.jar//com.booksaw.betterTeams.BooksawCommand.runExecution(BooksawCommand.java:72)
[13:21:32 WARN]:        at BetterTeams.jar//com.booksaw.betterTeams.BooksawCommand.execute(BooksawCommand.java:62)
[13:21:32 WARN]:        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:155)
[13:21:32 WARN]:        at org.bukkit.craftbukkit.v1_19_R3.CraftServer.dispatchCommand(CraftServer.java:906)
[13:21:32 WARN]:        at org.bukkit.craftbukkit.v1_19_R3.command.BukkitCommandWrapper.run(BukkitCommandWrapper.java:64)
[13:21:32 WARN]:        at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:264)
[13:21:32 WARN]:        at net.minecraft.commands.CommandDispatcher.performCommand(CommandDispatcher.java:322)
[13:21:32 WARN]:        at net.minecraft.commands.CommandDispatcher.a(CommandDispatcher.java:306)
[13:21:32 WARN]:        at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:2280)
[13:21:32 WARN]:        at net.minecraft.server.network.PlayerConnection.lambda$handleChatCommand$20(PlayerConnection.java:2240)
[13:21:32 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.b(IAsyncTaskHandler.java:59)
[13:21:32 WARN]:        at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
[13:21:32 WARN]:        at net.minecraft.server.TickTask.run(TickTask.java:18)
[13:21:32 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.d(IAsyncTaskHandler.java:153)
[13:21:32 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.d(IAsyncTaskHandlerReentrant.java:24)
[13:21:32 WARN]:        at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1341)
[13:21:32 WARN]:        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:197)
[13:21:32 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.x(IAsyncTaskHandler.java:126)
[13:21:32 WARN]:        at net.minecraft.server.MinecraftServer.bi(MinecraftServer.java:1318)
[13:21:32 WARN]:        at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1311)
[13:21:32 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.c(IAsyncTaskHandler.java:136)
[13:21:32 WARN]:        at net.minecraft.server.MinecraftServer.i_(MinecraftServer.java:1289)
[13:21:32 WARN]:        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1177)
[13:21:32 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319)
[13:21:32 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)
[13:22:10 INFO]: WeirdTrash issued server command: /teama reload
[13:22:10 ERROR]: Something went wrong while executing the command, please report this https://github.com/booksaw/BetterTeams/issues/new/choose
[13:22:10 WARN]: java.lang.IllegalStateException: Unregistered scoreboard component
[13:22:10 WARN]:        at org.bukkit.craftbukkit.v1_19_R3.scoreboard.CraftTeam.checkState(CraftTeam.java:403)
[13:22:10 WARN]:        at org.bukkit.craftbukkit.v1_19_R3.scoreboard.CraftTeam.removeEntry(CraftTeam.java:261)
[13:22:10 WARN]:        at BetterTeams.jar//com.booksaw.betterTeams.events.MCTeamManagement.remove(MCTeamManagement.java:110)
[13:22:10 WARN]:        at BetterTeams.jar//com.booksaw.betterTeams.events.MCTeamManagement.removeAll(MCTeamManagement.java:71)
[13:22:10 WARN]:        at BetterTeams.jar//com.booksaw.betterTeams.Main.onDisable(Main.java:231)
[13:22:10 WARN]:        at BetterTeams.jar//com.booksaw.betterTeams.Main.reload(Main.java:317)
[13:22:10 WARN]:        at BetterTeams.jar//com.booksaw.betterTeams.commands.teama.ReloadTeama.onCommand(ReloadTeama.java:18)
[13:22:10 WARN]:        at BetterTeams.jar//com.booksaw.betterTeams.commands.ParentCommand.onCommand(ParentCommand.java:135)
[13:22:10 WARN]:        at BetterTeams.jar//com.booksaw.betterTeams.BooksawCommand.runExecution(BooksawCommand.java:72)
[13:22:10 WARN]:        at BetterTeams.jar//com.booksaw.betterTeams.BooksawCommand.execute(BooksawCommand.java:62)
[13:22:10 WARN]:        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:155)
[13:22:10 WARN]:        at org.bukkit.craftbukkit.v1_19_R3.CraftServer.dispatchCommand(CraftServer.java:906)
[13:22:10 WARN]:        at org.bukkit.craftbukkit.v1_19_R3.command.BukkitCommandWrapper.run(BukkitCommandWrapper.java:64)
[13:22:10 WARN]:        at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:264)
[13:22:10 WARN]:        at net.minecraft.commands.CommandDispatcher.performCommand(CommandDispatcher.java:322)
[13:22:10 WARN]:        at net.minecraft.commands.CommandDispatcher.a(CommandDispatcher.java:306)
[13:22:10 WARN]:        at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:2280)
[13:22:10 WARN]:        at net.minecraft.server.network.PlayerConnection.lambda$handleChatCommand$20(PlayerConnection.java:2240)
[13:22:10 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.b(IAsyncTaskHandler.java:59)
[13:22:10 WARN]:        at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
[13:22:10 WARN]:        at net.minecraft.server.TickTask.run(TickTask.java:18)
[13:22:10 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.d(IAsyncTaskHandler.java:153)
[13:22:10 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.d(IAsyncTaskHandlerReentrant.java:24)
[13:22:10 WARN]:        at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1341)
[13:22:10 WARN]:        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:197)
[13:22:10 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.x(IAsyncTaskHandler.java:126)
[13:22:10 WARN]:        at net.minecraft.server.MinecraftServer.bi(MinecraftServer.java:1318)
[13:22:10 WARN]:        at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1311)
[13:22:10 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.br(IAsyncTaskHandler.java:114)
[13:22:10 WARN]:        at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1427)
[13:22:10 WARN]:        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1173)
[13:22:10 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319)
[13:22:10 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)

### Output of /teama version

Gives me an error idk what's wrong

**Comment by booksaw** [comment]
As stated in #437 at the bottom. please update protocolLib to the dev version and let me know if this fixes your problem.
