### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by GazorHuman** [booksaw/BetterTeams#465]
### What is the bug?

This error happened if someone in the team that wanted to demote a player but the player isn't online aka offline

### Expected Behaviour

Players will be demoted even if they are offline

### How to Reproduce

1. Run /team demote (player) - The player that will be demoted must be offline
2. Error appeared

### Error message

[06:45:27 ERROR]: Something went wrong while executing the command, please report this https://github.com/booksaw/BetterTeams/issues/new/choose
[06:45:27 WARN]: java.lang.ClassCastException: class org.bukkit.craftbukkit.v1_19_R3.CraftOfflinePlayer cannot be cast to class org.bukkit.command.CommandSender (org.bukkit.craftbukkit.v1_19_R3.CraftOfflinePlayer and org.bukkit.command.CommandSender are in unnamed module of loader java.net.URLClassLoader @6996db8)
[06:45:27 WARN]:        at BetterTeams.jar//com.booksaw.betterTeams.commands.team.DemoteCommand.onCommand(DemoteCommand.java:66)
[06:45:27 WARN]:        at BetterTeams.jar//com.booksaw.betterTeams.commands.presets.TeamSubCommand.onCommand(TeamSubCommand.java:39)
[06:45:27 WARN]:        at BetterTeams.jar//com.booksaw.betterTeams.commands.ParentCommand.onCommand(ParentCommand.java:135)
[06:45:27 WARN]:        at BetterTeams.jar//com.booksaw.betterTeams.BooksawCommand.runExecution(BooksawCommand.java:72)
[06:45:27 WARN]:        at BetterTeams.jar//com.booksaw.betterTeams.BooksawCommand.lambda$execute$0(BooksawCommand.java:59)
[06:45:27 WARN]:        at org.bukkit.craftbukkit.v1_19_R3.scheduler.CraftTask.run(CraftTask.java:101)
[06:45:27 WARN]:        at org.bukkit.craftbukkit.v1_19_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57)
[06:45:27 WARN]:        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[06:45:27 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[06:45:27 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[06:45:27 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)

### Output of /teama version

Storage Method: com.booksaw.betterTeams.team.storage.storageManager.SeparatedYamlStorageManager
Minecraft Version: git-Purpur-1985 (MC: 1.19.4)
Language Selected: messages
Current plugin version: 4.6.5

**Comment by booksaw** [comment]
This bug has been fixed and the patch will be included in the next update. Thank you for reporting.
