### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by Atharvanh** [booksaw/BetterTeams#468]
### What is the bug?

Some commands like leave , disband , kick are not working. Also creating some error when a player join or leave

### Expected Behaviour

To fix it 

### How to Reproduce

when using /team leave, kick, disband

### Error message

```issued server command: /team leave RisinGGamerZ
- [Mon 07:03:45 ERROR Minecraft] Something went wrong while executing the command, please report this https://github.com/booksaw/BetterTeams/issues/new/choose
! [Mon 07:03:45 WARN ] java.lang.IllegalStateException: Unregistered scoreboard component
! [Mon 07:03:45 WARN ] 	at org.bukkit.craftbukkit.v1_19_R2.scoreboard.CraftTeam.checkState(CraftTeam.java:403)
! [Mon 07:03:45 WARN ] 	at org.bukkit.craftbukkit.v1_19_R2.scoreboard.CraftTeam.removeEntry(CraftTeam.java:261)
! [Mon 07:03:45 WARN ] 	at BetterTeams.jar//com.booksaw.betterTeams.events.MCTeamManagement.remove(MCTeamManagement.java:110)
! [Mon 07:03:45 WARN ] 	at BetterTeams.jar//com.booksaw.betterTeams.events.MCTeamManagement.remove(MCTeamManagement.java:91)
! [Mon 07:03:45 WARN ] 	at BetterTeams.jar//com.booksaw.betterTeams.team.MemberListComponent.remove(MemberListComponent.java:63)
! [Mon 07:03:45 WARN ] 	at BetterTeams.jar//com.booksaw.betterTeams.Team.removePlayer(Team.java:662)
! [Mon 07:03:45 WARN ] 	at BetterTeams.jar//com.booksaw.betterTeams.Team.removePlayer(Team.java:648)
```diff
! [Mon 07:03:45 WARN ] 	at BetterTeams.jar//com.booksaw.betterTeams.commands.team.LeaveCommand.onCommand(LeaveCommand.java:26)
! [Mon 07:03:45 WARN ] 	at BetterTeams.jar//com.booksaw.betterTeams.commands.presets.TeamSubCommand.onCommand(TeamSubCommand.java:39)
! [Mon 07:03:45 WARN ] 	at BetterTeams.jar//com.booksaw.betterTeams.commands.ParentCommand.onCommand(ParentCommand.java:135)
! [Mon 07:03:45 WARN ] 	at BetterTeams.jar//com.booksaw.betterTeams.BooksawCommand.runExecution(BooksawCommand.java:72)
! [Mon 07:03:45 WARN ] 	at BetterTeams.jar//com.booksaw.betterTeams.BooksawCommand.lambda$execute$0(BooksawCommand.java:59)
! [Mon 07:03:45 WARN ] 	at org.bukkit.craftbukkit.v1_19_R2.scheduler.CraftTask.run(CraftTask.java:101)
! [Mon 07:03:45 WARN ] 	at org.bukkit.craftbukkit.v1_19_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57)
! [Mon 07:03:45 WARN ] 	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
! [Mon 07:03:45 WARN ] 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
! [Mon 07:03:45 WARN ] 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
! [Mon 07:03:45 WARN ] 	at java.base/java.lang.Thread.run(Thread.java:833)
```

Join/leave

```d
- [Mon 07:07:18 ERROR Minecraft] Could not pass event PlayerQuitEvent to BetterTeams v4.6.5
java.lang.IllegalStateException: Unregistered scoreboard component
	at org.bukkit.craftbukkit.v1_19_R2.scoreboard.CraftTeam.checkState(CraftTeam.java:403)
	at org.bukkit.craftbukkit.v1_19_R2.scoreboard.CraftTeam.unregister(CraftTeam.java:310)
	at BetterTeams.jar//com.booksaw.betterTeams.team.storage.storageManager.SeparatedYamlStorageManager.unloadTeam(SeparatedYamlStorageManager.java:138)
	at BetterTeams.jar//com.booksaw.betterTeams.team.storage.storageManager.SeparatedYamlStorageManager.onLeave(SeparatedYamlStorageManager.java:424)
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor479.execute(Unknown Source)
	at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77)
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80)
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
	at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54)
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126)
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:615)
	at net.minecraft.server.players.PlayerList.remove(PlayerList.java:578)
	at net.minecraft.server.players.PlayerList.remove(PlayerList.java:563)
	at net.minecraft.server.network.ServerGamePacketListenerImpl.onDisconnect(ServerGamePacketListenerImpl.java:2119)
	at net.minecraft.server.network.ServerGamePacketListenerImpl.onDisconnect(ServerGamePacketListenerImpl.java:2098)
	at net.minecraft.network.Connection.handleDisconnection(Connection.java:777)
	at net.minecraft.server.network.ServerConnectionListener.tick(ServerConnectionListener.java:253)
	at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1565)
	at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:447)
	at net.minecraft.serve
```

### Output of /teama version

[Mon 07:07:13 INFO ] [DN] Storage Method: com.booksaw.betterTeams.team.storage.storageManager.SeparatedYamlStorageManager
  [Mon 07:07:13 INFO ] [DN] Minecraft Version: git-Paper-420 (MC: 1.19.3)
  [Mon 07:07:13 INFO ] [DN] Language Selected: messages
  [Mon 07:07:13 INFO ] [DN] Current plugin version: 4.6.5```

**Comment by booksaw** [comment]
You have a plugin conflict in your server which is causing this. Set `useTeams` to false in config.yml and the error stop.
