### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by JeffreyRCGithub** [booksaw/BetterTeams#475]
### What is the bug?

BetterTeams won't allow you to leave your team.

### Expected Behaviour

BetterTeams was supposed to make the player leave the team when they did /team leave.

### How to Reproduce

1. Get BetterTeams from their SpigotMC page.
2. Bob1 creates a team.
3. Bob2 joins the team.
4. Bob2 wants to leave the team.
5. Bob2 can't leave the team.

### Error message
```
[14:46:02] [Craft Scheduler Thread - 73 - BetterTeams/WARN]: java.lang.IllegalStateException: Unregistered scoreboard component

[14:46:02] [Craft Scheduler Thread - 73 - BetterTeams/WARN]: at org.bukkit.craftbukkit.v1_19_R2.scoreboard.CraftTeam.checkState(CraftTeam.java:403)

[14:46:02] [Craft Scheduler Thread - 73 - BetterTeams/WARN]: at org.bukkit.craftbukkit.v1_19_R2.scoreboard.CraftTeam.removeEntry(CraftTeam.java:261)

[14:46:02] [Craft Scheduler Thread - 73 - BetterTeams/WARN]: at BetterTeams.jar//com.booksaw.betterTeams.events.MCTeamManagement.remove(MCTeamManagement.java:110)

[14:46:02] [Craft Scheduler Thread - 73 - BetterTeams/WARN]: at BetterTeams.jar//com.booksaw.betterTeams.events.MCTeamManagement.remove(MCTeamManagement.java:91)

[14:46:02] [Craft Scheduler Thread - 73 - BetterTeams/WARN]: at BetterTeams.jar//com.booksaw.betterTeams.team.MemberListComponent.remove(MemberListComponent.java:63)

[14:46:02] [Craft Scheduler Thread - 73 - BetterTeams/WARN]: at BetterTeams.jar//com.booksaw.betterTeams.Team.removePlayer(Team.java:662)

[14:46:02] [Craft Scheduler Thread - 73 - BetterTeams/WARN]: at BetterTeams.jar//com.booksaw.betterTeams.Team.removePlayer(Team.java:648)

[14:46:02] [Craft Scheduler Thread - 73 - BetterTeams/WARN]: at BetterTeams.jar//com.booksaw.betterTeams.commands.team.LeaveCommand.onCommand(LeaveCommand.java:26)

[14:46:02] [Craft Scheduler Thread - 73 - BetterTeams/WARN]: at BetterTeams.jar//com.booksaw.betterTeams.commands.presets.TeamSubCommand.onCommand(TeamSubCommand.java:39)

[14:46:02] [Craft Scheduler Thread - 73 - BetterTeams/WARN]: at BetterTeams.jar//com.booksaw.betterTeams.commands.ParentCommand.onCommand(ParentCommand.java:135)

[14:46:02] [Craft Scheduler Thread - 73 - BetterTeams/WARN]: at BetterTeams.jar//com.booksaw.betterTeams.BooksawCommand.runExecution(BooksawCommand.java:72)

[14:46:02] [Craft Scheduler Thread - 73 - BetterTeams/WARN]: at BetterTeams.jar//com.booksaw.betterTeams.BooksawCommand.lambda$execute$0(BooksawCommand.java:59)

[14:46:02] [Craft Scheduler Thread - 73 - BetterTeams/WARN]: at org.bukkit.craftbukkit.v1_19_R2.scheduler.CraftTask.run(CraftTask.java:101)

[14:46:02] [Craft Scheduler Thread - 73 - BetterTeams/WARN]: at org.bukkit.craftbukkit.v1_19_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57)

[14:46:02] [Craft Scheduler Thread - 73 - BetterTeams/WARN]: at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)

[14:46:02] [Craft Scheduler Thread - 73 - BetterTeams/WARN]: at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)

[14:46:02] [Craft Scheduler Thread - 73 - BetterTeams/WARN]: at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)

[14:46:02] [Craft Scheduler Thread - 73 - BetterTeams/WARN]: at java.base/java.lang.Thread.run(Thread.java:833)
```
### Output of /teama version

Sorage Method: com.booksaw.betterTeams.team.storage.storageManager.SeperatedYamlStorageManager 
Minecraft Version: git-Paper-448 (MC: 1.19.3) 
Language Selected: messages 
Current plugin version 4.6.5

**Comment by booksaw** [comment]
This bug has been fixed and the patch will be included in the next update. Thank you for reporting.
