### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by dxnnv** [booksaw/BetterTeams#497]
### What is the bug?

NullPointerException after running /team info <username> but only specifying part of an online player's name, for example for the IGN "dannv" running /team info dan

### Expected Behaviour

Not throw an error

### How to Reproduce

1. Run /team info <part of an online player's name>
```
[07:17:55 INFO]: _Miguel24083643 issued server command: /team info CAM
```
2. Throws error

### Error message

```
[07:17:55 ERROR]: Something went wrong while executing the command, please report this https://github.com/booksaw/BetterTeams/issues/new/choose
[07:17:55 WARN]: java.lang.NullPointerException: Cannot read the array length because the return value of "com.mojang.authlib.yggdrasil.response.ProfileSearchResultsResponse.getProfiles()" is null
[07:17:55 WARN]:        at com.mojang.authlib.yggdrasil.YggdrasilGameProfileRepository.findProfilesByNames(YggdrasilGameProfileRepository.java:59)
[07:17:55 WARN]:        at com.destroystokyo.paper.profile.PaperGameProfileRepository.findProfilesByNames(PaperGameProfileRepository.java:44)
[07:17:55 WARN]:        at net.minecraft.server.players.UserCache.a(UserCache.java:110)
[07:17:55 WARN]:        at net.minecraft.server.players.UserCache.a(UserCache.java:181)
[07:17:55 WARN]:        at org.bukkit.craftbukkit.v1_20_R1.CraftServer.getOfflinePlayer(CraftServer.java:1928)
[07:17:55 WARN]:        at org.bukkit.Bukkit.getOfflinePlayer(Bukkit.java:1283)
[07:17:55 WARN]:        at BetterTeams-4.8.0.jar//com.booksaw.betterTeams.commands.team.InfoCommand.onCommand(InfoCommand.java:142)
[07:17:55 WARN]:        at BetterTeams-4.8.0.jar//com.booksaw.betterTeams.commands.ParentCommand.onCommand(ParentCommand.java:135)
[07:17:55 WARN]:        at BetterTeams-4.8.0.jar//com.booksaw.betterTeams.BooksawCommand.runExecution(BooksawCommand.java:72)
[07:17:55 WARN]:        at BetterTeams-4.8.0.jar//com.booksaw.betterTeams.BooksawCommand.lambda$execute$0(BooksawCommand.java:59)
[07:17:55 WARN]:        at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftTask.run(CraftTask.java:101)
[07:17:55 WARN]:        at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57)
[07:17:55 WARN]:        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[07:17:55 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[07:17:55 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[07:17:55 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)
```

### Output of /teama version

```
[07:18:30 INFO]: TEAMS » Storage Method: com.booksaw.betterTeams.team.storage.storageManager.SQLStorageManager
[07:18:30 INFO]: TEAMS » Minecraft Version: git-Pufferfish-19 (MC: 1.20.1)
[07:18:30 INFO]: TEAMS » Language Selected: messages
[07:18:30 INFO]: TEAMS » Current plugin version: 4.8.0
```

**Comment by booksaw** [comment]
Example of #489, please continue all discussion there to keep all discussion in one place.
