### ISSUE TITLE
/team leave | /team kick not working [BUG] 

### ISSUE THREAD

**Issue by kikMine0** [booksaw/BetterTeams#500]
### What is the bug?

As said in the title /team leave & /team kick  are not working 
Its on a **Aternos PaperMC 1.20.1**
![immagine](https://github.com/booksaw/BetterTeams/assets/143831650/bbda0629-198b-429d-bae5-8adf6a4715a6)

### Expected Behaviour

Make an update with the bug fix

### How to Reproduce

/team leave (or kick)
And then theres the error
![immagine](https://github.com/booksaw/BetterTeams/assets/143831650/adfceb66-4c51-4871-85dd-4c4660a58f15)

### Error message

[18:55:31 ERROR]: Something went wrong while executing the command, please report this https://github.com/booksaw/BetterTeams/issues/new/choose
[18:55:31 WARN]: java.lang.IllegalStateException: Unregistered scoreboard component
[18:55:31 WARN]: 	at com.google.common.base.Preconditions.checkState(Preconditions.java:502)
[18:55:31 WARN]: 	at org.bukkit.craftbukkit.v1_20_R1.scoreboard.CraftTeam.checkState(CraftTeam.java:396)
[18:55:31 WARN]: 	at org.bukkit.craftbukkit.v1_20_R1.scoreboard.CraftTeam.removeEntry(CraftTeam.java:256)
[18:55:31 WARN]: 	at BetterTeams.jar//com.booksaw.betterTeams.events.MCTeamManagement.remove(MCTeamManagement.java:110)
[18:55:31 WARN]: 	at BetterTeams.jar//com.booksaw.betterTeams.events.MCTeamManagement.remove(MCTeamManagement.java:91)
[18:55:31 WARN]: 	at BetterTeams.jar//com.booksaw.betterTeams.team.MemberListComponent.remove(MemberListComponent.java:63)
[18:55:31 WARN]: 	at BetterTeams.jar//com.booksaw.betterTeams.Team.removePlayer(Team.java:662)
[18:55:31 WARN]: 	at BetterTeams.jar//com.booksaw.betterTeams.Team.removePlayer(Team.java:648)
[18:55:31 WARN]: 	at BetterTeams.jar//com.booksaw.betterTeams.commands.team.LeaveCommand.onCommand(LeaveCommand.java:26)
[18:55:31 WARN]: 	at BetterTeams.jar//com.booksaw.betterTeams.commands.presets.TeamSubCommand.onCommand(TeamSubCommand.java:39)
[18:55:31 WARN]: 	at BetterTeams.jar//com.booksaw.betterTeams.commands.ParentCommand.onCommand(ParentCommand.java:135)
[18:55:31 WARN]: 	at BetterTeams.jar//com.booksaw.betterTeams.BooksawCommand.runExecution(BooksawCommand.java:72)
[18:55:31 WARN]: 	at BetterTeams.jar//com.booksaw.betterTeams.BooksawCommand.lambda$execute$0(BooksawCommand.java:59)
[18:55:31 WARN]: 	at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftTask.run(CraftTask.java:101)
[18:55:31 WARN]: 	at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57)
[18:55:31 WARN]: 	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[18:55:31 WARN]: 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
[18:55:31 WARN]: 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
[18:55:31 WARN]: 	at java.base/java.lang.Thread.run(Unknown Source)

### Output of /teama version

?

**Comment by booksaw** [comment]
Firstly please update your plugin to the latest version, improvements have been made in this area.
This is caused by a plugin conflict as another plugin is interacting with the TAB menu, please view this wiki page for information on how to properly fix this: https://github.com/booksaw/BetterTeams/wiki/Managing-the-TAB-Menu
