### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by Painguino** [booksaw/BetterTeams#516]
### What is the bug?

When using /team ban (player) or /team unban (player), it says in chat "Something went wrong while executing that command, please report it to a staff member." If you do /team ban (same player) after already typing it once, it says "That player is already banned" meaning the command still works, so i'm not sure why that message appears. Same thing when typing /team unban (banned player) twice except it says "That player is not banned." We are using purpur 1.20.1 on our server and the latest version of BetterTeams (4.8.2).

### Expected Behaviour

Player is banned or unbanned from the team without an error message appearing.

### How to Reproduce

After creating a team, type /team ban (playername) of a player who has played on the server before and isn't banned from your team or type /team unban (playername) if they are banned from your team.

### Error message

[04:45:15] [Craft Scheduler Thread - 21 - BetterTeams/ERROR]: Something went wrong while executing the command, please report this https://github.com/booksaw/BetterTeams/issues/new/choose
[04:45:15] [Craft Scheduler Thread - 21 - BetterTeams/WARN]: java.lang.ClassCastException: class org.bukkit.craftbukkit.v1_20_R1.CraftOfflinePlayer cannot be cast to class org.bukkit.command.CommandSender (org.bukkit.craftbukkit.v1_20_R1.CraftOfflinePlayer and org.bukkit.command.CommandSender are in unnamed module of loader java.net.URLClassLoader @2b71fc7e)
[04:45:15] [Craft Scheduler Thread - 21 - BetterTeams/WARN]: 	at BetterTeams.jar//com.booksaw.betterTeams.commands.team.BanCommand.onCommand(BanCommand.java:43)
[04:45:15] [Craft Scheduler Thread - 21 - BetterTeams/WARN]: 	at BetterTeams.jar//com.booksaw.betterTeams.commands.presets.TeamSubCommand.onCommand(TeamSubCommand.java:39)
[04:45:15] [Craft Scheduler Thread - 21 - BetterTeams/WARN]: 	at BetterTeams.jar//com.booksaw.betterTeams.commands.ParentCommand.onCommand(ParentCommand.java:135)
[04:45:15] [Craft Scheduler Thread - 21 - BetterTeams/WARN]: 	at BetterTeams.jar//com.booksaw.betterTeams.BooksawCommand.runExecution(BooksawCommand.java:72)
[04:45:15] [Craft Scheduler Thread - 21 - BetterTeams/WARN]: 	at BetterTeams.jar//com.booksaw.betterTeams.BooksawCommand.lambda$execute$0(BooksawCommand.java:59)
[04:45:15] [Craft Scheduler Thread - 21 - BetterTeams/WARN]: 	at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftTask.run(CraftTask.java:101)
[04:45:15] [Craft Scheduler Thread - 21 - BetterTeams/WARN]: 	at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57)
[04:45:15] [Craft Scheduler Thread - 21 - BetterTeams/WARN]: 	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[04:45:15] [Craft Scheduler Thread - 21 - BetterTeams/WARN]: 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[04:45:15] [Craft Scheduler Thread - 21 - BetterTeams/WARN]: 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[04:45:15] [Craft Scheduler Thread - 21 - BetterTeams/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:833)

### Output of /teama version

![Screenshot 2023-10-20 010109](https://github.com/booksaw/BetterTeams/assets/105611448/d7f255dc-f0ce-4fdf-b1aa-3d41b76e6920)

**Comment by booksaw** [comment]
This bug has been fixed and the patch will be included in the next update. Thank you for reporting.
