### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by Astral69** [booksaw/BetterTeams#519]
### What is the bug?

[23:00:40 ERROR]: Something went wrong while executing the command, please report this https://github.com/booksaw/BetterTeams/issues/new/choose
[23:00:40 WARN]: java.lang.NullPointerException: Cannot invoke "org.bukkit.World.getName()" because the return value of "org.bukkit.Location.getWorld()" is null
[23:00:40 WARN]:        at BetterTeams.jar//com.booksaw.betterTeams.team.LocationListComponent.getString(LocationListComponent.java:31)
[23:00:40 WARN]:        at BetterTeams.jar//com.booksaw.betterTeams.Warp.toString(Warp.java:47)
[23:00:40 WARN]:        at BetterTeams.jar//com.booksaw.betterTeams.team.WarpListComponent.toString(WarpListComponent.java:34)
[23:00:40 WARN]:        at BetterTeams.jar//com.booksaw.betterTeams.team.WarpListComponent.toString(WarpListComponent.java:9)
[23:00:40 WARN]:        at BetterTeams.jar//com.booksaw.betterTeams.team.ListTeamComponent.getConvertedList(ListTeamComponent.java:62)
[23:00:40 WARN]:        at BetterTeams.jar//com.booksaw.betterTeams.team.WarpListComponent.save(WarpListComponent.java:18)
[23:00:40 WARN]:        at BetterTeams.jar//com.booksaw.betterTeams.Team.saveWarps(Team.java:1322)
[23:00:40 WARN]:        at BetterTeams.jar//com.booksaw.betterTeams.Team.addWarp(Team.java:1337)
[23:00:40 WARN]:        at BetterTeams.jar//com.booksaw.betterTeams.commands.team.SetWarpCommand.onCommand(SetWarpCommand.java:36)
[23:00:40 WARN]:        at BetterTeams.jar//com.booksaw.betterTeams.commands.presets.TeamSubCommand.onCommand(TeamSubCommand.java:46)
[23:00:40 WARN]:        at BetterTeams.jar//com.booksaw.betterTeams.commands.ParentCommand.onCommand(ParentCommand.java:135)
[23:00:40 WARN]:        at BetterTeams.jar//com.booksaw.betterTeams.BooksawCommand.runExecution(BooksawCommand.java:72)
[23:00:40 WARN]:        at BetterTeams.jar//com.booksaw.betterTeams.BooksawCommand.lambda$execute$0(BooksawCommand.java:59)
[23:00:40 WARN]:        at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftTask.run(CraftTask.java:101)
[23:00:40 WARN]:        at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57)
[23:00:40 WARN]:        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[23:00:40 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[23:00:40 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[23:00:40 WARN]:        at java.base/java.lang.Thread.run(Thread.java:840)

### Expected Behaviour

create a warp

### How to Reproduce

1. happens when someone uses /team setwarp <name>

### Error message

[23:00:40 ERROR]: Something went wrong while executing the command, please report this https://github.com/booksaw/BetterTeams/issues/new/choose
[23:00:40 WARN]: java.lang.NullPointerException: Cannot invoke "org.bukkit.World.getName()" because the return value of "org.bukkit.Location.getWorld()" is null
[23:00:40 WARN]:        at BetterTeams.jar//com.booksaw.betterTeams.team.LocationListComponent.getString(LocationListComponent.java:31)
[23:00:40 WARN]:        at BetterTeams.jar//com.booksaw.betterTeams.Warp.toString(Warp.java:47)
[23:00:40 WARN]:        at BetterTeams.jar//com.booksaw.betterTeams.team.WarpListComponent.toString(WarpListComponent.java:34)
[23:00:40 WARN]:        at BetterTeams.jar//com.booksaw.betterTeams.team.WarpListComponent.toString(WarpListComponent.java:9)
[23:00:40 WARN]:        at BetterTeams.jar//com.booksaw.betterTeams.team.ListTeamComponent.getConvertedList(ListTeamComponent.java:62)
[23:00:40 WARN]:        at BetterTeams.jar//com.booksaw.betterTeams.team.WarpListComponent.save(WarpListComponent.java:18)
[23:00:40 WARN]:        at BetterTeams.jar//com.booksaw.betterTeams.Team.saveWarps(Team.java:1322)
[23:00:40 WARN]:        at BetterTeams.jar//com.booksaw.betterTeams.Team.addWarp(Team.java:1337)
[23:00:40 WARN]:        at BetterTeams.jar//com.booksaw.betterTeams.commands.team.SetWarpCommand.onCommand(SetWarpCommand.java:36)
[23:00:40 WARN]:        at BetterTeams.jar//com.booksaw.betterTeams.commands.presets.TeamSubCommand.onCommand(TeamSubCommand.java:46)
[23:00:40 WARN]:        at BetterTeams.jar//com.booksaw.betterTeams.commands.ParentCommand.onCommand(ParentCommand.java:135)
[23:00:40 WARN]:        at BetterTeams.jar//com.booksaw.betterTeams.BooksawCommand.runExecution(BooksawCommand.java:72)
[23:00:40 WARN]:        at BetterTeams.jar//com.booksaw.betterTeams.BooksawCommand.lambda$execute$0(BooksawCommand.java:59)
[23:00:40 WARN]:        at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftTask.run(CraftTask.java:101)
[23:00:40 WARN]:        at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57)
[23:00:40 WARN]:        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[23:00:40 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[23:00:40 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[23:00:40 WARN]:        at java.base/java.lang.Thread.run(Thread.java:840)

### Output of /teama version

[23:06:35 INFO]: [BetterTeams] Storage Method: com.booksaw.betterTeams.team.storage.storageManager.SeparatedYamlStorageManager
[23:06:35 INFO]: [BetterTeams] Minecraft Version: git-Paper-196 (MC: 1.20.1)
[23:06:35 INFO]: [BetterTeams] Language Selected: messages
[23:06:35 INFO]: [BetterTeams] Current plugin version: 4.8.3

### Additional Information

[23:00:40 ERROR]: Something went wrong while executing the command, please report this https://github.com/booksaw/BetterTeams/issues/new/choose
[23:00:40 WARN]: java.lang.NullPointerException: Cannot invoke "org.bukkit.World.getName()" because the return value of "org.bukkit.Location.getWorld()" is null
[23:00:40 WARN]:        at BetterTeams.jar//com.booksaw.betterTeams.team.LocationListComponent.getString(LocationListComponent.java:31)
[23:00:40 WARN]:        at BetterTeams.jar//com.booksaw.betterTeams.Warp.toString(Warp.java:47)
[23:00:40 WARN]:        at BetterTeams.jar//com.booksaw.betterTeams.team.WarpListComponent.toString(WarpListComponent.java:34)
[23:00:40 WARN]:        at BetterTeams.jar//com.booksaw.betterTeams.team.WarpListComponent.toString(WarpListComponent.java:9)
[23:00:40 WARN]:        at BetterTeams.jar//com.booksaw.betterTeams.team.ListTeamComponent.getConvertedList(ListTeamComponent.java:62)
[23:00:40 WARN]:        at BetterTeams.jar//com.booksaw.betterTeams.team.WarpListComponent.save(WarpListComponent.java:18)
[23:00:40 WARN]:        at BetterTeams.jar//com.booksaw.betterTeams.Team.saveWarps(Team.java:1322)
[23:00:40 WARN]:        at BetterTeams.jar//com.booksaw.betterTeams.Team.addWarp(Team.java:1337)
[23:00:40 WARN]:        at BetterTeams.jar//com.booksaw.betterTeams.commands.team.SetWarpCommand.onCommand(SetWarpCommand.java:36)
[23:00:40 WARN]:        at BetterTeams.jar//com.booksaw.betterTeams.commands.presets.TeamSubCommand.onCommand(TeamSubCommand.java:46)
[23:00:40 WARN]:        at BetterTeams.jar//com.booksaw.betterTeams.commands.ParentCommand.onCommand(ParentCommand.java:135)
[23:00:40 WARN]:        at BetterTeams.jar//com.booksaw.betterTeams.BooksawCommand.runExecution(BooksawCommand.java:72)
[23:00:40 WARN]:        at BetterTeams.jar//com.booksaw.betterTeams.BooksawCommand.lambda$execute$0(BooksawCommand.java:59)
[23:00:40 WARN]:        at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftTask.run(CraftTask.java:101)
[23:00:40 WARN]:        at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57)
[23:00:40 WARN]:        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[23:00:40 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[23:00:40 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[23:00:40 WARN]:        at java.base/java.lang.Thread.run(Thread.java:840)

**Comment by booksaw** [comment]
This issue is being closed for inactivity. If you are still having problems feel free to open a new issue linking this one, make sure you answer any questions asked in the new issue.
