### ISSUE TITLE
[BUG] Cannot leave from team

### ISSUE THREAD

**Issue by AraaCuteUwU** [booksaw/BetterTeams#548]
### What is the bug?

I cannot leave the team when I type /team leave

### Expected Behaviour

Player leave the team when using /team leave

### How to Reproduce

1. Join a team
2. Add the %betterteam_name% tag in the scoreboard
3. Leave the team

### Error message

[13:59:02 WARN]: java.lang.IllegalStateException: Unregistered scoreboard component
[13:59:02 WARN]:        at com.google.common.base.Preconditions.checkState(Preconditions.java:502)
[13:59:02 WARN]:        at org.bukkit.craftbukkit.v1_20_R1.scoreboard.CraftTeam.checkState(CraftTeam.java:396)
[13:59:02 WARN]:        at org.bukkit.craftbukkit.v1_20_R1.scoreboard.CraftTeam.removeEntry(CraftTeam.java:256)
[13:59:02 WARN]:        at BetterTeams.jar//com.booksaw.betterTeams.events.MCTeamManagement.remove(MCTeamManagement.java:110)
[13:59:02 WARN]:        at BetterTeams.jar//com.booksaw.betterTeams.events.MCTeamManagement.remove(MCTeamManagement.java:91)
[13:59:02 WARN]:        at BetterTeams.jar//com.booksaw.betterTeams.team.MemberListComponent.remove(MemberListComponent.java:63)
[13:59:02 WARN]:        at BetterTeams.jar//com.booksaw.betterTeams.Team.removePlayer(Team.java:662)
[13:59:02 WARN]:        at BetterTeams.jar//com.booksaw.betterTeams.Team.removePlayer(Team.java:648)
[13:59:02 WARN]:        at BetterTeams.jar//com.booksaw.betterTeams.commands.team.LeaveCommand.onCommand(LeaveCommand.java:26)
[13:59:02 WARN]:        at BetterTeams.jar//com.booksaw.betterTeams.commands.presets.TeamSubCommand.onCommand(TeamSubCommand.java:39)
[13:59:02 WARN]:        at BetterTeams.jar//com.booksaw.betterTeams.commands.ParentCommand.onCommand(ParentCommand.java:135)
[13:59:02 WARN]:        at BetterTeams.jar//com.booksaw.betterTeams.BooksawCommand.runExecution(BooksawCommand.java:72)
[13:59:02 WARN]:        at BetterTeams.jar//com.booksaw.betterTeams.BooksawCommand.lambda$execute$0(BooksawCommand.java:59)
[13:59:02 WARN]:        at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftTask.run(CraftTask.java:101)
[13:59:02 WARN]:        at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57)
[13:59:02 WARN]:        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[13:59:02 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[13:59:02 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[13:59:02 WARN]:        at java.base/java.lang.Thread.run(Thread.java:840)

### Output of /teama version

team version
[14:01:34 INFO]: /team delhome  - Delete your team's home
[14:01:34 INFO]: /team echest  - View your teams ender chest
[14:01:34 INFO]: /team color <color code> - Change your teams color
[14:01:34 INFO]: /team allychat [message] - Send a message only to your allies
[14:01:34 INFO]: /team description [description] - View and change your team's description
[14:01:34 INFO]: /team setwarp <name> [password] - Set a warp for the rest of your team
[14:01:34 INFO]: /team title [player/me] [title] - Change that players title within the team
[14:01:34 INFO]: /team bal  - View your teams balance
[14:01:34 INFO]: /team ban <player> - Bans the specified player from your team
[14:01:34 INFO]: /team promote <player> - Promote the specified player within your team
[14:01:34 INFO]: /team warps  - View a list of your teams warps
[14:01:34 INFO]: /team top  - View the top teams
[14:01:34 INFO]: /team ally <team> - Used to request an alliance with another team
[14:01:34 INFO]: /team rankup  - Rank your team up to get more perks
[14:01:34 INFO]: /team leave  - Leave your current team
[14:01:34 INFO]: /team sethome  - Sets your team's home
[14:01:34 INFO]: /team create <name> [tag] - Create a team with the specified name
[14:01:34 INFO]: /team rank [team] - View the rank of a team
[14:01:34 INFO]: /team join <team> - Join the specified team
[14:01:34 INFO]: /team tag [tag] - Set your teams tag
[14:01:34 INFO]: /team disband  - Disband your current team
[14:01:34 INFO]: /team info [team/player] - View information about the specified player / team
[14:01:34 INFO]: /team delwarp <name> [password] - Delete that warp from your team
[14:01:34 INFO]: /team chest  - 
[14:01:34 INFO]: /team neutral <team> - Remove allies and reject ally requests
[14:01:34 INFO]: /team pvp  - Toggle if pvp is enabled for your team
[14:01:34 INFO]: /team baltop  - View the richest teams
[14:01:34 INFO]: /team list [page] - Get a list of all teams on the server
[14:01:34 INFO]: /team home  - Teleports you to your team's home
[14:01:34 INFO]: /team help  - View this help page
[14:01:34 INFO]: /team unban <player> - Unbans the specified player from your team
[14:01:34 INFO]: /team demote <player> - Demote the specified player within your team
[14:01:34 INFO]: /team kick <player> - Kick that player from your team
[14:01:34 INFO]: /team chat [message] - Send a message only to your team
[14:01:34 INFO]: /team name <name> - View and change your team's name
[14:01:34 INFO]: /team deposit <amount> - Deposit money into the teams balance
[14:01:34 INFO]: /team invite <player> - Invite the specified player to your team
[14:01:34 INFO]: /team open  - Toggle if the team is invite only
[14:01:34 INFO]: /team warp <name> - Warp to a location set by your team
[14:01:34 INFO]: /team withdraw <amount> - Withdraw money from the teams balance

**Comment by booksaw** [comment]
Hi, you have shared the output of `/team version`, please could you share the output of `/teama version`
Also, set `useTeams` to false in config.yml and it should fix the problem.

**Comment by booksaw** [comment]
Thanks, could you set `useTeams` to false and let me know if the issue persists? 
This is caused by a plugin conflict and limitations of minecraft itself.
See this page for more info: https://github.com/booksaw/BetterTeams/wiki/Managing-the-TAB-Menu#conflict

**Comment by booksaw** [comment]
This issue is being closed for inactivity. If you are still having problems feel free to open a new issue linking this one, make sure you answer any questions asked in the new issue.
