### ISSUE TITLE
[BUG] Betterteams not working with zkoth

### ISSUE THREAD

**Issue by Axeczz** [booksaw/BetterTeams#565]
### What is the bug?

Whenever you have both zkoth and betterteams in 1 server, betterteams doesn't work properly. You can't change the messages.yml as it resets whenever you restart the server but you can change the config.yml(I haven't tried changing other files so I don't know if they work or not). Also you can't use /teamadmin reload as it just shows an error and it doesn't do anything. Basically you can't edit anything as it just resets once you restart the server and /teamadmin reload doesn't work. Everything started working normally once I removed zkoth. zkoth works fine when betterteams is added though.

### Expected Behaviour

I expect everything to work normally when zkoth is added so I can change all the files without any issues and can also reload the plugin without any issues.

### How to Reproduce

1. Run /teamadmin reload
2. Check your console for the error

### Error message

[15:14:56 INFO]: [BetterTeams] Checking if the file config.yml is up to date
[15:14:56 INFO]: [BetterTeams] File is up to date
[15:14:56 INFO]: [BetterTeams] Checking if the file messages.yml is up to date
[15:14:56 INFO]: [BetterTeams] File is up to date
[15:14:56 INFO]: [PlaceholderAPI] Successfully registered internal expansion: betterTeams [4.8.4]
[15:14:56 INFO]: Display team name config value: prefix
[15:14:56 INFO]: Loading below name. Type: PREFIX
[15:14:56 INFO]: teamManagement declared: com.booksaw.betterTeams.events.MCTeamManagement@61c9f321
[15:14:56 INFO]: Found plugin zKoth, adding plugin integration
[15:14:56 ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing 'teamadmin reload' in com.booksaw.betterTeams.BooksawCommand(teamadmin)
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:165) ~[pufferfish-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_20_R3.CraftServer.dispatchCommand(CraftServer.java:999) ~[pufferfish-1.20.4.jar:git-Pufferfish-46]
        at org.bukkit.craftbukkit.v1_20_R3.command.BukkitCommandWrapper.run(BukkitCommandWrapper.java:64) ~[pufferfish-1.20.4.jar:git-Pufferfish-46]
        at com.mojang.brigadier.context.ContextChain.runExecutable(ContextChain.java:73) ~[brigadier-1.2.9.jar:?]
        at net.minecraft.commands.execution.tasks.ExecuteCommand.execute(ExecuteCommand.java:32) ~[pufferfish-1.20.4.jar:git-Pufferfish-46]
        at net.minecraft.commands.execution.tasks.ExecuteCommand.execute(ExecuteCommand.java:19) ~[pufferfish-1.20.4.jar:git-Pufferfish-46]
        at net.minecraft.commands.execution.UnboundEntryAction.lambda$bind$0(UnboundEntryAction.java:8) ~[pufferfish-1.20.4.jar:git-Pufferfish-46]
        at net.minecraft.commands.execution.CommandQueueEntry.a(CommandQueueEntry.java:5) ~[pufferfish-1.20.4.jar:git-Pufferfish-46]
        at net.minecraft.commands.execution.ExecutionContext.runCommandQueue(ExecutionContext.java:101) ~[pufferfish-1.20.4.jar:git-Pufferfish-46]
        at net.minecraft.commands.Commands.executeCommandInContext(Commands.java:434) ~[?:?]
        at net.minecraft.commands.Commands.performCommand(Commands.java:336) ~[?:?]
        at net.minecraft.commands.Commands.performCommand(Commands.java:323) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.performChatCommand(ServerGamePacketListenerImpl.java:2231) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.lambda$handleChatCommand$14(ServerGamePacketListenerImpl.java:2191) ~[?:?]
        at net.minecraft.util.thread.BlockableEventLoop.lambda$submitAsync$0(BlockableEventLoop.java:59) ~[?:?]
        at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) ~[?:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[pufferfish-1.20.4.jar:git-Pufferfish-46]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1462) ~[pufferfish-1.20.4.jar:git-Pufferfish-46]
        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:194) ~[pufferfish-1.20.4.jar:git-Pufferfish-46]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1439) ~[pufferfish-1.20.4.jar:git-Pufferfish-46]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1362) ~[pufferfish-1.20.4.jar:git-Pufferfish-46]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1340) ~[pufferfish-1.20.4.jar:git-Pufferfish-46]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1229) ~[pufferfish-1.20.4.jar:git-Pufferfish-46]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:320) ~[pufferfish-1.20.4.jar:git-Pufferfish-46]
        at java.lang.Thread.run(Thread.java:840) ~[?:?]
Caused by: java.lang.NoClassDefFoundError: fr/maxlego08/zkoth/api/FactionListener
        at com.booksaw.betterTeams.Main.setupListeners(Main.java:429) ~[BetterTeams (2).jar:?]
        at com.booksaw.betterTeams.Main.onEnable(Main.java:214) ~[BetterTeams (2).jar:?]
        at com.booksaw.betterTeams.Main.reload(Main.java:334) ~[BetterTeams (2).jar:?]
        at com.booksaw.betterTeams.commands.teama.ReloadTeama.onCommand(ReloadTeama.java:18) ~[BetterTeams (2).jar:?]
        at com.booksaw.betterTeams.commands.ParentCommand.onCommand(ParentCommand.java:135) ~[BetterTeams (2).jar:?]
        at com.booksaw.betterTeams.BooksawCommand.runExecution(BooksawCommand.java:72) ~[BetterTeams (2).jar:?]
        at com.booksaw.betterTeams.BooksawCommand.execute(BooksawCommand.java:62) ~[BetterTeams (2).jar:?]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:155) ~[pufferfish-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        ... 28 more
Caused by: java.lang.ClassNotFoundException: fr.maxlego08.zkoth.api.FactionListener
        at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:199) ~[pufferfish-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:166) ~[pufferfish-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:525) ~[?:?]
        at com.booksaw.betterTeams.Main.setupListeners(Main.java:429) ~[BetterTeams (2).jar:?]
        at com.booksaw.betterTeams.Main.onEnable(Main.java:214) ~[BetterTeams (2).jar:?]
        at com.booksaw.betterTeams.Main.reload(Main.java:334) ~[BetterTeams (2).jar:?]
        at com.booksaw.betterTeams.commands.teama.ReloadTeama.onCommand(ReloadTeama.java:18) ~[BetterTeams (2).jar:?]
        at com.booksaw.betterTeams.commands.ParentCommand.onCommand(ParentCommand.java:135) ~[BetterTeams (2).jar:?]
        at com.booksaw.betterTeams.BooksawCommand.runExecution(BooksawCommand.java:72) ~[BetterTeams (2).jar:?]
        at com.booksaw.betterTeams.BooksawCommand.execute(BooksawCommand.java:62) ~[BetterTeams (2).jar:?]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:155) ~[pufferfish-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        ... 28 more

### Output of /teama version

[16:18:59 INFO]: Storage Method: com.booksaw.betterTeams.team.storage.storageManager.SeparatedYamlStorageManager
[16:18:59 INFO]: Minecraft Version: git-Pufferfish-46 (MC: 1.20.4)
[16:18:59 INFO]: Language Selected: messages
[16:18:59 INFO]: Online mode: true
[16:18:59 INFO]: Player count: 0
[16:18:59 INFO]: Current plugin version: 4.9.1

**Comment by booksaw** [comment]
Adding "wontfix" to stop myself checking this issue while working on other bugs as I do not intend to personally maintain support for zkoth any more in favour of trying to only really support free plugins.
