### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by IQsmYT** [booksaw/BetterTeams#587]
### What is the bug?

Logs:

19:33:17 WARN]: [BetterTeams] Plugin BetterTeams v4.9.1 generated an exception while executing task 6573717
java.lang.IllegalStateException: Unregistered scoreboard component
	at com.google.common.base.Preconditions.checkState(Preconditions.java:502) ~[guava-31.1-jre.jar:?]
	at org.bukkit.craftbukkit.v1_20_R1.scoreboard.CraftTeam.checkState(CraftTeam.java:396) ~[paper-1.20.1.jar:git-Paper-"f042be6"]
	at org.bukkit.craftbukkit.v1_20_R1.scoreboard.CraftTeam.addEntry(CraftTeam.java:227) ~[paper-1.20.1.jar:git-Paper-"f042be6"]
	at com.booksaw.betterTeams.events.MCTeamManagement.displayBelowName(MCTeamManagement.java:62) ~[BetterTeams (1).jar:?]
	at com.booksaw.betterTeams.events.MCTeamManagement.lambda$playerJoinEvent$0(MCTeamManagement.java:127) ~[BetterTeams (1).jar:?]
	at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.20.1.jar:git-Paper-"f042be6"]
	at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[paper-1.20.1.jar:git-Paper-"f042be6"]
	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[paper-1.20.1.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]

### Expected Behaviour

Fix the Bug, does it cause a RAM Leak?

### How to Reproduce

Always occours once the server is active

### Error message

19:33:17 WARN]: [BetterTeams] Plugin BetterTeams v4.9.1 generated an exception while executing task 6573717
java.lang.IllegalStateException: Unregistered scoreboard component
	at com.google.common.base.Preconditions.checkState(Preconditions.java:502) ~[guava-31.1-jre.jar:?]
	at org.bukkit.craftbukkit.v1_20_R1.scoreboard.CraftTeam.checkState(CraftTeam.java:396) ~[paper-1.20.1.jar:git-Paper-"f042be6"]
	at org.bukkit.craftbukkit.v1_20_R1.scoreboard.CraftTeam.addEntry(CraftTeam.java:227) ~[paper-1.20.1.jar:git-Paper-"f042be6"]
	at com.booksaw.betterTeams.events.MCTeamManagement.displayBelowName(MCTeamManagement.java:62) ~[BetterTeams (1).jar:?]
	at com.booksaw.betterTeams.events.MCTeamManagement.lambda$playerJoinEvent$0(MCTeamManagement.java:127) ~[BetterTeams (1).jar:?]
	at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.20.1.jar:git-Paper-"f042be6"]
	at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[paper-1.20.1.jar:git-Paper-"f042be6"]
	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[paper-1.20.1.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]

### Output of /teama version

.

**Comment by booksaw** [comment]
Hi, please see this wiki page on how to fix this error: https://github.com/booksaw/BetterTeams/wiki/Managing-the-TAB-Menu.

I have also improved the error message for future users.
