### ISSUE TITLE
[BUG] Invalid location in team file

### ISSUE THREAD

**Issue by leon1234567890123** [booksaw/BetterTeams#588]
### What is the bug?

an error that the plugin doesn´t work

### Expected Behaviour

no error

### How to Reproduce

starting the server

### Error message

```
[14:18:21] [Server thread/ERROR]: Could not pass event PlayerJoinEvent to BetterTeams v4.9.1
--
194 | java.lang.ArrayIndexOutOfBoundsException: Index 1 out of bounds for length 1
195 | at com.booksaw.betterTeams.team.LocationListComponent.getLocation(LocationListComponent.java:19) ~[BetterTeams.jar:?]
196 | at com.booksaw.betterTeams.team.LocationListComponent.fromString(LocationListComponent.java:47) ~[BetterTeams.jar:?]
197 | at com.booksaw.betterTeams.team.LocationListComponent.fromString(LocationListComponent.java:8) ~[BetterTeams.jar:?]
198 | at com.booksaw.betterTeams.team.ListTeamComponent.load(ListTeamComponent.java:54) ~[BetterTeams.jar:?]
199 | at com.booksaw.betterTeams.team.ChestClaimComponent.load(ChestClaimComponent.java:17) ~[BetterTeams.jar:?]
200 | at com.booksaw.betterTeams.Team.<init>(Team.java:352) ~[BetterTeams.jar:?]
201 | at com.booksaw.betterTeams.team.storage.storageManager.SeparatedYamlStorageManager.loadTeam(SeparatedYamlStorageManager.java:126) ~[BetterTeams.jar:?]
202 | at com.booksaw.betterTeams.team.storage.storageManager.SeparatedYamlStorageManager.onJoin(SeparatedYamlStorageManager.java:413) ~[BetterTeams.jar:?]
203 | at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor34.execute(Unknown Source) ~[?:?]
204 | at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[paper-api-1.19.4-R0.1-SNAPSHOT.jar:?]
205 | at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:81) ~[paper-api-1.19.4-R0.1-SNAPSHOT.jar:git-Paper-550]
206 | at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.19.4-R0.1-SNAPSHOT.jar:?]
207 | at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[paper-1.19.4.jar:git-Paper-550]
208 | at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126) ~[paper-1.19.4.jar:git-Paper-550]
209 | at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:615) ~[paper-api-1.19.4-R0.1-SNAPSHOT.jar:?]
210 | at net.minecraft.server.players.PlayerList.placeNewPlayer(PlayerList.java:332) ~[paper-1.19.4.jar:git-Paper-550]
211 | at net.minecraft.server.network.ServerLoginPacketListenerImpl.placeNewPlayer(ServerLoginPacketListenerImpl.java:202) ~[?:?]
212 | at net.minecraft.server.network.ServerLoginPacketListenerImpl.handleAcceptedLogin(ServerLoginPacketListenerImpl.java:183) ~[?:?]
213 | at net.minecraft.server.network.ServerLoginPacketListenerImpl.tick(ServerLoginPacketListenerImpl.java:85) ~[?:?]
214 | at net.minecraft.network.Connection.tick(Connection.java:595) ~[?:?]
215 | at net.minecraft.server.network.ServerConnectionListener.tick(ServerConnectionListener.java:234) ~[?:?]
216 | at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1576) ~[paper-1.19.4.jar:git-Paper-550]
217 | at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:447) ~[paper-1.19.4.jar:git-Paper-550]
218 | at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1397) ~[paper-1.19.4.jar:git-Paper-550]
219 | at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1174) ~[paper-1.19.4.jar:git-Paper-550]
220 | at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:320) ~[paper-1.19.4.jar:git-Paper-550]
221 | at java.lang.Thread.run(Thread.java:840) ~[?:?]

[14:18:21] [Server thread/ERROR]: Could not pass event PlayerJoinEvent to BetterTeams v4.9.1
java.lang.ArrayIndexOutOfBoundsException: Index 1 out of bounds for length 1
	at com.booksaw.betterTeams.team.LocationListComponent.getLocation(LocationListComponent.java:19) ~[BetterTeams.jar:?]
	at com.booksaw.betterTeams.team.LocationListComponent.fromString(LocationListComponent.java:47) ~[BetterTeams.jar:?]
	at com.booksaw.betterTeams.team.LocationListComponent.fromString(LocationListComponent.java:8) ~[BetterTeams.jar:?]
	at com.booksaw.betterTeams.team.ListTeamComponent.load(ListTeamComponent.java:54) ~[BetterTeams.jar:?]
	at com.booksaw.betterTeams.team.ChestClaimComponent.load(ChestClaimComponent.java:17) ~[BetterTeams.jar:?]
	at com.booksaw.betterTeams.Team.<init>(Team.java:352) ~[BetterTeams.jar:?]
	at com.booksaw.betterTeams.team.storage.storageManager.SeparatedYamlStorageManager.loadTeam(SeparatedYamlStorageManager.java:126) ~[BetterTeams.jar:?]
	at com.booksaw.betterTeams.team.storage.storageManager.SeparatedYamlStorageManager.onJoin(SeparatedYamlStorageManager.java:413) ~[BetterTeams.jar:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor34.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[paper-api-1.19.4-R0.1-SNAPSHOT.jar:?]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:81) ~[paper-api-1.19.4-R0.1-SNAPSHOT.jar:git-Paper-550]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.19.4-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[paper-1.19.4.jar:git-Paper-550]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126) ~[paper-1.19.4.jar:git-Paper-550]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:615) ~[paper-api-1.19.4-R0.1-SNAPSHOT.jar:?]
	at net.minecraft.server.players.PlayerList.placeNewPlayer(PlayerList.java:332) ~[paper-1.19.4.jar:git-Paper-550]
	at net.minecraft.server.network.ServerLoginPacketListenerImpl.placeNewPlayer(ServerLoginPacketListenerImpl.java:[202](https://aternos.org/log/#L202)) ~[?:?]
	at net.minecraft.server.network.ServerLoginPacketListenerImpl.handleAcceptedLogin(ServerLoginPacketListenerImpl.java:183) ~[?:?]
	at net.minecraft.server.network.ServerLoginPacketListenerImpl.tick(ServerLoginPacketListenerImpl.java:85) ~[?:?]
	at net.minecraft.network.Connection.tick(Connection.java:595) ~[?:?]
	at net.minecraft.server.network.ServerConnectionListener.tick(ServerConnectionListener.java:234) ~[?:?]
	at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1576) ~[paper-1.19.4.jar:git-Paper-550]
	at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:447) ~[paper-1.19.4.jar:git-Paper-550]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1397) ~[paper-1.19.4.jar:git-Paper-550]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1174) ~[paper-1.19.4.jar:git-Paper-550]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:320) ~[paper-1.19.4.jar:git-Paper-550]
	at java.lang.Thread.run(Thread.java:840) ~[?:?]
```
### Output of /teama version

 Unknown command. Type "/help" for help.

**Comment by booksaw** [comment]
Some invalid data has somehow got into a file within your plugin, I have improved the error message so you can find the suspect file within the teamInfo folder and delete it. Please let me know here if you need further support.

**Comment by booksaw** [comment]
This issue is being closed for inactivity. If you are still having problems feel free to open a new issue linking this one, make sure you answer any questions asked in the new issue.
