### ISSUE TITLE
mySQL Error when quickly switching teams [BUG] 

### ISSUE THREAD

**Issue by JorisvD01** [booksaw/BetterTeams#606]
### What is the bug?

When quicly joining / leaving different teams, the console gives multiple errors, mainly about mySQL

### Expected Behaviour

Let players join and leave the teams

### How to Reproduce

Install plugin with mySQL, quickly join / leave teams (possibly with multiple people at the same time, in our case while testing 3).
We already tried to enable rebuildLookups when a message in console mentioned it.

### Error message

[19:05:07] [Craft Scheduler Thread - 30 - BetterTeams/ERROR]: Something went wrong while executing the command, please report this https://github.com/booksaw/BetterTeams/issues/new/choose
[19:05:07] [Craft Scheduler Thread - 30 - BetterTeams/WARN]: java.lang.IllegalArgumentException: Invalid UUID string: 
[19:05:07] [Craft Scheduler Thread - 30 - BetterTeams/WARN]: 	at java.base/java.util.UUID.fromString1(UUID.java:282)
[19:05:07] [Craft Scheduler Thread - 30 - BetterTeams/WARN]: 	at java.base/java.util.UUID.fromString(UUID.java:260)
[19:05:07] [Craft Scheduler Thread - 30 - BetterTeams/WARN]: 	at BetterTeams-4.9.4 (1).jar//com.booksaw.betterTeams.team.storage.storageManager.SQLStorageManager.getTeamUUID(SQLStorageManager.java:108)
[19:05:07] [Craft Scheduler Thread - 30 - BetterTeams/WARN]: 	at BetterTeams-4.9.4 (1).jar//com.booksaw.betterTeams.team.TeamManager.getTeam(TeamManager.java:117)
[19:05:07] [Craft Scheduler Thread - 30 - BetterTeams/WARN]: 	at BetterTeams-4.9.4 (1).jar//com.booksaw.betterTeams.Team.getTeam(Team.java:94)
[19:05:07] [Craft Scheduler Thread - 30 - BetterTeams/WARN]: 	at BetterTeams-4.9.4 (1).jar//com.booksaw.betterTeams.commands.presets.TeamSubCommand.onCommand(TeamSubCommand.java:27)
[19:05:07] [Craft Scheduler Thread - 30 - BetterTeams/WARN]: 	at BetterTeams-4.9.4 (1).jar//com.booksaw.betterTeams.commands.ParentCommand.onCommand(ParentCommand.java:135)
[19:05:07] [Craft Scheduler Thread - 30 - BetterTeams/WARN]: 	at BetterTeams-4.9.4 (1).jar//com.booksaw.betterTeams.BooksawCommand.runExecution(BooksawCommand.java:73)
[19:05:07] [Craft Scheduler Thread - 30 - BetterTeams/WARN]: 	at BetterTeams-4.9.4 (1).jar//com.booksaw.betterTeams.BooksawCommand.lambda$execute$0(BooksawCommand.java:60)
[19:05:07] [Craft Scheduler Thread - 30 - BetterTeams/WARN]: 	at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftTask.run(CraftTask.java:101)
[19:05:07] [Craft Scheduler Thread - 30 - BetterTeams/WARN]: 	at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57)
[19:05:07] [Craft Scheduler Thread - 30 - BetterTeams/WARN]: 	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[19:05:07] [Craft Scheduler Thread - 30 - BetterTeams/WARN]: 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
[19:05:07] [Craft Scheduler Thread - 30 - BetterTeams/WARN]: 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
[19:05:07] [Craft Scheduler Threa - 30 - BetterTeams/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:1583)

### Output of /teama version

![image](https://github.com/booksaw/BetterTeams/assets/99077822/5831971f-e76a-4c94-b9a4-bd2aa6384136)

### Additional Information

We have a deluxeMenus menu where people can join / leave a team thru. This menu has a lot of placeholders as well. At some point we thought this may could be part of the issue, but these placeholders don't seem to refresh very often, so they might not be an issue

**Comment by JorisvD01** [comment]
[20:31:16 ERROR]: [BetterTeams] For some reason your storage has desynchronised, set `rebuildLookups` to true in config.yml and restart your server
[20:31:16 ERROR]: [BetterTeams] If this keeps occuring after performing this change, please report it as a bug
[20:31:16 ERROR]: Something went wrong while executing the command, please report this https://github.com/booksaw/BetterTeams/issues/new/choose
[20:31:16 WARN]: java.lang.NullPointerException: Cannot invoke "com.booksaw.betterTeams.TeamPlayer.getRank()" because "player" is null
[20:31:16 WARN]: at BetterTeams-4.9.4 (1).jar//com.booksaw.betterTeams.commands.presets.TeamSubCommand.checkRank(TeamSubCommand.java:84)
[20:31:16 WARN]: at BetterTeams-4.9.4 (1).jar//com.booksaw.betterTeams.commands.presets.TeamSubCommand.checkRank(TeamSubCommand.java:79)
[20:31:16 WARN]: at BetterTeams-4.9.4 (1).jar//com.booksaw.betterTeams.commands.presets.TeamSubCommand.onCommand(TeamSubCommand.java:40)
[20:31:16 WARN]: at BetterTeams-4.9.4 (1).jar//com.booksaw.betterTeams.commands.ParentCommand.onCommand(ParentCommand.java:135)
[20:31:16 WARN]: at BetterTeams-4.9.4 (1).jar//com.booksaw.betterTeams.BooksawCommand.runExecution(BooksawCommand.java:73)
[20:31:16 WARN]: at BetterTeams-4.9.4 (1).jar//com.booksaw.betterTeams.BooksawCommand.lambda$execute$0(BooksawCommand.java:60)
[20:31:16 WARN]: at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftTask.run(CraftTask.java:101)
[20:31:16 WARN]: at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57)
[20:31:16 WARN]: at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[20:31:16 WARN]: at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
[20:31:16 WARN]: at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
[20:31:16 WARN]: at java.base/java.lang.Thread.run(Thread.java:1583)

**Comment by booksaw** [comment]
I have tried to reproduce and so far have been unable. Are you able to provide any further information?
Do you know what the latency between your SQL DB and server are as I'm guessing this is likely the cause.

**Comment by JorisvD01** [comment]
> I have tried to reproduce and so far have been unable. Are you able to provide any further information?
> Do you know what the latency between your SQL DB and server are as I'm guessing this is likely the cause.

For now we've decided it was easier to switch to a different plugin. We might give the plugin a try again soon tho! It has a lot of features we were looking for.

Apart from that I don't really know the exact latency. We were using a lot of placeholders, so that may increase the network traffic? But we didn't have and simular issues with other plugins at the time. Sorry I can't give much more info on this.

**Comment by booksaw** [comment]
This issue is being closed for inactivity. If you are still having problems feel free to open a new issue linking this one, make sure you answer any questions asked in the new issue.
