### ISSUE TITLE
[BUG] Randomly Breaking

### ISSUE THREAD

**Issue by KhrysAK47** [booksaw/BetterTeams#609]
### What is the bug?

https://pastebin.com/z4xR2Tvy

### Expected Behaviour

It should not break lol

### How to Reproduce

Not certain

### Output of /teama version

[18:19:49 INFO]: Storage Method: com.booksaw.betterTeams.team.storage.storageManager.SeparatedYamlStorageManager
[18:19:49 INFO]: Minecraft Version: git-Paper-496 (MC: 1.20.4)
[18:19:49 INFO]: Language Selected: messages
[18:19:49 INFO]: Online mode: false
[18:19:49 INFO]: Player count: 1
[18:19:49 INFO]: Current plugin version: 4.9.4

**Comment by booksaw** [comment]
```yaml
[08:53:03] [TAB Placeholder Refreshing Thread/ERROR]: [org.bukkit.configuration.serialization.ConfigurationSerialization] Could not call method 'public static org.bukkit.inventory.meta.ItemMeta org.bukkit.craftbukkit.v1_20_R3.inventory.CraftMetaItem$SerializableMeta.deserialize(java.util.Map) throws java.lang.Throwable' of class org.bukkit.craftbukkit.v1_20_R3.inventory.CraftMetaItem$SerializableMeta for deserialization
java.lang.ClassCastException: class java.util.LinkedHashMap cannot be cast to class java.lang.String (java.util.LinkedHashMap and java.lang.String are in module java.base of loader 'bootstrap')
	at org.bukkit.craftbukkit.v1_20_R3.inventory.CraftMetaItem.<init>(CraftMetaItem.java:557) ~[paper-1.20.4.jar:git-Paper-496]
	at org.bukkit.craftbukkit.v1_20_R3.inventory.CraftMetaSpawnEgg.<init>(CraftMetaSpawnEgg.java:132) ~[paper-1.20.4.jar:git-Paper-496]
	at jdk.internal.reflect.GeneratedConstructorAccessor45.newInstance(Unknown Source) ~[?:?]
	at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source) ~[?:?]
	at java.lang.reflect.Constructor.newInstanceWithCaller(Unknown Source) ~[?:?]
	at java.lang.reflect.Constructor.newInstance(Unknown Source) ~[?:?]
	at org.bukkit.craftbukkit.v1_20_R3.inventory.CraftMetaItem$SerializableMeta.deserialize(CraftMetaItem.java:206) ~[paper-1.20.4.jar:git-Paper-496]
	at jdk.internal.reflect.GeneratedMethodAccessor31.invoke(Unknown Source) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:?]
	at org.bukkit.configuration.serialization.ConfigurationSerialization.deserializeViaMethod(ConfigurationSerialization.java:87) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.configuration.serialization.ConfigurationSerialization.deserialize(ConfigurationSerialization.java:129) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.configuration.serialization.ConfigurationSerialization.deserializeObject(ConfigurationSerialization.java:209) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.configuration.file.YamlConstructor$ConstructCustomObject.construct(YamlConstructor.java:58) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
	at org.yaml.snakeyaml.constructor.BaseConstructor.constructObjectNoCheck(BaseConstructor.java:264) ~[snakeyaml-2.2.jar:?]
	at org.yaml.snakeyaml.constructor.BaseConstructor.constructObject(BaseConstructor.java:247) ~[snakeyaml-2.2.jar:?]
	at org.yaml.snakeyaml.constructor.BaseConstructor.constructMapping2ndStep(BaseConstructor.java:576) ~[snakeyaml-2.2.jar:?]
	at org.yaml.snakeyaml.constructor.SafeConstructor.constructMapping2ndStep(SafeConstructor.java:210) ~[snakeyaml-2.2.jar:?]
	at org.yaml.snakeyaml.constructor.BaseConstructor.constructMapping(BaseConstructor.java:552) ~[snakeyaml-2.2.jar:?]
	at org.yaml.snakeyaml.constructor.SafeConstructor$ConstructYamlMap.construct(SafeConstructor.java:597) ~[snakeyaml-2.2.jar:?]
	at org.bukkit.configuration.file.YamlConstructor$ConstructCustomObject.construct(YamlConstructor.java:49) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
	at org.yaml.snakeyaml.constructor.BaseConstructor.constructObjectNoCheck(BaseConstructor.java:264) ~[snakeyaml-2.2.jar:?]
	at org.yaml.snakeyaml.constructor.BaseConstructor.constructObject(BaseConstructor.java:247) ~[snakeyaml-2.2.jar:?]
	at org.bukkit.configuration.file.YamlConstructor.construct(YamlConstructor.java:37) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.configuration.file.YamlConfiguration.fromNodeTree(YamlConfiguration.java:163) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.configuration.file.YamlConfiguration.fromNodeTree(YamlConfiguration.java:161) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.configuration.file.YamlConfiguration.loadFromString(YamlConfiguration.java:120) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.configuration.file.FileConfiguration.load(FileConfiguration.java:160) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.configuration.file.FileConfiguration.load(FileConfiguration.java:128) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.configuration.file.YamlConfiguration.loadConfiguration(YamlConfiguration.java:309) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
	at com.booksaw.betterTeams.ConfigManager.<init>(ConfigManager.java:73) ~[BetterTeams-4.9.4.jar:?]
	at com.booksaw.betterTeams.team.storage.team.SeparatedYamlTeamStorage.<init>(SeparatedYamlTeamStorage.java:30) ~[BetterTeams-4.9.4.jar:?]
	at com.booksaw.betterTeams.team.storage.storageManager.SeparatedYamlStorageManager.createTeamStorage(SeparatedYamlStorageManager.java:207) ~[BetterTeams-4.9.4.jar:?]
	at com.booksaw.betterTeams.Team.<init>(Team.java:298) ~[BetterTeams-4.9.4.jar:?]
	at com.booksaw.betterTeams.team.TeamManager.getTeam(TeamManager.java:74) ~[BetterTeams-4.9.4.jar:?]
	at com.booksaw.betterTeams.team.TeamManager.getTeam(TeamManager.java:122) ~[BetterTeams-4.9.4.jar:?]
	at com.booksaw.betterTeams.Team.getTeam(Team.java:94) ~[BetterTeams-4.9.4.jar:?]
	at com.booksaw.betterTeams.integrations.placeholder.TeamPlaceholders.onPlaceholderRequest(TeamPlaceholders.java:83) ~[BetterTeams-4.9.4.jar:?]
	at me.clip.placeholderapi.PlaceholderHook.onRequest(PlaceholderHook.java:32) ~[PlaceholderAPI-2.11.6.jar:?]
	at me.clip.placeholderapi.replacer.CharsReplacer.apply(CharsReplacer.java:119) ~[PlaceholderAPI-2.11.6.jar:?]
	at me.clip.placeholderapi.PlaceholderAPI.setPlaceholders(PlaceholderAPI.java:71) ~[PlaceholderAPI-2.11.6.jar:?]
	at me.clip.placeholderapi.PlaceholderAPI.setPlaceholders(PlaceholderAPI.java:99) ~[PlaceholderAPI-2.11.6.jar:?]
	at me.neznamy.tab.platforms.bukkit.platform.BukkitPlatform.lambda$registerUnknownPlaceholder$7(BukkitPlatform.java:190) ~[TAB v4.1.2.jar:?]
	at me.neznamy.tab.shared.placeholders.PlayerPlaceholderImpl.request(PlayerPlaceholderImpl.java:146) ~[TAB v4.1.2.jar:?]
	at me.neznamy.tab.shared.placeholders.PlayerPlaceholderImpl.update(PlayerPlaceholderImpl.java:52) ~[TAB v4.1.2.jar:?]
	at me.neznamy.tab.shared.features.PlaceholderManagerImpl.updatePlayerPlaceholder(PlaceholderManagerImpl.java:120) ~[TAB v4.1.2.jar:?]
	at me.neznamy.tab.shared.features.PlaceholderManagerImpl.refresh(PlaceholderManagerImpl.java:67) ~[TAB v4.1.2.jar:?]
	at me.neznamy.tab.shared.cpu.CpuManager.lambda$enable$1(CpuManager.java:77) ~[TAB v4.1.2.jar:?]
	at me.neznamy.tab.shared.cpu.CpuManager.run(CpuManager.java:173) ~[TAB v4.1.2.jar:?]
	at me.neznamy.tab.shared.cpu.CpuManager.lambda$enable$2(CpuManager.java:75) ~[TAB v4.1.2.jar:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[?:?]
	at java.util.concurrent.FutureTask.runAndReset(Unknown Source) ~[?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) ~[?:?]
	at java.lang.Thread.run(Unknown Source) ~[?:?]
[08:53:03] [TAB Placeholder Refreshing Thread/ERROR]: [org.bukkit.configuration.serialization.ConfigurationSerialization] Could not call method 'public static org.bukkit.inventory.meta.ItemMeta org.bukkit.craftbukkit.v1_20_R3.inventory.CraftMetaItem$SerializableMeta.deserialize(java.util.Map) throws java.lang.Throwable' of class org.bukkit.craftbukkit.v1_20_R3.inventory.CraftMetaItem$SerializableMeta for deserialization
java.lang.ClassCastException: class java.util.LinkedHashMap cannot be cast to class java.lang.String (java.util.LinkedHashMap and java.lang.String are in module java.base of loader 'bootstrap')
	at org.bukkit.craftbukkit.v1_20_R3.inventory.CraftMetaItem.<init>(CraftMetaItem.java:557) ~[paper-1.20.4.jar:git-Paper-496]
	at org.bukkit.craftbukkit.v1_20_R3.inventory.CraftMetaSpawnEgg.<init>(CraftMetaSpawnEgg.java:132) ~[paper-1.20.4.jar:git-Paper-496]
	at jdk.internal.reflect.GeneratedConstructorAccessor45.newInstance(Unknown Source) ~[?:?]
	at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source) ~[?:?]
	at java.lang.reflect.Constructor.newInstanceWithCaller(Unknown Source) ~[?:?]
	at java.lang.reflect.Constructor.newInstance(Unknown Source) ~[?:?]
	at org.bukkit.craftbukkit.v1_20_R3.inventory.CraftMetaItem$SerializableMeta.deserialize(CraftMetaItem.java:206) ~[paper-1.20.4.jar:git-Paper-496]
	at jdk.internal.reflect.GeneratedMethodAccessor31.invoke(Unknown Source) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:?]
	at org.bukkit.configuration.serialization.ConfigurationSerialization.deserializeViaMethod(ConfigurationSerialization.java:87) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.configuration.serialization.ConfigurationSerialization.deserialize(ConfigurationSerialization.java:129) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.configuration.serialization.ConfigurationSerialization.deserializeObject(ConfigurationSerialization.java:209) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.configuration.file.YamlConstructor$ConstructCustomObject.construct(YamlConstructor.java:58) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
	at org.yaml.snakeyaml.constructor.BaseConstructor.constructObjectNoCheck(BaseConstructor.java:264) ~[snakeyaml-2.2.jar:?]
	at org.yaml.snakeyaml.constructor.BaseConstructor.constructObject(BaseConstructor.java:247) ~[snakeyaml-2.2.jar:?]
	at org.yaml.snakeyaml.constructor.BaseConstructor.constructMapping2ndStep(BaseConstructor.java:576) ~[snakeyaml-2.2.jar:?]
	at org.yaml.snakeyaml.constructor.SafeConstructor.constructMapping2ndStep(SafeConstructor.java:210) ~[snakeyaml-2.2.jar:?]
	at org.yaml.snakeyaml.constructor.BaseConstructor.constructMapping(BaseConstructor.java:552) ~[snakeyaml-2.2.jar:?]
	at org.yaml.snakeyaml.constructor.SafeConstructor$ConstructYamlMap.construct(SafeConstructor.java:597) ~[snakeyaml-2.2.jar:?]
	at org.bukkit.configuration.file.YamlConstructor$ConstructCustomObject.construct(YamlConstructor.java:49) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
	at org.yaml.snakeyaml.constructor.BaseConstructor.constructObjectNoCheck(BaseConstructor.java:264) ~[snakeyaml-2.2.jar:?]
	at org.yaml.snakeyaml.constructor.BaseConstructor.constructObject(BaseConstructor.java:247) ~[snakeyaml-2.2.jar:?]
	at org.bukkit.configuration.file.YamlConstructor.construct(YamlConstructor.java:37) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.configuration.file.YamlConfiguration.fromNodeTree(YamlConfiguration.java:163) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.configuration.file.YamlConfiguration.fromNodeTree(YamlConfiguration.java:161) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.configuration.file.YamlConfiguration.loadFromString(YamlConfiguration.java:120) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.configuration.file.FileConfiguration.load(FileConfiguration.java:160) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.configuration.file.FileConfiguration.load(FileConfiguration.java:128) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.configuration.file.YamlConfiguration.loadConfiguration(YamlConfiguration.java:309) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
	at com.booksaw.betterTeams.ConfigManager.<init>(ConfigManager.java:73) ~[BetterTeams-4.9.4.jar:?]
	at com.booksaw.betterTeams.team.storage.team.SeparatedYamlTeamStorage.<init>(SeparatedYamlTeamStorage.java:30) ~[BetterTeams-4.9.4.jar:?]
	at com.booksaw.betterTeams.team.storage.storageManager.SeparatedYamlStorageManager.createTeamStorage(SeparatedYamlStorageManager.java:207) ~[BetterTeams-4.9.4.jar:?]
	at com.booksaw.betterTeams.Team.<init>(Team.java:298) ~[BetterTeams-4.9.4.jar:?]
	at com.booksaw.betterTeams.team.TeamManager.getTeam(TeamManager.java:74) ~[BetterTeams-4.9.4.jar:?]
	at com.booksaw.betterTeams.team.TeamManager.getTeam(TeamManager.java:122) ~[BetterTeams-4.9.4.jar:?]
	at com.booksaw.betterTeams.Team.getTeam(Team.java:94) ~[BetterTeams-4.9.4.jar:?]
	at com.booksaw.betterTeams.integrations.placeholder.TeamPlaceholders.onPlaceholderRequest(TeamPlaceholders.java:83) ~[BetterTeams-4.9.4.jar:?]
	at me.clip.placeholderapi.PlaceholderHook.onRequest(PlaceholderHook.java:32) ~[PlaceholderAPI-2.11.6.jar:?]
	at me.clip.placeholderapi.replacer.CharsReplacer.apply(CharsReplacer.java:119) ~[PlaceholderAPI-2.11.6.jar:?]
	at me.clip.placeholderapi.PlaceholderAPI.setPlaceholders(PlaceholderAPI.java:71) ~[PlaceholderAPI-2.11.6.jar:?]
	at me.clip.placeholderapi.PlaceholderAPI.setPlaceholders(PlaceholderAPI.java:99) ~[PlaceholderAPI-2.11.6.jar:?]
	at me.neznamy.tab.platforms.bukkit.platform.BukkitPlatform.lambda$registerUnknownPlaceholder$7(BukkitPlatform.java:190) ~[TAB v4.1.2.jar:?]
	at me.neznamy.tab.shared.placeholders.PlayerPlaceholderImpl.request(PlayerPlaceholderImpl.java:146) ~[TAB v4.1.2.jar:?]
	at me.neznamy.tab.shared.placeholders.PlayerPlaceholderImpl.update(PlayerPlaceholderImpl.java:52) ~[TAB v4.1.2.jar:?]
	at me.neznamy.tab.shared.features.PlaceholderManagerImpl.updatePlayerPlaceholder(PlaceholderManagerImpl.java:120) ~[TAB v4.1.2.jar:?]
	at me.neznamy.tab.shared.features.PlaceholderManagerImpl.refresh(PlaceholderManagerImpl.java:67) ~[TAB v4.1.2.jar:?]
	at me.neznamy.tab.shared.cpu.CpuManager.lambda$enable$1(CpuManager.java:77) ~[TAB v4.1.2.jar:?]
	at me.neznamy.tab.shared.cpu.CpuManager.run(CpuManager.java:173) ~[TAB v4.1.2.jar:?]
	at me.neznamy.tab.shared.cpu.CpuManager.lambda$enable$2(CpuManager.java:75) ~[TAB v4.1.2.jar:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[?:?]
	at java.util.concurrent.FutureTask.runAndReset(Unknown Source) ~[?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) ~[?:?]
	at java.lang.Thread.run(Unknown Source) ~[?:?]
```

**Comment by booksaw** [comment]
@KhrysAK47 If you run /team top, are there any errors in the console, if so could you share the files mentioned in any error mesasges?

**Comment by booksaw** [comment]
This issue is being closed for inactivity. If you are still having problems feel free to open a new issue linking this one, make sure you answer any questions asked in the new issue.
