### ISSUE TITLE
[BUG] /team baltop

### ISSUE THREAD

**Issue by ShikuretSensei** [booksaw/BetterTeams#623]
### What is the bug?

When doing /team baltop I get this issue

[16:11:39 INFO]: EtoGamesLive issued server command: /team baltop
[16:11:39 WARN]: [BetterTeams] Plugin BetterTeams v4.9.4 generated an exception while executing task 45789
java.lang.NullPointerException: Cannot invoke "com.booksaw.betterTeams.Team.getName()" because "tempTeam" is null
        at BetterTeams-4.9.4.jar/com.booksaw.betterTeams.commands.team.BaltopCommand$1.run(BaltopCommand.java:39) ~[BetterTeams-4.9.4.jar:?]
        at org.bukkit.craftbukkit.scheduler.CraftTask.run(CraftTask.java:101) ~[purpur-1.20.6.jar:1.20.6-2233-0d6766e]
        at org.bukkit.craftbukkit.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[purpur-1.20.6.jar:1.20.6-2233-0d6766e]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[purpur-1.20.6.jar:?]
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) ~[?:?]
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) ~[?:?]
        at java.base/java.lang.Thread.run(Unknown Source) ~[?:?]

### Expected Behaviour

When doing /team baltop

### How to Reproduce

I just did /teambaltop 

### Error message

[16:11:39 INFO]: EtoGamesLive issued server command: /team baltop
[16:11:39 WARN]: [BetterTeams] Plugin BetterTeams v4.9.4 generated an exception while executing task 45789
java.lang.NullPointerException: Cannot invoke "com.booksaw.betterTeams.Team.getName()" because "tempTeam" is null
        at BetterTeams-4.9.4.jar/com.booksaw.betterTeams.commands.team.BaltopCommand$1.run(BaltopCommand.java:39) ~[BetterTeams-4.9.4.jar:?]
        at org.bukkit.craftbukkit.scheduler.CraftTask.run(CraftTask.java:101) ~[purpur-1.20.6.jar:1.20.6-2233-0d6766e]
        at org.bukkit.craftbukkit.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[purpur-1.20.6.jar:1.20.6-2233-0d6766e]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[purpur-1.20.6.jar:?]
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) ~[?:?]
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) ~[?:?]
        at java.base/java.lang.Thread.run(Unknown Source) ~[?:?]

### Output of /teama version

![image](https://github.com/booksaw/BetterTeams/assets/39545120/246dd159-f769-4b66-b12c-b6a6e77d247f)

**Comment by booksaw** [comment]
Set `rebuildLookups` to true and restart your server, it should fix the problem.
I have also improved the logging so I am going to close the issue. 
Please feel free to open a new one if you have further problems.
