### ISSUE TITLE
[BUG] Error in Console

### ISSUE THREAD

**Issue by TheProOne1** [booksaw/BetterTeams#634]
### What is the bug?

There seems to be an Error popping up in Console regarding BetterTeams.

### Expected Behaviour

-

### How to Reproduce

-

### Error message

[08:32:16 WARN]: [BetterTeams] Plugin BetterTeams v4.9.4 generated an exception while executing task 4260461
java.lang.NullPointerException: Cannot invoke "org.bukkit.OfflinePlayer.getUniqueId()" because "p" is null
        at com.booksaw.betterTeams.team.TeamPlayerListComponent.getTeamPlayer(TeamPlayerListComponent.java:71) ~[BetterTeams-4.9.4.jar:?]
        at com.booksaw.betterTeams.Team.getTeamPlayer(Team.java:714) ~[BetterTeams-4.9.4.jar:?]
        at com.booksaw.betterTeams.Team$1.run(Team.java:818) ~[BetterTeams-4.9.4.jar:?]
        at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftTask.run(CraftTask.java:101) ~[purpur-1.20.4.jar:git-Purpur-2176]
        at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[purpur-1.20.4.jar:git-Purpur-2176]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[purpur-1.20.4.jar:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
        at java.lang.Thread.run(Thread.java:1583) ~[?:?]

### Output of /teama version

[08:34:05 INFO]: Storage Method: com.booksaw.betterTeams.team.storage.storageManager.SeparatedYamlStorageManager
[08:34:05 INFO]: Minecraft Version: git-Purpur-2176 (MC: 1.20.4)
[08:34:05 INFO]: Language Selected: messages
[08:34:05 INFO]: Online mode: false
[08:34:05 INFO]: Player count: 74
[08:34:05 INFO]: Current plugin version: 4.9.4

### Additional Information

-

**Comment by Ceymikey** [comment]
Could you maybe provide some more information for example if this occures after performing a specific action or it just happens randomly etc. Because this just shows that it is null.

**Comment by Ceymikey** [comment]
Anyway what I am thinking is the issue here is due to the fact you are running an offline server for cracked players. The plugin tried searching for a players UUID but that player could be playing cracked and cracked accounts don’t hold an UUID which caused the plugin to throw in a nullpointerexception.

**Comment by booksaw** [comment]
This bug has been fixed and the patch will be included in the next update. Thank you for reporting.
