### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by WoolOrange** [booksaw/BetterTeams#651]
### What is the bug?

The teams plugin randomly broke after my server was up for 2 days and it was working fine before.

### Expected Behaviour

I expected the commands to work but none of them actually do,

### How to Reproduce

1. Try to wait 2 days
2. run a command
3. it stops working

### Error message

[22:39:26 WARN]: Could not find the message with the reference help.header
[22:39:26 WARN]: Could not find the message with the reference command.delhome
[22:39:26 ERROR]: Something went wrong while executing the command, please report this https://github.com/booksaw/BetterTeams/issues/new/choose
[22:39:26 WARN]: java.lang.NullPointerException: Cannot invoke "org.bukkit.configuration.file.FileConfiguration.set(String, Object)" because the return value of "com.booksaw.betterTeams.message.MessageManager.getDefaultMessages()" is null
[22:39:26 WARN]: 	at BetterTeams-4.9.4.jar//com.booksaw.betterTeams.commands.ParentCommand.getReference(ParentCommand.java:246)
[22:39:26 WARN]: 	at BetterTeams-4.9.4.jar//com.booksaw.betterTeams.commands.HelpCommand.onCommand(HelpCommand.java:85)
[22:39:26 WARN]: 	at BetterTeams-4.9.4.jar//com.booksaw.betterTeams.commands.ParentCommand.displayHelp(ParentCommand.java:168)
[22:39:26 WARN]: 	at BetterTeams-4.9.4.jar//com.booksaw.betterTeams.commands.ParentCommand.onCommand(ParentCommand.java:90)
[22:39:26 WARN]: 	at BetterTeams-4.9.4.jar//com.booksaw.betterTeams.BooksawCommand.runExecution(BooksawCommand.java:73)
[22:39:26 WARN]: 	at BetterTeams-4.9.4.jar//com.booksaw.betterTeams.BooksawCommand.lambda$execute$0(BooksawCommand.java:60)
[22:39:26 WARN]: 	at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftTask.run(CraftTask.java:101)
[22:39:26 WARN]: 	at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57)
[22:39:26 WARN]: 	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[22:39:26 WARN]: 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
[22:39:26 WARN]: 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
[22:39:26 WARN]: 	at java.base/java.lang.Thread.run(Thread.java:1583)
[22:39:26 WARN]: Could not find the message with the reference internalError

**Also when trying to tab complete something in the plugin this happens,** 

org.bukkit.command.CommandException: Unhandled exception executing tab-completer for 'teama invite ' in com.booksaw.betterTeams.BooksawCommand(teamadmin)
	at org.bukkit.command.SimpleCommandMap.tabComplete(SimpleCommandMap.java:246) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_20_R3.CraftServer.tabCompleteCommand(CraftServer.java:2548) ~[paper-1.20.4.jar:git-Paper-496]
	at org.bukkit.craftbukkit.v1_20_R3.CraftServer.tabComplete(CraftServer.java:2520) ~[paper-1.20.4.jar:git-Paper-496]
	at org.bukkit.craftbukkit.v1_20_R3.command.BukkitCommandWrapper.getSuggestions(BukkitCommandWrapper.java:74) ~[paper-1.20.4.jar:git-Paper-496]
	at com.mojang.brigadier.tree.ArgumentCommandNode.listSuggestions(ArgumentCommandNode.java:71) ~[brigadier-1.2.9.jar:git-Paper-496]
	at com.mojang.brigadier.CommandDispatcher.getCompletionSuggestions(CommandDispatcher.java:551) ~[paper-1.20.4.jar:?]
	at com.mojang.brigadier.CommandDispatcher.getCompletionSuggestions(CommandDispatcher.java:531) ~[paper-1.20.4.jar:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.sendServerSuggestions(ServerGamePacketListenerImpl.java:842) ~[?:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.lambda$handleCustomCommandSuggestions0$2(ServerGamePacketListenerImpl.java:808) ~[?:?]
	at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.20.4.jar:git-Paper-496]
	at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:149) ~[?:?]
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
	at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1465) ~[paper-1.20.4.jar:git-Paper-496]
	at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:194) ~[paper-1.20.4.jar:git-Paper-496]
	at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:123) ~[?:?]
	at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1442) ~[paper-1.20.4.jar:git-Paper-496]
	at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1365) ~[paper-1.20.4.jar:git-Paper-496]
	at net.minecraft.util.thread.BlockableEventLoop.runAllTasks(BlockableEventLoop.java:112) ~[?:?]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1557) ~[paper-1.20.4.jar:git-Paper-496]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1226) ~[paper-1.20.4.jar:git-Paper-496]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[paper-1.20.4.jar:git-Paper-496]
	at java.lang.Thread.run(Thread.java:1583) ~[?:?]
Caused by: java.lang.NullPointerException: Cannot invoke "com.booksaw.betterTeams.team.TeamManager.getLoadedTeamListClone()" because the return value of "com.booksaw.betterTeams.Team.getTeamManager()" is null
	at com.booksaw.betterTeams.commands.SubCommand.addTeamStringList(SubCommand.java:160) ~[BetterTeams-4.9.4.jar:?]
	at com.booksaw.betterTeams.commands.teama.InviteTeama.onTabComplete(InviteTeama.java:83) ~[BetterTeams-4.9.4.jar:?]
	at com.booksaw.betterTeams.commands.ParentCommand.onTabComplete(ParentCommand.java:232) ~[BetterTeams-4.9.4.jar:?]
	at com.booksaw.betterTeams.BooksawCommand.tabComplete(BooksawCommand.java:91) ~[BetterTeams-4.9.4.jar:?]
	at org.bukkit.command.Command.tabComplete(Command.java:93) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.command.SimpleCommandMap.tabComplete(SimpleCommandMap.java:240) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
	... 21 more

### Output of /teama version

[22:42:36 ERROR]: Something went wrong while executing the command, please report this https://github.com/booksaw/BetterTeams/issues/new/choose
[22:42:36 WARN]: java.lang.NullPointerException: Cannot invoke "Object.getClass()" because the return value of "com.booksaw.betterTeams.Team.getTeamManager()" is null
[22:42:36 WARN]: 	at BetterTeams-4.9.4.jar//com.booksaw.betterTeams.commands.teama.VersionTeama.onCommand(VersionTeama.java:25)
[22:42:36 WARN]: 	at BetterTeams-4.9.4.jar//com.booksaw.betterTeams.commands.ParentCommand.onCommand(ParentCommand.java:135)
[22:42:36 WARN]: 	at BetterTeams-4.9.4.jar//com.booksaw.betterTeams.BooksawCommand.runExecution(BooksawCommand.java:73)
[22:42:36 WARN]: 	at BetterTeams-4.9.4.jar//com.booksaw.betterTeams.BooksawCommand.lambda$execute$0(BooksawCommand.java:60)
[22:42:36 WARN]: 	at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftTask.run(CraftTask.java:101)
[22:42:36 WARN]: 	at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57)
[22:42:36 WARN]: 	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[22:42:36 WARN]: 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
[22:42:36 WARN]: 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
[22:42:36 WARN]: 	at java.base/java.lang.Thread.run(Thread.java:1583)
[22:42:36 WARN]: Could not find the message with the reference internalError

**Comment by booksaw** [comment]
What are the logs when betterteams starts?

**Comment by booksaw** [comment]
This issue is being closed for inactivity. If you are still having problems feel free to open a new issue linking this one, make sure you answer any questions asked in the new issue.
