### ISSUE TITLE
[BUG]  Sender is null

### ISSUE THREAD

**Issue by bobhenl** [booksaw/BetterTeams#654]
### What is the bug?

Hello, I got the error that sender is null, unfortunately, I don't know why.

### Expected Behaviour

No error

### How to Reproduce

It looks like the player used teamchat?

### Error message

11:03:10] [Async Chat Thread - #94/INFO]: [BetterTeams]§b[Team]§f **Indev§r§f: uhh
[11:03:12] [Server thread/INFO]: [ChatControlRed] [standard2] NukexKiwiz: . . .
[11:03:13] [Craft Scheduler Thread - 2305 - BetterTeams/WARN]: [BetterTeams] Plugin BetterTeams v4.10.0 generated an exception while executing task 41344706
java.lang.NullPointerException: Cannot invoke "org.bukkit.command.CommandSender.sendMessage(String)" because "sender" is null
    at BetterTeams-4.10.0.jar/com.booksaw.betterTeams.message.MessageManager.sendMessage(MessageManager.java:191) ~[BetterTeams-4.10.0.jar:?]
    at BetterTeams-4.10.0.jar/com.booksaw.betterTeams.Team$1.run(Team.java:804) ~[BetterTeams-4.10.0.jar:?]
    at org.bukkit.craftbukkit.scheduler.CraftTask.run(CraftTask.java:86) ~[purpur-1.21.jar:1.21-2284-4e55e26]
    at org.bukkit.craftbukkit.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[purpur-1.21.jar:1.21-2284-4e55e26]
    at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[purpur-1.21.jar:?]
    at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
    at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
    at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]

### Output of /teama version

[22:28:13 INFO]: Storage Method: com.booksaw.betterTeams.team.storage.storageManager.SQLStorageManager
[22:28:13 INFO]: Minecraft Version: 1.21-2284-4e55e26 (MC: 1.21)
[22:28:13 INFO]: Language Selected: messages
[22:28:13 INFO]: Online mode: false
[22:28:13 INFO]: Player count: 44
[22:28:13 INFO]: Current plugin version: 4.10.0

**Comment by booksaw** [comment]
This bug has been fixed and the patch will be included in the next update. Thank you for reporting.
