### ISSUE TITLE
[BUG] Command /team chest claim not work on 1.21.1

### ISSUE THREAD

**Issue by mizpablito** [booksaw/BetterTeams#656]
### What is the bug?

Hello, players report a problem with using the `/team chest claim` command, even checking with full permissions gives the same error. According to the information obtained earlier on version 1.20.4 of the server and the previous version of the plugin the command worked correctly.

### Expected Behaviour

Classically, for the command to work correctly with its assumptions 😉

### How to Reproduce

1. The player who is the team owner or the deputy stands on the chest
2. executes the command `/team chest claim`
3. The player receives a message with a problem that the command cannot be executed, and the following error appears in the console

### Error message

```js
[19:31:02 INFO]: MizPablito issued server command: /team chest claim
[19:31:02 ERROR]: Something went wrong while executing the command, please report this https://github.com/booksaw/BetterTeams/issues/new/choose
[19:31:02 WARN]: java.lang.IllegalStateException: Tile is null, asynchronous access? CraftBlock{pos=BlockPos{x=1591, y=62, z=-7374},type=CHEST,data=Block{minecraft:chest}[facing=west,type=left,waterlogged=false],fluid=net.minecraft.world.level.material.EmptyFluid@22044776}
[19:31:02 WARN]:        at com.google.common.base.Preconditions.checkState(Preconditions.java:601)
[19:31:02 WARN]:        at org.bukkit.craftbukkit.block.CraftBlockStates$BlockEntityStateFactory.createBlockState(CraftBlockStates.java:102)
[19:31:02 WARN]:        at org.bukkit.craftbukkit.block.CraftBlockStates$BlockEntityStateFactory.createBlockState(CraftBlockStates.java:88)
[19:31:02 WARN]:        at org.bukkit.craftbukkit.block.CraftBlockStates.getBlockState(CraftBlockStates.java:306)
[19:31:02 WARN]:        at org.bukkit.craftbukkit.block.CraftBlockStates.getBlockState(CraftBlockStates.java:254)
[19:31:02 WARN]:        at org.bukkit.craftbukkit.block.CraftBlockStates.getBlockState(CraftBlockStates.java:239)
[19:31:02 WARN]:        at org.bukkit.craftbukkit.block.CraftBlock.getState(CraftBlock.java:334)
[19:31:02 WARN]:        at BetterTeams-4.10.0.jar//com.booksaw.betterTeams.team.TeamManager.getClaimingTeam(TeamManager.java:228)
[19:31:02 WARN]:        at BetterTeams-4.10.0.jar//com.booksaw.betterTeams.Team.getClaimingTeam(Team.java:82)
[19:31:02 WARN]:        at BetterTeams-4.10.0.jar//com.booksaw.betterTeams.commands.team.chest.ChestClaimCommand.onCommand(ChestClaimCommand.java:34)
[19:31:02 WARN]:        at BetterTeams-4.10.0.jar//com.booksaw.betterTeams.commands.presets.TeamSubCommand.onCommand(TeamSubCommand.java:68)
[19:31:02 WARN]:        at BetterTeams-4.10.0.jar//com.booksaw.betterTeams.commands.ParentCommand.onCommand(ParentCommand.java:135)
[19:31:02 WARN]:        at BetterTeams-4.10.0.jar//com.booksaw.betterTeams.commands.ParentCommand.onCommand(ParentCommand.java:82)
[19:31:02 WARN]:        at BetterTeams-4.10.0.jar//com.booksaw.betterTeams.commands.ParentCommand.onCommand(ParentCommand.java:135)
[19:31:02 WARN]:        at BetterTeams-4.10.0.jar//com.booksaw.betterTeams.BooksawCommand.runExecution(BooksawCommand.java:72)
[19:31:02 WARN]:        at BetterTeams-4.10.0.jar//com.booksaw.betterTeams.BooksawCommand.lambda$execute$0(BooksawCommand.java:59)
[19:31:02 WARN]:        at org.bukkit.craftbukkit.scheduler.CraftTask.run(CraftTask.java:86)
[19:31:02 WARN]:        at org.bukkit.craftbukkit.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57)
[19:31:02 WARN]:        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[19:31:02 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
[19:31:02 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
[19:31:02 WARN]:        at java.base/java.lang.Thread.run(Thread.java:1583)
```

### Output of /teama version

```bash
[19:42:49 INFO]: Storage Method: com.booksaw.betterTeams.team.storage.storageManager.SQLStorageManager
[19:42:49 INFO]: Minecraft Version: 1.21.1-2291-bba87bf (MC: 1.21.1)
[19:42:49 INFO]: Language Selected: pl
[19:42:49 INFO]: Online mode: false
[19:42:49 INFO]: Player count: 12
[19:42:49 INFO]: Wersja pluginu: 4.10.0
```

### Additional Information

```
Current Purpur Version: 1.21.1-2291-bba87bf (MC: 1.21.1)
```

File `chestpermissions.yml`:
```yaml
claim:
  enabled: true
  rank: ADMIN
remove:
  enabled: true
  rank: ADMIN
removeall:
  enabled: true
  rank: OWNER
```

**Comment by booksaw** [comment]
This bug has been fixed and the patch will be included in the next update. Thank you for reporting.
