### ISSUE TITLE
[BUG] Team /chest claim not working on 1.20.4

### ISSUE THREAD

**Issue by SirPorkus** [booksaw/BetterTeams#658]
### What is the bug?

When trying to claim a chest as part of a team with `/team chest claim`, it does not work and gives an error in the console.

### Expected Behaviour

To successfully claim a team chest

### How to Reproduce

1. Load a server on 1.20.4 with BetterTeams
2. Go to a random location
3. Place a chest
4. Do /team chest claim
5. Look at the console to see the error

### Error message

[10:28:04 ERROR]: Something went wrong while executing the command, please report this https://github.com/booksaw/BetterTeams/issues/new/choose
[10:28:04 WARN]: java.lang.IllegalStateException: Tile is null, asynchronous access? CraftBlock{pos=BlockPosition{x=-176, y=69, z=487},type=CHEST,data=Block{minecraft:chest}[facing=east,type=single,waterlogged=false],fluid=net.minecraft.world.level.material.FluidTypeEmpty@76af95cc}
[10:28:04 WARN]:        at com.google.common.base.Preconditions.checkState(Preconditions.java:601)
[10:28:04 WARN]:        at org.bukkit.craftbukkit.v1_20_R3.block.CraftBlockStates$BlockEntityStateFactory.createBlockState(CraftBlockStates.java:98)
[10:28:04 WARN]:        at org.bukkit.craftbukkit.v1_20_R3.block.CraftBlockStates$BlockEntityStateFactory.createBlockState(CraftBlockStates.java:84)
[10:28:04 WARN]:        at org.bukkit.craftbukkit.v1_20_R3.block.CraftBlockStates.getBlockState(CraftBlockStates.java:297)
[10:28:04 WARN]:        at org.bukkit.craftbukkit.v1_20_R3.block.CraftBlockStates.getBlockState(CraftBlockStates.java:249)
[10:28:04 WARN]:        at org.bukkit.craftbukkit.v1_20_R3.block.CraftBlockStates.getBlockState(CraftBlockStates.java:234)
[10:28:04 WARN]:        at org.bukkit.craftbukkit.v1_20_R3.block.CraftBlock.getState(CraftBlock.java:334)
[10:28:04 WARN]:        at 17129 - Better Teams.jar//com.booksaw.betterTeams.team.TeamManager.getClaimingTeam(TeamManager.java:228)
[10:28:04 WARN]:        at 17129 - Better Teams.jar//com.booksaw.betterTeams.Team.getClaimingTeam(Team.java:82)
[10:28:04 WARN]:        at 17129 - Better Teams.jar//com.booksaw.betterTeams.commands.team.chest.ChestClaimCommand.onCommand(ChestClaimCommand.java:34)
[10:28:04 WARN]:        at 17129 - Better Teams.jar//com.booksaw.betterTeams.commands.presets.TeamSubCommand.onCommand(TeamSubCommand.java:68)
[10:28:04 WARN]:        at 17129 - Better Teams.jar//com.booksaw.betterTeams.commands.ParentCommand.onCommand(ParentCommand.java:135)
[10:28:04 WARN]:        at 17129 - Better Teams.jar//com.booksaw.betterTeams.commands.ParentCommand.onCommand(ParentCommand.java:82)
[10:28:04 WARN]:        at 17129 - Better Teams.jar//com.booksaw.betterTeams.commands.ParentCommand.onCommand(ParentCommand.java:135)
[10:28:04 WARN]:        at 17129 - Better Teams.jar//com.booksaw.betterTeams.BooksawCommand.runExecution(BooksawCommand.java:72)
[10:28:04 WARN]:        at 17129 - Better Teams.jar//com.booksaw.betterTeams.BooksawCommand.lambda$execute$0(BooksawCommand.java:59)
[10:28:04 WARN]:        at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftTask.run(CraftTask.java:101)
[10:28:04 WARN]:        at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57)
[10:28:04 WARN]:        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[10:28:04 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
[10:28:04 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
[10:28:04 WARN]:        at java.base/java.lang.Thread.run(Thread.java:1583)

### Output of /teama version

[10:32:37 INFO]: Storage Method: com.booksaw.betterTeams.team.storage.storageManager.SeparatedYamlStorageManager
[10:32:37 INFO]: Minecraft Version: git-Paper-497 (MC: 1.20.4)
[10:32:37 INFO]: Language Selected: messages
[10:32:37 INFO]: Online mode: true
[10:32:37 INFO]: Player count: 1
[10:32:37 INFO]: Current plugin version: 4.10.0

**Comment by mizpablito** [comment]
Is related to #656

**Comment by SirPorkus** [comment]
Any update on when this might be fixed?

**Comment by booksaw** [comment]
Closing as duplicate of #656
