### ISSUE TITLE
[BUG] Error on /team top

### ISSUE THREAD

**Issue by IQsmYT** [booksaw/BetterTeams#660]
### What is the bug?

When you do /team top

it sends you this error message

[17:13:45 WARN]: [BetterTeams] Plugin BetterTeams v4.10.0 generated an exception while executing task 1697784
java.lang.IllegalArgumentException: name cannot be null
        at com.google.common.base.Preconditions.checkArgument(Preconditions.java:143) ~[guava-32.1.2-jre.jar:?]
        at org.bukkit.craftbukkit.v1_20_R3.CraftServer.getPlayer(CraftServer.java:675) ~[paper-1.20.4.jar:git-Paper-"f4c7d37"]
        at org.bukkit.Bukkit.getPlayer(Bukkit.java:715) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at com.booksaw.betterTeams.team.TeamManager.getTeam(TeamManager.java:90) ~[BetterTeams-4.10.0.jar:?]
        at com.booksaw.betterTeams.Team.getTeam(Team.java:70) ~[BetterTeams-4.10.0.jar:?]
        at com.booksaw.betterTeams.commands.team.TopCommand$1.run(TopCommand.java:39) ~[BetterTeams-4.10.0.jar:?]
        at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.20.4.jar:git-Paper-"f4c7d37"]
        at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[paper-1.20.4.jar:git-Paper-"f4c7d37"]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[paper-1.20.4.jar:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]

### Expected Behaviour

Fix the bug

### How to Reproduce

1. /team top
2. error message

### Error message

[17:13:45 WARN]: [BetterTeams] Plugin BetterTeams v4.10.0 generated an exception while executing task 1697784
java.lang.IllegalArgumentException: name cannot be null
        at com.google.common.base.Preconditions.checkArgument(Preconditions.java:143) ~[guava-32.1.2-jre.jar:?]
        at org.bukkit.craftbukkit.v1_20_R3.CraftServer.getPlayer(CraftServer.java:675) ~[paper-1.20.4.jar:git-Paper-"f4c7d37"]
        at org.bukkit.Bukkit.getPlayer(Bukkit.java:715) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at com.booksaw.betterTeams.team.TeamManager.getTeam(TeamManager.java:90) ~[BetterTeams-4.10.0.jar:?]
        at com.booksaw.betterTeams.Team.getTeam(Team.java:70) ~[BetterTeams-4.10.0.jar:?]
        at com.booksaw.betterTeams.commands.team.TopCommand$1.run(TopCommand.java:39) ~[BetterTeams-4.10.0.jar:?]
        at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.20.4.jar:git-Paper-"f4c7d37"]
        at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[paper-1.20.4.jar:git-Paper-"f4c7d37"]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[paper-1.20.4.jar:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]

### Output of /teama version

Latest version

**Comment by booksaw** [comment]
I need the full output of /teama version as this is a storage related bug.
Additionally, try setting `rebuildLookups` to true in config.yaml and restarting your server, it should auto-repair.

**Comment by booksaw** [comment]
This issue is being closed for inactivity. If you are still having problems feel free to open a new issue linking this one, make sure you answer any questions asked in the new issue.
