### ISSUE TITLE
[BUG] /team chest claim gives error 

### ISSUE THREAD

**Issue by 1nv1sibl3** [booksaw/BetterTeams#668]
### What is the bug?

```
[06:17:09 INFO]: Invis1bl3 issued server command: /teama chest claim Invisible
[06:17:09 ERROR]: Something went wrong while executing the command, please report this https://github.com/booksaw/BetterTeams/issues/new/choose
[06:17:09 WARN]: java.lang.IllegalStateException: Tile is null, asynchronous access? CraftBlock{pos=BlockPos{x=55, y=63, z=-28},type=CHEST,data=Block{minecraft:chest}[facing=west,type=single,waterlogged=false],fluid=net.minecraft.world.level.material.EmptyFluid@4854b1d6}
[06:17:09 WARN]:        at com.google.common.base.Preconditions.checkState(Preconditions.java:601)
[06:17:09 WARN]:        at org.bukkit.craftbukkit.block.CraftBlockStates$BlockEntityStateFactory.createBlockState(CraftBlockStates.java:102)
[06:17:09 WARN]:        at org.bukkit.craftbukkit.block.CraftBlockStates$BlockEntityStateFactory.createBlockState(CraftBlockStates.java:88)
[06:17:09 WARN]:        at org.bukkit.craftbukkit.block.CraftBlockStates.getBlockState(CraftBlockStates.java:306)
[06:17:09 WARN]:        at org.bukkit.craftbukkit.block.CraftBlockStates.getBlockState(CraftBlockStates.java:254)
[06:17:09 WARN]:        at org.bukkit.craftbukkit.block.CraftBlockStates.getBlockState(CraftBlockStates.java:239)
[06:17:09 WARN]:        at org.bukkit.craftbukkit.block.CraftBlock.getState(CraftBlock.java:334)
[06:17:09 WARN]:        at BetterTeams-4.10.0.jar//com.booksaw.betterTeams.team.TeamManager.getClaimingTeam(TeamManager.java:228)
[06:17:09 WARN]:        at BetterTeams-4.10.0.jar//com.booksaw.betterTeams.Team.getClaimingTeam(Team.java:82)
[06:17:09 WARN]:        at BetterTeams-4.10.0.jar//com.booksaw.betterTeams.commands.teama.chest.ChestClaimTeama.onCommand(ChestClaimTeama.java:31)
[06:17:09 WARN]:        at BetterTeams-4.10.0.jar//com.booksaw.betterTeams.commands.presets.TeamSelectSubCommand.onCommand(TeamSelectSubCommand.java:28)
[06:17:09 WARN]:        at BetterTeams-4.10.0.jar//com.booksaw.betterTeams.commands.ParentCommand.onCommand(ParentCommand.java:135)
[06:17:09 WARN]:        at BetterTeams-4.10.0.jar//com.booksaw.betterTeams.commands.ParentCommand.onCommand(ParentCommand.java:82)
[06:17:09 WARN]:        at BetterTeams-4.10.0.jar//com.booksaw.betterTeams.commands.ParentCommand.onCommand(ParentCommand.java:135)
[06:17:09 WARN]:        at BetterTeams-4.10.0.jar//com.booksaw.betterTeams.BooksawCommand.runExecution(BooksawCommand.java:72)
[06:17:09 WARN]:        at BetterTeams-4.10.0.jar//com.booksaw.betterTeams.BooksawCommand.lambda$execute$0(BooksawCommand.java:59)
[06:17:09 WARN]:        at org.bukkit.craftbukkit.scheduler.CraftTask.run(CraftTask.java:86)
[06:17:09 WARN]:        at org.bukkit.craftbukkit.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57)
[06:17:09 WARN]:        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[06:17:09 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
[06:17:09 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
[06:17:09 WARN]:        at java.base/java.lang.Thread.run(Thread.java:1583)
```

It seems like /team chest claim gives error

### Expected Behaviour

It should work as the command is intended to work 

### How to Reproduce

Just run that command.

### Output of /teama version

4.10.0

**Comment by booksaw** [comment]
Closing as duplicate of #656
