### ISSUE TITLE
[BUG] Chest claim command

### ISSUE THREAD

**Issue by qwerio** [booksaw/BetterTeams#677]
### What is the bug?

Usage of the `/team chest claim` command causes an issue.

### Expected Behaviour

To be able to claim the chest.

### How to Reproduce

/team create <name>
/team chest claim

### Error message

[22:55:18 WARN]: java.lang.IllegalStateException: Tile is null, asynchronous access? CraftBlock{pos=BlockPos{x=6, y=179, z=-236},type=CHEST,data=Block{minecraft:chest}[facing=north,type=single,waterlogged=false],fluid=net.minecraft.world.level.material.EmptyFluid@3d278e95}
[22:55:18 WARN]:        at com.google.common.base.Preconditions.checkState(Preconditions.java:601)
[22:55:18 WARN]:        at org.bukkit.craftbukkit.block.CraftBlockStates$BlockEntityStateFactory.createBlockState(CraftBlockStates.java:102)
[22:55:18 WARN]:        at org.bukkit.craftbukkit.block.CraftBlockStates$BlockEntityStateFactory.createBlockState(CraftBlockStates.java:88)
[22:55:18 WARN]:        at org.bukkit.craftbukkit.block.CraftBlockStates.getBlockState(CraftBlockStates.java:306)
[22:55:18 WARN]:        at org.bukkit.craftbukkit.block.CraftBlockStates.getBlockState(CraftBlockStates.java:254)
[22:55:18 WARN]:        at org.bukkit.craftbukkit.block.CraftBlockStates.getBlockState(CraftBlockStates.java:239)
[22:55:18 WARN]:        at org.bukkit.craftbukkit.block.CraftBlock.getState(CraftBlock.java:334)
[22:55:18 WARN]:        at BetterTeams-4.10.0.jar//com.booksaw.betterTeams.team.TeamManager.getClaimingTeam(TeamManager.java:228)
[22:55:18 WARN]:        at BetterTeams-4.10.0.jar//com.booksaw.betterTeams.Team.getClaimingTeam(Team.java:82)
[22:55:18 WARN]:        at BetterTeams-4.10.0.jar//com.booksaw.betterTeams.commands.team.chest.ChestClaimCommand.onCommand(ChestClaimCommand.java:34)
[22:55:18 WARN]:        at BetterTeams-4.10.0.jar//com.booksaw.betterTeams.commands.presets.TeamSubCommand.onCommand(TeamSubCommand.java:68)
[22:55:18 WARN]:        at BetterTeams-4.10.0.jar//com.booksaw.betterTeams.commands.ParentCommand.onCommand(ParentCommand.java:135)
[22:55:18 WARN]:        at BetterTeams-4.10.0.jar//com.booksaw.betterTeams.commands.ParentCommand.onCommand(ParentCommand.java:82)
[22:55:18 WARN]:        at BetterTeams-4.10.0.jar//com.booksaw.betterTeams.commands.ParentCommand.onCommand(ParentCommand.java:135)
[22:55:18 WARN]:        at BetterTeams-4.10.0.jar//com.booksaw.betterTeams.BooksawCommand.runExecution(BooksawCommand.java:72)
[22:55:18 WARN]:        at BetterTeams-4.10.0.jar//com.booksaw.betterTeams.BooksawCommand.lambda$execute$0(BooksawCommand.java:59)
[22:55:18 WARN]:        at org.bukkit.craftbukkit.scheduler.CraftTask.run(CraftTask.java:86)
[22:55:18 WARN]:        at org.bukkit.craftbukkit.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57)
[22:55:18 WARN]:        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[22:55:18 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
[22:55:18 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
[22:55:18 WARN]:        at java.base/java.lang.Thread.run(Thread.java:1583)

### Output of /teama version

[22:56:34 INFO]: Storage Method: com.booksaw.betterTeams.team.storage.storageManager.SeparatedYamlStorageManager
[22:56:34 INFO]: Minecraft Version: 1.21.1-2327-4b57bed (MC: 1.21.1)
[22:56:34 INFO]: Language Selected: messages
[22:56:34 INFO]: Online mode: true
[22:56:34 INFO]: Player count: 1
[22:56:34 INFO]: Current plugin version: 4.10.0

**Comment by Xenox003** [comment]
+1

Server Purpur 1.21.1
BetterTeams 4.10.0

**Comment by caf600** [comment]
I just added BetterTeams to my server and the Chest Claiming is not working.

**Comment by booksaw** [comment]
Closing as duplicate of #656
