### ISSUE TITLE
[BUG] /team leaves do not work. Default config

### ISSUE THREAD

**Issue by TylerHaoNhot** [booksaw/BetterTeams#683]
### What is the bug?

/team leave does not work. /teama leave <player> too. Im using the default configuration.
Version: BetterTeam 4.10.0 Minecraft Paper 1.21.1 build 132

### Expected Behaviour

Make it work like normal.

### How to Reproduce

1 run command: /team leave
2 error: Something went wrong while executing the command, please report this 
https://github.com/booksaw/BetterTeams/issues/new/choose

### Error message

[11:56:43 INFO]: NhotCutii issued server command: /team leave
[11:56:43 ERROR]: Something went wrong while executing the command, please report this 
https://github.com/booksaw/BetterTeams/issues/new/choose
[11:56:43 WARN]: java.lang.IllegalStateException: Unregistered scoreboard component
[11:56:43 WARN]: 	at com.google.common.base.Preconditions.checkState(Preconditions.java:512)
[11:56:43 WARN]: 	at org.bukkit.craftbukkit.scoreboard.CraftTeam.checkState(CraftTeam.java:396)
[11:56:43 WARN]: 	at org.bukkit.craftbukkit.scoreboard.CraftTeam.hasEntry(CraftTeam.java:297)
[11:56:43 WARN]: 	at BetterTeams-4.10.0.jar//com.booksaw.betterTeams.events.MCTeamManagement.remove(MCTeamManagement.java:114)
[11:56:43 WARN]: 	at BetterTeams-4.10.0.jar//com.booksaw.betterTeams.events.MCTeamManagement.remove(MCTeamManagement.java:94)
[11:56:43 WARN]: 	at BetterTeams-4.10.0.jar//com.booksaw.betterTeams.team.MemberSetComponent.remove(MemberSetComponent.java:71)
[11:56:43 WARN]: 	at BetterTeams-4.10.0.jar//com.booksaw.betterTeams.Team.removePlayer(Team.java:669)
[11:56:43 WARN]: 	at BetterTeams-4.10.0.jar//com.booksaw.betterTeams.Team.removePlayer(Team.java:656)
[11:56:43 WARN]: 	at BetterTeams-4.10.0.jar//com.booksaw.betterTeams.commands.team.LeaveCommand.onCommand(LeaveCommand.java:26)
[11:56:43 WARN]: 	at BetterTeams-4.10.0.jar//com.booksaw.betterTeams.commands.presets.TeamSubCommand.onCommand(TeamSubCommand.java:68)
[11:56:43 WARN]: 	at BetterTeams-4.10.0.jar//com.booksaw.betterTeams.commands.ParentCommand.onCommand(ParentCommand.java:135)
[11:56:43 WARN]: 	at BetterTeams-4.10.0.jar//com.booksaw.betterTeams.BooksawCommand.runExecution(BooksawCommand.java:72)
[11:56:43 WARN]: 	at BetterTeams-4.10.0.jar//com.booksaw.betterTeams.BooksawCommand.lambda$execute$0(BooksawCommand.java:59)
[11:56:43 WARN]: 	at org.bukkit.craftbukkit.scheduler.CraftTask.run(CraftTask.java:86)
[11:56:43 WARN]: 	at org.bukkit.craftbukkit.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57)
[11:56:43 WARN]: 	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[11:56:43 WARN]: 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
[11:56:43 WARN]: 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
[11:56:43 WARN]: 	at java.base/java.lang.Thread.run(Thread.java:1583)

### Output of /teama version

Same: Something went wrong while executing the command, please report this 
https://github.com/booksaw/BetterTeams/issues/new/choose

**Comment by booksaw** [comment]
This is due to a plugin conflict on your server, see https://github.com/booksaw/BetterTeams/wiki/Managing-the-TAB-Menu

**Comment by booksaw** [comment]
This issue is being closed for inactivity. If you are still having problems feel free to open a new issue linking this one, make sure you answer any questions asked in the new issue.
