### ISSUE TITLE
[BUG] team setwarp is not working

### ISSUE THREAD

**Issue by ichibanS** [booksaw/BetterTeams#684]
### What is the bug?

can not set new warps with /team setwarp <warpname>

### Expected Behaviour

it should create a warp where the player is standing with the name provided

### How to Reproduce

run the command /team setwarp <warpname>
an error pops up in the chat saying that there was an error and you should contact the server owner

### Error message

[19:39:56 INFO]: ichiban_s issued server command: /team setwarp sfdka
[19:39:56 ERROR]: Something went wrong while executing the command, please report this https://github.com/booksaw/BetterTeams/issues/new/choose
[19:39:56 WARN]: java.lang.NullPointerException: Cannot invoke "org.bukkit.World.getName()" because the return value of "org.bukkit.Location.getWorld()" is null
[19:39:56 WARN]:        at BetterTeams-4.10.0.jar//com.booksaw.betterTeams.team.LocationSetComponent.getString(LocationSetComponent.java:36)
[19:39:56 WARN]:        at BetterTeams-4.10.0.jar//com.booksaw.betterTeams.Warp.toString(Warp.java:47)
[19:39:56 WARN]:        at BetterTeams-4.10.0.jar//com.booksaw.betterTeams.team.WarpSetComponent.toString(WarpSetComponent.java:34)
[19:39:56 WARN]:        at BetterTeams-4.10.0.jar//com.booksaw.betterTeams.team.WarpSetComponent.toString(WarpSetComponent.java:9)
[19:39:56 WARN]:        at BetterTeams-4.10.0.jar//com.booksaw.betterTeams.team.SetTeamComponent.getConvertedList(SetTeamComponent.java:61)
[19:39:56 WARN]:        at BetterTeams-4.10.0.jar//com.booksaw.betterTeams.team.WarpSetComponent.save(WarpSetComponent.java:18)
[19:39:56 WARN]:        at BetterTeams-4.10.0.jar//com.booksaw.betterTeams.Team.saveWarps(Team.java:1361)
[19:39:56 WARN]:        at BetterTeams-4.10.0.jar//com.booksaw.betterTeams.Team.addWarp(Team.java:1376)
[19:39:56 WARN]:        at BetterTeams-4.10.0.jar//com.booksaw.betterTeams.commands.team.SetWarpCommand.onCommand(SetWarpCommand.java:36)
[19:39:56 WARN]:        at BetterTeams-4.10.0.jar//com.booksaw.betterTeams.commands.presets.TeamSubCommand.onCommand(TeamSubCommand.java:68)
[19:39:56 WARN]:        at BetterTeams-4.10.0.jar//com.booksaw.betterTeams.commands.ParentCommand.onCommand(ParentCommand.java:135)
[19:39:56 WARN]:        at BetterTeams-4.10.0.jar//com.booksaw.betterTeams.BooksawCommand.runExecution(BooksawCommand.java:72)
[19:39:56 WARN]:        at BetterTeams-4.10.0.jar//com.booksaw.betterTeams.BooksawCommand.lambda$execute$0(BooksawCommand.java:59)
[19:39:56 WARN]:        at org.bukkit.craftbukkit.scheduler.CraftTask.run(CraftTask.java:86)
[19:39:56 WARN]:        at org.bukkit.craftbukkit.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57)
[19:39:56 WARN]:        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[19:39:56 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
[19:39:56 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
[19:39:56 WARN]:        at java.base/java.lang.Thread.run(Unknown Source)

### Output of /teama version

when I run /teama <team> <warpname> 
it says that that team had already maximum warps while I have in the config -1 as the limit wich means no limits

### Additional Information

[21:09:39 INFO]: Server Plugins (59):
[21:09:39 INFO]: Paper Plugins:
[21:09:39 INFO]:  - AdvancedServerList
[21:09:39 INFO]: Bukkit Plugins:
[21:09:39 INFO]:  - AdvancedBan, AdvancedPlHide, AdvancedRegionMarket, ajLeaderboards, AntiPopup, AuthMe, AutoWhitelistRemove, AxGraves, AxiomPaper, Back
[21:09:39 INFO]:  BankPlus, BetterRTP, BetterTeams, BlueMap, Chunky, Citizens, CoreProtect, CraftingStore, DecentHolograms, DiscordSRV
[21:09:39 INFO]:  EliteMobs, Essentials, EssentialsChat, EssentialsSpawn, EzChestShop, floodgate, FreeMinecraftModels, Geyser-Spigot, GeyserExtras, GriefPrevention
[21:09:39 INFO]:  GSit, Hurricane, ImageFrame, KnockbackSync, LibsDisguises, LuckPerms, Maintenance, Multiverse-Core, NoEmotecraft, OpenInv
[21:09:39 INFO]:  packetevents, PlaceholderAPI, PlayerStats, ProtocolLib, PvPManager, SkinsRestorer, SuperVanish, TAB, TeaksTweaks, TerraformGenerator
[21:09:39 INFO]:  Vault, VeinMiner, ViaVersion, voicechat, *VoidWorld, WorldEdit, WorldGuard, WorldGuardExtraFlags

**Comment by booksaw** [comment]
I have tested on my server and I am able to run the /team setwarp command so this is likely some server configuration issue, please could you provide further information. I'm guessing it is going to a problem relating to your world manager plugin.

**Comment by booksaw** [comment]
This issue is being closed for inactivity. If you are still having problems feel free to open a new issue linking this one, make sure you answer any questions asked in the new issue.
