### ISSUE TITLE
[BUG] /team kick errors

### ISSUE THREAD

**Issue by booksaw** [booksaw/BetterTeams#69]
Team kick throwing nullPointerException 
```
[02:45:42 ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing 'team kick kAZomics' in com.booksaw.betterTeams.BooksawCommand(team)
at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:169) ~[patched_1.16.5.jar:git-Paper-467]
at org.bukkit.craftbukkit.v1_16_R3.CraftServer.dispatchCommand(CraftServer.java:806) ~[patched_1.16.5.jar:git-Paper-467]
at net.minecraft.server.v1_16_R3.PlayerConnection.handleCommand(PlayerConnection.java:2021) ~[?:git-Paper-467]
at net.minecraft.server.v1_16_R3.PlayerConnection.c(PlayerConnection.java:1832) ~[?:git-Paper-467]
at net.minecraft.server.v1_16_R3.PlayerConnection.a(PlayerConnection.java:1785) ~[?:git-Paper-467]
at net.minecraft.server.v1_16_R3.PacketPlayInChat.a(PacketPlayInChat.java:47) ~[patched_1.16.5.jar:git-Paper-467]
at net.minecraft.server.v1_16_R3.PacketPlayInChat.a(PacketPlayInChat.java:5) ~[patched_1.16.5.jar:git-Paper-467]
at net.minecraft.server.v1_16_R3.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:23) ~[patched_1.16.5.jar:git-Paper-467]
at net.minecraft.server.v1_16_R3.TickTask.run(SourceFile:18) ~[patched_1.16.5.jar:git-Paper-467]
at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.16.5.jar:git-Paper-467]
at net.minecraft.server.v1_16_R3.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.16.5.jar:git-Paper-467]
at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.16.5.jar:git-Paper-467]
at net.minecraft.server.v1_16_R3.MinecraftServer.bb(MinecraftServer.java:1133) ~[patched_1.16.5.jar:git-Paper-467]
at net.minecraft.server.v1_16_R3.MinecraftServer.executeNext(MinecraftServer.java:1126) ~[patched_1.16.5.jar:git-Paper-467]
at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.16.5.jar:git-Paper-467]
at net.minecraft.server.v1_16_R3.MinecraftServer.sleepForTick(MinecraftServer.java:1087) ~[patched_1.16.5.jar:git-Paper-467]
at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1001) ~[patched_1.16.5.jar:git-Paper-467]
at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:174) ~[patched_1.16.5.jar:git-Paper-467]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_282]
Caused by: java.lang.NullPointerException
at com.booksaw.betterTeams.Team.getTeam(Team.java:103) ~[?:?]
at com.booksaw.betterTeams.events.MCTeamManagement.remove(MCTeamManagement.java:118) ~[?:?]
at com.booksaw.betterTeams.Team.removePlayer(Team.java:915) ~[?:?]
at com.booksaw.betterTeams.commands.team.KickCommand.onCommand(KickCommand.java:47) ~[?:?]
at com.booksaw.betterTeams.commands.presets.TeamSubCommand.onCommand(TeamSubCommand.java:29) ~[?:?]
at com.booksaw.betterTeams.commands.ParentCommand.onCommand(ParentCommand.java:125) ~[?:?]
at com.booksaw.betterTeams.BooksawCommand.execute(BooksawCommand.java:57) ~[?:?]
at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159) ~[patched_1.16.5.jar:git-Paper-467]
... 18 more
```
Online player in the same team

**Comment by booksaw** [comment]
This bug has been fixed and will be included in the next update
