### ISSUE TITLE
[BUG] ClassCastException

### ISSUE THREAD

**Issue by booksaw** [booksaw/BetterTeams#87]
[09:55:21 ERROR]: Could not pass event EntityDamageByEntityEvent to BetterTeams v3.1.21
java.lang.ClassCastException: class org.bukkit.craftbukkit.v1_16_R3.entity.CraftTippedArrow cannot be cast to class org.bukkit.entity.Player (org.bukkit.craftbukkit.v1_16_R3.entity.CraftTippedArrow and org.bukkit.entity.Player are in unnamed module of loader 'app')
        at com.booksaw.betterTeams.events.DamageManagement.onDamage(DamageManagement.java:67) ~[?:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor223.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.16.5.jar:git-Paper-545]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.16.5.jar:git-Paper-545]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.5.jar:git-Paper-545]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.16.5.jar:git-Paper-545]
        at org.bukkit.craftbukkit.v1_16_R3.event.CraftEventFactory.callEvent(CraftEventFactory.java:248) ~[patched_1.16.5.jar:git-Paper-545]
        at org.bukkit.craftbukkit.v1_16_R3.event.CraftEventFactory.callEntityDamageEvent(CraftEventFactory.java:1068) ~[patched_1.16.5.jar:git-Paper-545]
        at org.bukkit.craftbukkit.v1_16_R3.event.CraftEventFactory.handleEntityDamageEvent(CraftEventFactory.java:955) ~[patched_1.16.5.jar:git-Paper-545]
        at org.bukkit.craftbukkit.v1_16_R3.event.CraftEventFactory.handleEntityDamageEvent(CraftEventFactory.java:911) ~[patched_1.16.5.jar:git-Paper-545]
        at org.bukkit.craftbukkit.v1_16_R3.event.CraftEventFactory.handleLivingEntityDamageEvent(CraftEventFactory.java:1100) ~[patched_1.16.5.jar:git-Paper-545]
        at net.minecraft.server.v1_16_R3.EntityLiving.damageEntity0(EntityLiving.java:1838) ~[patched_1.16.5.jar:git-Paper-545]
        at net.minecraft.server.v1_16_R3.EntityHuman.damageEntity0(EntityHuman.java:844) ~[patched_1.16.5.jar:git-Paper-545]
        at net.minecraft.server.v1_16_R3.EntityLiving.damageEntity(EntityLiving.java:1166) ~[patched_1.16.5.jar:git-Paper-545]
        at net.minecraft.server.v1_16_R3.EntityHuman.damageEntity(EntityHuman.java:761) ~[patched_1.16.5.jar:git-Paper-545]
        at net.minecraft.server.v1_16_R3.EntityPlayer.damageEntity(EntityPlayer.java:842) ~[patched_1.16.5.jar:git-Paper-545]
        at net.minecraft.server.v1_16_R3.EntityArrow.a(EntityArrow.java:333) ~[patched_1.16.5.jar:git-Paper-545]
        at net.minecraft.server.v1_16_R3.IProjectile.a(IProjectile.java:125) ~[patched_1.16.5.jar:git-Paper-545]
        at net.minecraft.server.v1_16_R3.EntityArrow.tick(EntityArrow.java:176) ~[patched_1.16.5.jar:git-Paper-545]
        at net.minecraft.server.v1_16_R3.EntityTippedArrow.tick(EntityTippedArrow.java:92) ~[patched_1.16.5.jar:git-Paper-545]
        at net.minecraft.server.v1_16_R3.WorldServer.entityJoinedWorld(WorldServer.java:846) ~[patched_1.16.5.jar:git-Paper-545]
        at net.minecraft.server.v1_16_R3.World.a(World.java:886) ~[patched_1.16.5.jar:git-Paper-545]
        at net.minecraft.server.v1_16_R3.WorldServer.doTick(WorldServer.java:531) ~[patched_1.16.5.jar:git-Paper-545]
        at net.minecraft.server.v1_16_R3.MinecraftServer.b(MinecraftServer.java:1364) ~[patched_1.16.5.jar:git-Paper-545]
        at net.minecraft.server.v1_16_R3.DedicatedServer.b(DedicatedServer.java:379) ~[patched_1.16.5.jar:git-Paper-545]
        at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1216) ~[patched_1.16.5.jar:git-Paper-545]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1004) ~[patched_1.16.5.jar:git-Paper-545]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[patched_1.16.5.jar:git-Paper-545]

**Comment by booksaw** [comment]
This bug has been fixed and will be included in the next update
